import type { Lesson } from "./content";

export const NAREZKI_NEW: Lesson[] = [
  // narezki-34 (4.7 MB) — N5
  {
    id: "n5-narezki-mini-dialogue",
    level: "N5",
    titleRu: "Мини-диалог на японском",
    descriptionRu: "Короткий диалог для тренировки восприятия базовых японских фраз на слух.",
    video: { type: "remote", src: "https://archive.org/download/japanese-trainer-narezki/narezki-34.mp4" },
    subtitles: [
      { startSec: 1, endSec: 3.9, ja: "早々のフリーレン 〇〇の魔法", furigana: "早々のフリーレン 〇〇の魔法" },
      { startSec: 3.9, endSec: 8.6, ja: "体からいい匂いが出る魔法", furigana: "体からいい匂いが出る魔法" },
      { startSec: 8.6, endSec: 13.9, ja: "いい匂いって言ってもどういう匂いなんだろう", furigana: "いい匂いって言ってもどういう匂いなんだろう" },
      { startSec: 13.9, endSec: 17.9, ja: "人それぞれいいと感じる匂いって違いますからね", furigana: "人それぞれいいと感じる匂いって違いますからね" },
      { startSec: 17.9, endSec: 23.9, ja: "香水のような感じや花の香りだったり爽やかな香りだったりでしょうか", furigana: "香水のような感じや花の香りだったり爽やかな香りだったりでしょうか" },
      { startSec: 23.9, endSec: 26.4, ja: "例によって試してみようか", furigana: "例によって試してみようか" },
      { startSec: 26.4, endSec: 27.8, ja: "ねえシュタルク", furigana: "ねえシュタルク" },
      { startSec: 27.8, endSec: 29.7, ja: "ん?なに?", furigana: "ん?なに?" },
      { startSec: 30, endSec: 36.6, ja: "フリーレン様お肉を焼いたような匂いが", furigana: "フリーレン様お肉を焼いたような匂いが" },
      { startSec: 36.6, endSec: 40.7, ja: "すごく香ばしいね食欲をそそるというか", furigana: "すごく香ばしいね食欲をそそるというか" },
      { startSec: 40.7, endSec: 46, ja: "この魔法を作った魔法使いにとっていい匂いということのようですね", furigana: "この魔法を作った魔法使いにとっていい匂いということのようですね" },
      { startSec: 46, endSec: 49.2, ja: "美味しそうな匂い", furigana: "美味しそうな匂い" },
      { startSec: 49.2, endSec: 50.1, ja: "な、なに?", furigana: "な、なに?" },
      { startSec: 51.1, endSec: 52.7, ja: "ていうか今日の晩飯どうする?", furigana: "ていうか今日の晩飯どうする?" },
      { startSec: 55.6, endSec: 56, ja: "肉", furigana: "肉" },
      { startSec: 56, endSec: 59, ja: "え?なに?なんか怖いんだけど", furigana: "え?なに?なんか怖いんだけど" },
      { startSec: 59, endSec: 89, ja: "ご視聴ありがとうございました", furigana: "ご視聴ありがとうございました" },
    ],
    questions: [],
  },
  // narezki-35 (7.8 MB) — N5
  {
    id: "n5-narezki-everyday-words",
    level: "N5",
    titleRu: "Повседневные слова и выражения",
    descriptionRu: "Набор полезных повседневных слов и фраз для начинающих.",
    video: { type: "remote", src: "https://archive.org/download/japanese-trainer-narezki/narezki-35.mp4" },
    subtitles: [
      { startSec: 0, endSec: 6, ja: "ユニークな日本の食べ物", furigana: "ユニークな日本の食べ物" },
      { startSec: 6, endSec: 9, ja: "フルーツサンド", furigana: "フルーツサンド" },
      { startSec: 9, endSec: 11, ja: "食パン", furigana: "食パン" },
      { startSec: 11, endSec: 14, ja: "ホイップクリーム", furigana: "ホイップクリーム" },
      { startSec: 14, endSec: 18, ja: "果物", furigana: "果物" },
      { startSec: 18, endSec: 24, ja: "ハッシュドビーフまたは林ライス", furigana: "ハッシュドビーフまたは林ライス" },
      { startSec: 24, endSec: 26, ja: "牛肉", furigana: "牛肉" },
      { startSec: 26, endSec: 29, ja: "玉ねぎ", furigana: "玉ねぎ" },
      { startSec: 29, endSec: 30.4, ja: "マッシュルーム", furigana: "マッシュルーム" },
      { startSec: 30.4, endSec: 33.4, ja: "デミグラスソース", furigana: "デミグラスソース" },
      { startSec: 33.4, endSec: 34.9, ja: "ご飯", furigana: "ご飯" },
      { startSec: 34.9, endSec: 41.1, ja: "ナポリタン", furigana: "ナポリタン" },
      { startSec: 41.1, endSec: 43.8, ja: "ケチャップスパゲッティ", furigana: "ケチャップスパゲッティ" },
      { startSec: 43.8, endSec: 46.1, ja: "ピーマン", furigana: "ピーマン" },
      { startSec: 46.1, endSec: 48, ja: "マッシュルーム", furigana: "マッシュルーム" },
      { startSec: 48, endSec: 51.1, ja: "ベーコン", furigana: "ベーコン" },
      { startSec: 51.1, endSec: 52.9, ja: "玉ねぎ", furigana: "玉ねぎ" },
      { startSec: 57, endSec: 58.5, ja: "シーフードドリア", furigana: "シーフードドリア" },
      { startSec: 58.5, endSec: 69.5, ja: "チーズ エビ イカ ホタテ ホワイトソース バターライス", furigana: "チーズ エビ イカ ホタテ ホワイトソース バターライス" },
      { startSec: 69.5, endSec: 89, ja: "カレーうどんうどん カレーとだし 万能ギ和風ハンバーグ ハンバーグ", furigana: "カレーうどんうどん カレーとだし 万能ギ和風ハンバーグ ハンバーグ" },
      { startSec: 89, endSec: 93.8, ja: "大根おろし ポン酢", furigana: "大根おろし ポン酢" },
      { startSec: 97.8, endSec: 101.6, ja: "メンチカツ パン粉", furigana: "メンチカツ パン粉" },
      { startSec: 101.6, endSec: 103.8, ja: "ひき肉", furigana: "ひき肉" },
      { startSec: 103.8, endSec: 109.8, ja: "うなじゅう", furigana: "うなじゅう" },
      { startSec: 109.8, endSec: 112.5, ja: "うなぎのかば焼き", furigana: "うなぎのかば焼き" },
      { startSec: 112.5, endSec: 114.2, ja: "白ご飯", furigana: "白ご飯" },
      { startSec: 114.2, endSec: 119.7, ja: "焼きそばパン", furigana: "焼きそばパン" },
      { startSec: 119.7, endSec: 122.5, ja: "こっぺパン", furigana: "こっぺパン" },
      { startSec: 122.5, endSec: 124, ja: "焼きそば", furigana: "焼きそば" },
      { startSec: 124, endSec: 126.5, ja: "紅生姜", furigana: "紅生姜" },
      { startSec: 126.5, endSec: 128.9, ja: "青のり", furigana: "青のり" },
      { startSec: 131.6, endSec: 134.3, ja: "卵かけご飯", furigana: "卵かけご飯" },
      { startSec: 134.3, endSec: 137.1, ja: "白ご飯", furigana: "白ご飯" },
      { startSec: 137.1, endSec: 139.5, ja: "生卵", furigana: "生卵" },
      { startSec: 139.5, endSec: 141.8, ja: "醤油", furigana: "醤油" },
      { startSec: 141.8, endSec: 147.1, ja: "どれを食べてみたいですか?", furigana: "どれを食べてみたいですか?" },
    ],
    questions: [],
  },
  // narezki-36 (8.7 MB) — N4
  {
    id: "n4-narezki-short-story",
    level: "N4",
    titleRu: "Короткая история на японском",
    descriptionRu: "Небольшая история для аудирования на уровне N4.",
    video: { type: "remote", src: "https://archive.org/download/japanese-trainer-narezki/narezki-36.mp4" },
    subtitles: [
      { startSec: 0, endSec: 3.4, ja: "何時かな?", furigana: "何時かな?" },
      { startSec: 4.4, endSec: 6.8, ja: "時計の読み方を覚えよう", furigana: "時計の読み方を覚えよう" },
      { startSec: 6.8, endSec: 14.6, ja: "時計には短い針と長い針があるよ", furigana: "時計には短い針と長い針があるよ" },
      { startSec: 14.6, endSec: 21.2, ja: "短い針が何時、長い針が何分を指すよ", furigana: "短い針が何時、長い針が何分を指すよ" },
      { startSec: 23.2, endSec: 25.2, ja: "例えば、これは3時", furigana: "例えば、これは3時" },
      { startSec: 25.2, endSec: 29.2, ja: "これは6時", furigana: "これは6時" },
      { startSec: 29.2, endSec: 33.6, ja: "これはくじだよ", furigana: "これはくじだよ" },
      { startSec: 33.6, endSec: 39.9, ja: "長い針は小さい目盛り一つで1分だから", furigana: "長い針は小さい目盛り一つで1分だから" },
      { startSec: 39.9, endSec: 45, ja: "1 2 3 4 5分", furigana: "1 2 3 4 5分" },
      { startSec: 45, endSec: 49.9, ja: "10分 15分 20分", furigana: "10分 15分 20分" },
      { startSec: 49.9, endSec: 53, ja: "25分 30分", furigana: "25分 30分" },
      { startSec: 53, endSec: 56.1, ja: "35分 40分", furigana: "35分 40分" },
      { startSec: 56.1, endSec: 69.7, ja: "45分 50分55分と読むよそれから30分のことを3とも言うよ", furigana: "45分 50分55分と読むよそれから30分のことを3とも言うよ" },
      { startSec: 69.7, endSec: 74.3, ja: "それじゃあ問題いってみよう", furigana: "それじゃあ問題いってみよう" },
      { startSec: 74.3, endSec: 79.4, ja: "何時かな", furigana: "何時かな" },
      { startSec: 79.4, endSec: 83, ja: "2時", furigana: "2時" },
      { startSec: 88.8, endSec: 91.5, ja: "何時かな?", furigana: "何時かな?" },
      { startSec: 92.9, endSec: 95, ja: "5時", furigana: "5時" },
      { startSec: 95, endSec: 103.5, ja: "何時かな?", furigana: "何時かな?" },
      { startSec: 106.3, endSec: 107.8, ja: "7時", furigana: "7時" },
      { startSec: 107.8, endSec: 115.4, ja: "何時かな?", furigana: "何時かな?" },
      { startSec: 115.4, endSec: 117.4, ja: "何時かな?", furigana: "何時かな?" },
      { startSec: 117.4, endSec: 119.4, ja: "10時", furigana: "10時" },
      { startSec: 119.4, endSec: 139.4, ja: "何時かな?12時何時かな?", furigana: "何時かな?12時何時かな?" },
      { startSec: 142.5, endSec: 144.2, ja: "1時30分", furigana: "1時30分" },
      { startSec: 151.4, endSec: 152.4, ja: "何時かな?", furigana: "何時かな?" },
      { startSec: 152.6, endSec: 157.4, ja: "3時10分", furigana: "3時10分" },
      { startSec: 157.4, endSec: 163.5, ja: "何時かな", furigana: "何時かな" },
      { startSec: 163.5, endSec: 168.5, ja: "4時45分", furigana: "4時45分" },
      { startSec: 175.2, endSec: 176.4, ja: "何時かな", furigana: "何時かな" },
      { startSec: 176.4, endSec: 181.6, ja: "7時25分", furigana: "7時25分" },
      { startSec: 181.6, endSec: 202.2, ja: "ご視聴ありがとうございました何時かな?9時40分何時かな?", furigana: "ご視聴ありがとうございました何時かな?9時40分何時かな?" },
      { startSec: 204.8, endSec: 206.9, ja: "10時15分", furigana: "10時15分" },
      { startSec: 206.9, endSec: 215.2, ja: "何時かな?", furigana: "何時かな?" },
      { startSec: 216.4, endSec: 220.7, ja: "12時55分", furigana: "12時55分" },
      { startSec: 220.7, endSec: 227, ja: "時計の読み方わかったかな?", furigana: "時計の読み方わかったかな?" },
      { startSec: 228.8, endSec: 230.8, ja: "じゃあね、またね", furigana: "じゃあね、またね" },
      { startSec: 237.3, endSec: 240.6, ja: "最後まで見てくれてありがとう", furigana: "最後まで見てくれてありがとう" },
      { startSec: 240.6, endSec: 246.7, ja: "チャンネル登録といいねもお願いします", furigana: "チャンネル登録といいねもお願いします" },
    ],
    questions: [],
  },
  // narezki-37 (12.6 MB) — N4
  {
    id: "n4-narezki-daily-life",
    level: "N4",
    titleRu: "Повседневная жизнь: описание дня",
    descriptionRu: "Видео о повседневной жизни — практика понимания рассказов о ежедневных делах.",
    video: { type: "remote", src: "https://archive.org/download/japanese-trainer-narezki/narezki-37.mp4" },
    subtitles: [
      { startSec: 0, endSec: 2.8, ja: "おいフリー", furigana: "おいフリー" },
      { startSec: 2.8, endSec: 5.9, ja: "うまそうなものを見る目をしたな", furigana: "うまそうなものを見る目をしたな" },
      { startSec: 5.9, endSec: 17.4, ja: "この世は嘘にまみれている", furigana: "この世は嘘にまみれている" },
      { startSec: 17.4, endSec: 21.4, ja: "装飾が上辺ばかりの生き方をしていれば", furigana: "装飾が上辺ばかりの生き方をしていれば" },
      { startSec: 21.4, endSec: 23.4, ja: "必ず取って食われるんだ", furigana: "必ず取って食われるんだ" },
      { startSec: 23.4, endSec: 28, ja: "今度こそ本当の強さを手に入れる", furigana: "今度こそ本当の強さを手に入れる" },
      { startSec: 28, endSec: 29.6, ja: "自分と", furigana: "自分と" },
      { startSec: 30, endSec: 32.6, ja: "肉食獣の邪悪さを信じて", furigana: "肉食獣の邪悪さを信じて" },
      { startSec: 32.6, endSec: 37.5, ja: "おいフリー", furigana: "おいフリー" },
      { startSec: 37.5, endSec: 40.7, ja: "美味そうなものを見る目をしたな", furigana: "美味そうなものを見る目をしたな" },
      { startSec: 40.7, endSec: 54.2, ja: "いいな", furigana: "いいな" },
      { startSec: 54.2, endSec: 57.6, ja: "俺たちが交わした約束を忘れるな", furigana: "俺たちが交わした約束を忘れるな" },
      { startSec: 60, endSec: 62, ja: "ありがとうございました", furigana: "ありがとうございました" },
    ],
    questions: [],
  },
  // narezki-38 (24.1 MB) — N4
  {
    id: "n4-narezki-conversation",
    level: "N4",
    titleRu: "Разговорная практика",
    descriptionRu: "Разговорный японский: тренировка восприятия естественной речи на уровне N4.",
    video: { type: "remote", src: "https://archive.org/download/japanese-trainer-narezki/narezki-38.mp4" },
    subtitles: [
      { startSec: 0, endSec: 1, ja: "おお!", furigana: "おお!" },
      { startSec: 1, endSec: 2, ja: "させへん!", furigana: "させへん!" },
      { startSec: 2, endSec: 3, ja: "わ、待ってよ!", furigana: "わ、待ってよ!" },
      { startSec: 3, endSec: 5, ja: "はくん、沈む!", furigana: "はくん、沈む!" },
      { startSec: 5, endSec: 7, ja: "沈ませ屋さんのファットだいえ!", furigana: "沈ませ屋さんのファットだいえ!" },
      { startSec: 7, endSec: 8, ja: "うっ、バカ!", furigana: "うっ、バカ!" },
      { startSec: 8, endSec: 11, ja: "って、なや!エッジとコースでかぶっとるでお前!", furigana: "って、なや!エッジとコースでかぶっとるでお前!" },
      { startSec: 12, endSec: 14, ja: "なんじゃこのタコ!", furigana: "なんじゃこのタコ!" },
      { startSec: 15, endSec: 17, ja: "ひどい言い方を…", furigana: "ひどい言い方を…" },
      { startSec: 17, endSec: 20, ja: "違うよ先輩!見た目の話、悪口じゃないっせ!", furigana: "違うよ先輩!見た目の話、悪口じゃないっせ!" },
      { startSec: 27, endSec: 29, ja: "タコやマリンかい、我…", furigana: "タコやマリンかい、我…" },
      { startSec: 30, endSec: 31.8, ja: "アサリは便利なんだ", furigana: "アサリは便利なんだ" },
      { startSec: 31.8, endSec: 33.5, ja: "工房に炊ける", furigana: "工房に炊ける" },
      { startSec: 33.5, endSec: 36.8, ja: "だから毎日食べるようにしているんだ", furigana: "だから毎日食べるようにしているんだ" },
      { startSec: 36.8, endSec: 39.5, ja: "UA高校3年ビッグスリー", furigana: "UA高校3年ビッグスリー" },
      { startSec: 39.5, endSec: 40.5, ja: "天敷玉樹", furigana: "天敷玉樹" },
      { startSec: 40.5, endSec: 41.9, ja: "個性再現", furigana: "個性再現" },
      { startSec: 41.9, endSec: 45.6, ja: "食らったものの特徴をその体に再現できる", furigana: "食らったものの特徴をその体に再現できる" },
      { startSec: 45.6, endSec: 47.6, ja: "ちなみに右腕はたこ焼き", furigana: "ちなみに右腕はたこ焼き" },
      { startSec: 47.6, endSec: 49.5, ja: "左腕がアサリのしぐれに", furigana: "左腕がアサリのしぐれに" },
      { startSec: 49.5, endSec: 52.6, ja: "羽の足はフライドチキンを食べて再現してるぞ", furigana: "羽の足はフライドチキンを食べて再現してるぞ" },
      { startSec: 52.6, endSec: 54.6, ja: "羽はいらなかった", furigana: "羽はいらなかった" },
      { startSec: 54.6, endSec: 56.5, ja: "すげえ", furigana: "すげえ" },
      { startSec: 56.5, endSec: 58.3, ja: "てかまたいいとこね", furigana: "てかまたいいとこね" },
      { startSec: 58.3, endSec: 61.5, ja: "うまくできていただろうか", furigana: "うまくできていただろうか" },
      { startSec: 61.5, endSec: 62.2, ja: "すげーっす!", furigana: "すげーっす!" },
      { startSec: 62.5, endSec: 64.8, ja: "迅速で個性の使い方も慣れてて!", furigana: "迅速で個性の使い方も慣れてて!" },
      { startSec: 65.1, endSec: 67.2, ja: "技量ならとうにプロ以上やで", furigana: "技量ならとうにプロ以上やで" },
      { startSec: 67.2, endSec: 68.6, ja: "うちのサンイーターは", furigana: "うちのサンイーターは" },
      { startSec: 68.6, endSec: 70.4, ja: "メンタルは育たんけど", furigana: "メンタルは育たんけど" },
      { startSec: 70.4, endSec: 71.7, ja: "なあ!", furigana: "なあ!" },
      { startSec: 72.4, endSec: 73.5, ja: "エイドサンイーター!", furigana: "エイドサンイーター!" },
      { startSec: 73.9, endSec: 74.9, ja: "かっこいい!", furigana: "かっこいい!" },
    ],
    questions: [],
  },
  // narezki-39 (30.3 MB) — N3
  {
    id: "n3-narezki-interview",
    level: "N3",
    titleRu: "Интервью на японском",
    descriptionRu: "Тренировка понимания интервью — более длинные высказывания и сложная лексика.",
    video: { type: "remote", src: "https://archive.org/download/japanese-trainer-narezki/narezki-39.mp4" },
    subtitles: [
      { startSec: 0, endSec: 2, ja: "音楽", furigana: "音楽" },
      { startSec: 2, endSec: 14.5, ja: "はい、みどりシステムでございます。", furigana: "はい、みどりシステムでございます。" },
      { startSec: 15.4, endSec: 17.2, ja: "ABC障子の伊藤です。", furigana: "ABC障子の伊藤です。" },
      { startSec: 19.5, endSec: 22.8, ja: "みなさんこんにちは。ジャパスタのマナです。", furigana: "みなさんこんにちは。ジャパスタのマナです。" },
      { startSec: 23.6, endSec: 26.8, ja: "それでは、今日も楽しく日本語を勉強しましょう。", furigana: "それでは、今日も楽しく日本語を勉強しましょう。" },
      { startSec: 26.8, endSec: 34.2, ja: "今日は会社で電話に出る方法についてお話をしたいと思います", furigana: "今日は会社で電話に出る方法についてお話をしたいと思います" },
      { startSec: 34.2, endSec: 39.2, ja: "皆さん会社で電話が鳴っているけれど", furigana: "皆さん会社で電話が鳴っているけれど" },
      { startSec: 39.2, endSec: 42.5, ja: "どうやって出たらいいかわからないなぁ", furigana: "どうやって出たらいいかわからないなぁ" },
      { startSec: 42.5, endSec: 47.1, ja: "電話で話すのは緊張するなぁということはありませんか?", furigana: "電話で話すのは緊張するなぁということはありませんか?" },
      { startSec: 48.6, endSec: 52.9, ja: "今日はそんな皆さんの悩みを解決したいと思います", furigana: "今日はそんな皆さんの悩みを解決したいと思います" },
      { startSec: 52.9, endSec: 58.5, ja: "この動画を見ることで2つのことができるようになります", furigana: "この動画を見ることで2つのことができるようになります" },
      { startSec: 58.5, endSec: 64.4, ja: "まず1つ目が会社にかかってくる電話の種類がわかります", furigana: "まず1つ目が会社にかかってくる電話の種類がわかります" },
      { startSec: 64.4, endSec: 67.8, ja: "実は2種類の電話がありますよ", furigana: "実は2種類の電話がありますよ" },
      { startSec: 67.8, endSec: 75.8, ja: "そしてもう1つは会社で電話に出るときに何を言えばいいかわかるようになります", furigana: "そしてもう1つは会社で電話に出るときに何を言えばいいかわかるようになります" },
      { startSec: 77, endSec: 80.1, ja: "それでは今日も楽しく日本語を勉強しましょう", furigana: "それでは今日も楽しく日本語を勉強しましょう" },
      { startSec: 80.1, endSec: 86.2, ja: "ではまず会社にかかってくる電話の種類についてです", furigana: "ではまず会社にかかってくる電話の種類についてです" },
      { startSec: 86.2, endSec: 91, ja: "会社にかかってくる電話は2つの種類があります", furigana: "会社にかかってくる電話は2つの種類があります" },
      { startSec: 91, endSec: 93.9, ja: "皆さん何だと思いますか?", furigana: "皆さん何だと思いますか?" },
      { startSec: 95.5, endSec: 100.4, ja: "1つ目は会社の外の人からかかってくる電話です", furigana: "1つ目は会社の外の人からかかってくる電話です" },
      { startSec: 100.4, endSec: 103.1, ja: "会社の外の人なので", furigana: "会社の外の人なので" },
      { startSec: 103.1, endSec: 107, ja: "取引先やお客様などですね", furigana: "取引先やお客様などですね" },
      { startSec: 107, endSec: 113.5, ja: "そしてもう一つは会社の中の人からかかってくる電話です", furigana: "そしてもう一つは会社の中の人からかかってくる電話です" },
      { startSec: 113.5, endSec: 119.3, ja: "同じ会社の違う部署の人などからかかってくる電話のことです", furigana: "同じ会社の違う部署の人などからかかってくる電話のことです" },
      { startSec: 119.3, endSec: 125, ja: "この会社の外の人からかかってくる電話のことを", furigana: "この会社の外の人からかかってくる電話のことを" },
      { startSec: 125, endSec: 125.9, ja: "外線", furigana: "外線" },
      { startSec: 125.9, endSec: 132.4, ja: "会社の中の人からかかってくる電話のことを", furigana: "会社の中の人からかかってくる電話のことを" },
      { startSec: 132.4, endSec: 133.3, ja: "内線", furigana: "内線" },
      { startSec: 133.3, endSec: 136, ja: "と言います", furigana: "と言います" },
      { startSec: 136, endSec: 141.2, ja: "実は会社の外の人からかかってきた時と", furigana: "実は会社の外の人からかかってきた時と" },
      { startSec: 141.2, endSec: 145, ja: "会社の中の人からかかってきた時で", furigana: "会社の中の人からかかってきた時で" },
      { startSec: 145, endSec: 155.1, ja: "話す内容が少しだけ違いますなので今日はこの2つの種類の電話がかかってきた時に、", furigana: "話す内容が少しだけ違いますなので今日はこの2つの種類の電話がかかってきた時に、" },
      { startSec: 155.3, endSec: 159.2, ja: "それぞれどんなことを言えばいいかお話ししたいと思います。", furigana: "それぞれどんなことを言えばいいかお話ししたいと思います。" },
      { startSec: 160.9, endSec: 166, ja: "では実際に話をする内容の前に、", furigana: "では実際に話をする内容の前に、" },
      { startSec: 166.1, endSec: 170.7, ja: "まず電話の流れについてお話をしたいと思います。", furigana: "まず電話の流れについてお話をしたいと思います。" },
      { startSec: 170.7, endSec: 176.7, ja: "電話の流れは大きく分けると3つのステップがあります", furigana: "電話の流れは大きく分けると3つのステップがあります" },
      { startSec: 176.7, endSec: 181.2, ja: "これは会社の外の人からかかってきた時も", furigana: "これは会社の外の人からかかってきた時も" },
      { startSec: 181.2, endSec: 185, ja: "会社の中の人からかかってきた時も同じです", furigana: "会社の中の人からかかってきた時も同じです" },
      { startSec: 185, endSec: 187.7, ja: "では3つのステップです", furigana: "では3つのステップです" },
      { startSec: 187.7, endSec: 190.6, ja: "1つ目が自分について", furigana: "1つ目が自分について" },
      { startSec: 190.6, endSec: 193.4, ja: "2つ目が挨拶", furigana: "2つ目が挨拶" },
      { startSec: 194.4, endSec: 197.7, ja: "そして3つ目が要件の確認です", furigana: "そして3つ目が要件の確認です" },
      { startSec: 197.7, endSec: 204.9, ja: "要件の確認というのは相手がなぜ電話をしてきたのかを確認することです", furigana: "要件の確認というのは相手がなぜ電話をしてきたのかを確認することです" },
      { startSec: 204.9, endSec: 206.8, ja: "皆さんいいですか?", furigana: "皆さんいいですか?" },
      { startSec: 207.4, endSec: 211.4, ja: "自分について、挨拶、要件の確認", furigana: "自分について、挨拶、要件の確認" },
      { startSec: 211.4, endSec: 217.3, ja: "この3つのステップはとても大事ですからここは覚えておいてください", furigana: "この3つのステップはとても大事ですからここは覚えておいてください" },
      { startSec: 217.3, endSec: 222.2, ja: "それではまず1つ目の自分についてからです", furigana: "それではまず1つ目の自分についてからです" },
      { startSec: 222.2, endSec: 228.6, ja: "では自分について話すときに何と言えばいいか見てみましょう", furigana: "では自分について話すときに何と言えばいいか見てみましょう" },
      { startSec: 228.6, endSec: 233.8, ja: "これは会社の外の人からかかってくるときと", furigana: "これは会社の外の人からかかってくるときと" },
      { startSec: 233.8, endSec: 239.3, ja: "会社の中の人からかかってくるときで話すことが違います", furigana: "会社の中の人からかかってくるときで話すことが違います" },
      { startSec: 239.3, endSec: 243.6, ja: "まず会社の外の人からかかってきたときです", furigana: "まず会社の外の人からかかってきたときです" },
      { startSec: 244.7, endSec: 247.5, ja: "このときまず言うことは", furigana: "このときまず言うことは" },
      { startSec: 247.5, endSec: 253.7, ja: "はいプラス自分の会社の名前プラスでございます", furigana: "はいプラス自分の会社の名前プラスでございます" },
      { startSec: 253.7, endSec: 261.4, ja: "なので例えば私がジャパスタ会社というところで働いているとすると", furigana: "なので例えば私がジャパスタ会社というところで働いているとすると" },
      { startSec: 261.4, endSec: 265, ja: "電話が鳴ったら電話を取って", furigana: "電話が鳴ったら電話を取って" },
      { startSec: 265, endSec: 267.7, ja: "はいジャパスタ会社でございます", furigana: "はいジャパスタ会社でございます" },
      { startSec: 267.7, endSec: 271, ja: "はいジャパスタ会社でございます", furigana: "はいジャパスタ会社でございます" },
      { startSec: 271.8, endSec: 274.2, ja: "こういうのが一番自然です", furigana: "こういうのが一番自然です" },
      { startSec: 274.2, endSec: 279.5, ja: "では次に会社の中の人からかかってきた時です", furigana: "では次に会社の中の人からかかってきた時です" },
      { startSec: 279.5, endSec: 283.1, ja: "この時は2つ言い方があります", furigana: "この時は2つ言い方があります" },
      { startSec: 283.1, endSec: 292.2, ja: "1つ目ははいプラス自分の担当名担当の名前プラスです", furigana: "1つ目ははいプラス自分の担当名担当の名前プラスです" },
      { startSec: 294, endSec: 305.1, ja: "例えば私がシステム開発担当というところで働いているとすると最初に電話を取ってはい、システム開発担当というところで働いているとすると最初に電話を取ってはいシステム開発担当です", furigana: "例えば私がシステム開発担当というところで働いているとすると最初に電話を取ってはい、システム開発担当というところで働いているとすると最初に電話を取ってはいシステム開発担当です" },
      { startSec: 305.1, endSec: 308.7, ja: "はいシステム開発担当です", furigana: "はいシステム開発担当です" },
      { startSec: 308.7, endSec: 313, ja: "こういうふうに担当の名前を言うという言い方があります", furigana: "こういうふうに担当の名前を言うという言い方があります" },
      { startSec: 313, endSec: 316.6, ja: "そしてもう一つの言い方は", furigana: "そしてもう一つの言い方は" },
      { startSec: 316.6, endSec: 323.1, ja: "はいプラス自分の担当名プラス名前プラスです", furigana: "はいプラス自分の担当名プラス名前プラスです" },
      { startSec: 323.1, endSec: 325.9, ja: "ではこれも見てみましょう", furigana: "ではこれも見てみましょう" },
      { startSec: 325.9, endSec: 332.8, ja: "例えば私がシステム開発担当で働くキムさんだったとすると", furigana: "例えば私がシステム開発担当で働くキムさんだったとすると" },
      { startSec: 332.8, endSec: 334.5, ja: "電話を取って", furigana: "電話を取って" },
      { startSec: 334.5, endSec: 337.5, ja: "はいシステム開発担当のキムです", furigana: "はいシステム開発担当のキムです" },
      { startSec: 337.5, endSec: 341.1, ja: "はいシステム開発担当のキムです", furigana: "はいシステム開発担当のキムです" },
      { startSec: 341.1, endSec: 342.9, ja: "みたいな感じですね", furigana: "みたいな感じですね" },
      { startSec: 344.9, endSec: 349.1, ja: "皆さん一つ目の自分についての言い方は分かりましたか", furigana: "皆さん一つ目の自分についての言い方は分かりましたか" },
      { startSec: 349.1, endSec: 352.8, ja: "それでは2つ目の挨拶", furigana: "それでは2つ目の挨拶" },
      { startSec: 352.8, endSec: 358.1, ja: "と3つ目の要件の確認をまとめて見てみましょう", furigana: "と3つ目の要件の確認をまとめて見てみましょう" },
      { startSec: 358.1, endSec: 362.4, ja: "ではまず2つ目の挨拶からです", furigana: "ではまず2つ目の挨拶からです" },
      { startSec: 362.4, endSec: 365.1, ja: "挨拶は簡単です", furigana: "挨拶は簡単です" },
      { startSec: 365.1, endSec: 369.6, ja: "会社の外の人からかかってくる電話の時は", furigana: "会社の外の人からかかってくる電話の時は" },
      { startSec: 369.6, endSec: 372.1, ja: "いつもお世話になっております", furigana: "いつもお世話になっております" },
      { startSec: 372.1, endSec: 374.7, ja: "いつもお世話になっております", furigana: "いつもお世話になっております" },
      { startSec: 374.7, endSec: 376.3, ja: "これです", furigana: "これです" },
      { startSec: 377.5, endSec: 381.1, ja: "では会社の中の人からかかってくる電話です", furigana: "では会社の中の人からかかってくる電話です" },
      { startSec: 381.1, endSec: 384.6, ja: "これはお疲れ様です", furigana: "これはお疲れ様です" },
      { startSec: 384.6, endSec: 386.7, ja: "お疲れ様です", furigana: "お疲れ様です" },
      { startSec: 386.7, endSec: 389.7, ja: "挨拶はこれだけです", furigana: "挨拶はこれだけです" },
      { startSec: 389.7, endSec: 391.8, ja: "皆さん簡単でしたね", furigana: "皆さん簡単でしたね" },
      { startSec: 391.8, endSec: 394.5, ja: "それでは次に進みましょう", furigana: "それでは次に進みましょう" },
      { startSec: 394.5, endSec: 400.1, ja: "それでは最後の要件の確認についてです", furigana: "それでは最後の要件の確認についてです" },
      { startSec: 400.1, endSec: 402.9, ja: "ここで大事なことは", furigana: "ここで大事なことは" },
      { startSec: 403.2, endSec: 408.2, ja: "まずは相手が要件を話すのを待つということです", furigana: "まずは相手が要件を話すのを待つということです" },
      { startSec: 408.2, endSec: 411.9, ja: "挨拶をした後にすぐ", furigana: "挨拶をした後にすぐ" },
      { startSec: 411.9, endSec: 416.1, ja: "要件は何ですか?なぜ電話しましたか?", furigana: "要件は何ですか?なぜ電話しましたか?" },
      { startSec: 416.9, endSec: 419.8, ja: "というように聞くと少し失礼です", furigana: "というように聞くと少し失礼です" },
      { startSec: 419.8, endSec: 425.5, ja: "なのでまずは相手が話すのを少し待ってみましょう", furigana: "なのでまずは相手が話すのを少し待ってみましょう" },
      { startSec: 425.5, endSec: 429.7, ja: "だいたい電話でお互いに挨拶", furigana: "だいたい電話でお互いに挨拶" },
      { startSec: 429.7, endSec: 431.1, ja: "お疲れ様です", furigana: "お疲れ様です" },
      { startSec: 431.1, endSec: 433.2, ja: "いつもお世話になっております", furigana: "いつもお世話になっております" },
      { startSec: 433.2, endSec: 436.3, ja: "といった挨拶が終わって少し待つと", furigana: "といった挨拶が終わって少し待つと" },
      { startSec: 436.3, endSec: 438.6, ja: "電話をしてきた相手から", furigana: "電話をしてきた相手から" },
      { startSec: 438.6, endSec: 442.1, ja: "木村さんはいらっしゃいますか?のように", furigana: "木村さんはいらっしゃいますか?のように" },
      { startSec: 442.1, endSec: 443.9, ja: "要件を言ってくれます", furigana: "要件を言ってくれます" },
      { startSec: 443.9, endSec: 459.8, ja: "なので皆さん要件は何ですか?と聞かずに少し待つというのを覚えておいてください。ではここまで電話の流れについて3つのステップでお話をしてきました。", furigana: "なので皆さん要件は何ですか?と聞かずに少し待つというのを覚えておいてください。ではここまで電話の流れについて3つのステップでお話をしてきました。" },
      { startSec: 461.1, endSec: 465.7, ja: "では今までお話をしたこの3つの流れを使うと", furigana: "では今までお話をしたこの3つの流れを使うと" },
      { startSec: 465.7, endSec: 467.8, ja: "どんな会話になるのか", furigana: "どんな会話になるのか" },
      { startSec: 467.8, endSec: 472.8, ja: "実際に日本の会社ではどんな電話のやり取りがされるのか", furigana: "実際に日本の会社ではどんな電話のやり取りがされるのか" },
      { startSec: 472.8, endSec: 475.2, ja: "というのを見てみたいと思います", furigana: "というのを見てみたいと思います" },
      { startSec: 475.2, endSec: 480.1, ja: "今日は会社の外の人からかかってくる電話と", furigana: "今日は会社の外の人からかかってくる電話と" },
      { startSec: 480.1, endSec: 483.5, ja: "会社の中の人からかかってくる電話の", furigana: "会社の中の人からかかってくる電話の" },
      { startSec: 483.5, endSec: 486.7, ja: "2つの場面でお話をしたいと思います", furigana: "2つの場面でお話をしたいと思います" },
      { startSec: 486.7, endSec: 492.6, ja: "ではまず会社の外の人からかかってくる電話です", furigana: "ではまず会社の外の人からかかってくる電話です" },
      { startSec: 492.6, endSec: 497, ja: "みどりシステムで働くキムさんと", furigana: "みどりシステムで働くキムさんと" },
      { startSec: 497.2, endSec: 501.5, ja: "取引先のABC障子の伊藤さんです", furigana: "取引先のABC障子の伊藤さんです" },
      { startSec: 501.5, endSec: 506.7, ja: "キムさんが仕事をしていると電話がかかってきました", furigana: "キムさんが仕事をしていると電話がかかってきました" },
      { startSec: 506.7, endSec: 511, ja: "では皆さんもキムさんになったつもりで", furigana: "では皆さんもキムさんになったつもりで" },
      { startSec: 511, endSec: 513.9, ja: "声に出して一緒に練習してみてくださいね", furigana: "声に出して一緒に練習してみてくださいね" },
      { startSec: 521.2, endSec: 523.3, ja: "はい、みどりシステムでございます", furigana: "はい、みどりシステムでございます" },
      { startSec: 523.3, endSec: 526.3, ja: "ABC障子の伊藤です", furigana: "ABC障子の伊藤です" },
      { startSec: 526.3, endSec: 528.7, ja: "いつもお世話になっております", furigana: "いつもお世話になっております" },
      { startSec: 528.7, endSec: 531, ja: "お世話になっております", furigana: "お世話になっております" },
      { startSec: 531, endSec: 534.4, ja: "木村さんはいらっしゃいますか?", furigana: "木村さんはいらっしゃいますか?" },
      { startSec: 535.6, endSec: 537, ja: "はい、少々お待ちください", furigana: "はい、少々お待ちください" },
      { startSec: 537, endSec: 544, ja: "皆さんどうですか?うまく言えましたか?", furigana: "皆さんどうですか?うまく言えましたか?" },
      { startSec: 545.4, endSec: 549.8, ja: "では次は会社の中の人からかかってくる電話です", furigana: "では次は会社の中の人からかかってくる電話です" },
      { startSec: 549.8, endSec: 556, ja: "緑システムの開発担当で働くキムさんと", furigana: "緑システムの開発担当で働くキムさんと" },
      { startSec: 556, endSec: 563, ja: "同じく緑システムの営業担当で働く佐藤さんです", furigana: "同じく緑システムの営業担当で働く佐藤さんです" },
      { startSec: 563, endSec: 567.8, ja: "キムさんが仕事をしていると電話がかかってきました", furigana: "キムさんが仕事をしていると電話がかかってきました" },
      { startSec: 569.1, endSec: 574.5, ja: "皆さんもキムさんになったつもりで声に出して練習してみてくださいね", furigana: "皆さんもキムさんになったつもりで声に出して練習してみてくださいね" },
      { startSec: 579.8, endSec: 583.5, ja: "はい、開発担当のキムです", furigana: "はい、開発担当のキムです" },
      { startSec: 583.5, endSec: 586.2, ja: "営業担当の佐藤です", furigana: "営業担当の佐藤です" },
      { startSec: 586.2, endSec: 587.6, ja: "お疲れ様です", furigana: "お疲れ様です" },
      { startSec: 587.6, endSec: 589.3, ja: "お疲れ様です", furigana: "お疲れ様です" },
      { startSec: 589.3, endSec: 592.9, ja: "明日の打ち合わせ資料を送ってほしいんだけど", furigana: "明日の打ち合わせ資料を送ってほしいんだけど" },
      { startSec: 592.9, endSec: 596.5, ja: "はい、この後すぐ送りますね", furigana: "はい、この後すぐ送りますね" },
      { startSec: 600, endSec: 604.4, ja: "皆さんどうですか?うまく言えましたか?", furigana: "皆さんどうですか?うまく言えましたか?" },
      { startSec: 605.9, endSec: 609.1, ja: "今日の動画で何回か練習をして", furigana: "今日の動画で何回か練習をして" },
      { startSec: 609.1, endSec: 612.8, ja: "会社の外の人からかかってくる電話と", furigana: "会社の外の人からかかってくる電話と" },
      { startSec: 612.8, endSec: 616.1, ja: "会社の中の人からかかってくる電話に", furigana: "会社の中の人からかかってくる電話に" },
      { startSec: 616.1, endSec: 620.2, ja: "ぜひ自信を持って対応できるようになってくださいね", furigana: "ぜひ自信を持って対応できるようになってくださいね" },
      { startSec: 620.2, endSec: 625, ja: "最後まで動画を見ていただきありがとうございました", furigana: "最後まで動画を見ていただきありがとうございました" },
      { startSec: 625, endSec: 629.3, ja: "役に立ったらぜひいいねをお願いします", furigana: "役に立ったらぜひいいねをお願いします" },
      { startSec: 629.3, endSec: 632.8, ja: "ぜひコメントも書いてくださいね", furigana: "ぜひコメントも書いてくださいね" },
      { startSec: 632.8, endSec: 638.6, ja: "これからも皆さんの日本語の勉強に役に立つ動画を作っていくので", furigana: "これからも皆さんの日本語の勉強に役に立つ動画を作っていくので" },
      { startSec: 638.6, endSec: 641.8, ja: "ぜひチャンネル登録もよろしくお願いします", furigana: "ぜひチャンネル登録もよろしくお願いします" },
      { startSec: 641.8, endSec: 645.8, ja: "それではまた次の動画でお会いしましょう", furigana: "それではまた次の動画でお会いしましょう" },
      { startSec: 645.8, endSec: 647.1, ja: "バイバイ", furigana: "バイバイ" },
    ],
    questions: [],
  },
  // narezki-40 (34.7 MB) — N3
  {
    id: "n3-narezki-discussion",
    level: "N3",
    titleRu: "Обсуждение на японском",
    descriptionRu: "Дискуссия на японском языке — тренировка понимания разговорной речи среднего уровня.",
    video: { type: "remote", src: "https://archive.org/download/japanese-trainer-narezki/narezki-40.mp4" },
    subtitles: [
      { startSec: 0, endSec: 15.8, ja: "第1話 イクウカン", furigana: "第1話 イクウカン" },
      { startSec: 15.8, endSec: 15.9, ja: "イクウカン", furigana: "イクウカン" },
      { startSec: 15.9, endSec: 18.6, ja: "ここに呼ばれたということは", furigana: "ここに呼ばれたということは" },
      { startSec: 18.6, endSec: 22, ja: "上限が鬼狩りにやられた", furigana: "上限が鬼狩りにやられた" },
      { startSec: 22, endSec: 28.7, ja: "これはこれは赤だぞ", furigana: "これはこれは赤だぞ" },
      { startSec: 28.7, endSec: 30.8, ja: "いいや早お元気そう", furigana: "いいや早お元気そう" },
      { startSec: 30.8, endSec: 33.4, ja: "恐ろしい", furigana: "恐ろしい" },
      { startSec: 33.4, endSec: 35.1, ja: "13年ぶり", furigana: "13年ぶり" },
      { startSec: 35.1, endSec: 37.6, ja: "ムザン様はいらっしゃらないのか", furigana: "ムザン様はいらっしゃらないのか" },
      { startSec: 37.6, endSec: 38.1, ja: "いません", furigana: "いません" },
      { startSec: 38.1, endSec: 40.1, ja: "どこだ", furigana: "どこだ" },
      { startSec: 40.1, endSec: 41.7, ja: "赤座殿", furigana: "赤座殿" },
      { startSec: 41.7, endSec: 43.4, ja: "ないのかい", furigana: "ないのかい" },
      { startSec: 43.4, endSec: 45.3, ja: "大切な仲", furigana: "大切な仲" },
      { startSec: 45.3, endSec: 47.9, ja: "やあやあ", furigana: "やあやあ" },
      { startSec: 47.9, endSec: 48.7, ja: "どかせ", furigana: "どかせ" },
      { startSec: 48.7, endSec: 49.6, ja: "ん?", furigana: "ん?" },
      { startSec: 50, endSec: 51, ja: "どかせ", furigana: "どかせ" },
      { startSec: 51, endSec: 54.7, ja: "いい拳だ", furigana: "いい拳だ" },
      { startSec: 54.7, endSec: 59.3, ja: "ずっとそこにいらっしゃいますよ", furigana: "ずっとそこにいらっしゃいますよ" },
      { startSec: 59.3, endSec: 60.1, ja: "ここにいる", furigana: "ここにいる" },
      { startSec: 60.1, endSec: 62.7, ja: "様がお見え", furigana: "様がお見え" },
      { startSec: 62.7, endSec: 66.8, ja: "かけた", furigana: "かけた" },
      { startSec: 66.8, endSec: 68.9, ja: "すいませんぬ", furigana: "すいませんぬ" },
      { startSec: 68.9, endSec: 70.7, ja: "送り出しましょうか", furigana: "送り出しましょうか" },
      { startSec: 70.7, endSec: 73.9, ja: "貴様の目玉なしでまといだった", furigana: "貴様の目玉なしでまといだった" },
      { startSec: 73.9, endSec: 76.5, ja: "だから牛太郎が戦っていればか", furigana: "だから牛太郎が戦っていればか" },
      { startSec: 76.5, endSec: 78.8, ja: "もうどうでもいい", furigana: "もうどうでもいい" },
      { startSec: 78.8, endSec: 79.6, ja: "ならぬ", furigana: "ならぬ" },
      { startSec: 79.6, endSec: 81.4, ja: "いい", furigana: "いい" },
      { startSec: 81.4, endSec: 88.1, ja: "俺があなた様の期待に応えなかった時があったでしょうか", furigana: "俺があなた様の期待に応えなかった時があったでしょうか" },
      { startSec: 88.1, endSec: 89.5, ja: "っていない", furigana: "っていない" },
      { startSec: 89.5, endSec: 101.9, ja: "どうした理由がわからなくなってきて気に入らない悪意だからな私はつかむ", furigana: "どうした理由がわからなくなってきて気に入らない悪意だからな私はつかむ" },
      { startSec: 101.9, endSec: 103.7, ja: "変化だ", furigana: "変化だ" },
      { startSec: 103.7, endSec: 106.6, ja: "今日の変化の場合劣化だ", furigana: "今日の変化の場合劣化だ" },
      { startSec: 106.6, endSec: 109.3, ja: "私が好きなものは不変こと", furigana: "私が好きなものは不変こと" },
      { startSec: 109.3, endSec: 112.2, ja: "頭に", furigana: "頭に" },
      { startSec: 112.2, endSec: 115.1, ja: "13年ぶりに上限を", furigana: "13年ぶりに上限を" },
      { startSec: 115.1, endSec: 117.4, ja: "まだ確定していない情報", furigana: "まだ確定していない情報" },
      { startSec: 117.4, endSec: 121.2, ja: "とともにそこへ向かえ", furigana: "とともにそこへ向かえ" },
      { startSec: 121.2, endSec: 123, ja: "この法とは何のことだ", furigana: "この法とは何のことだ" },
      { startSec: 123, endSec: 127.1, ja: "この通りと言っている", furigana: "この通りと言っている" },
      { startSec: 127.1, endSec: 129.6, ja: "赤さ", furigana: "赤さ" },
      { startSec: 129.6, endSec: 130.2, ja: "次", furigana: "次" },
      { startSec: 130.2, endSec: 133.5, ja: "しない", furigana: "しない" },
      { startSec: 133.5, endSec: 135, ja: "乱れ", furigana: "乱れ" },
      { startSec: 135, endSec: 137.4, ja: "憂いているのだ", furigana: "憂いているのだ" },
      { startSec: 137.4, endSec: 138.1, ja: "なるほどね", furigana: "なるほどね" },
      { startSec: 138.1, endSec: 142.5, ja: "この決戦を申し込む子は我らに勝てないが", furigana: "この決戦を申し込む子は我らに勝てないが" },
      { startSec: 142.5, endSec: 143.7, ja: "したのだから", furigana: "したのだから" },
      { startSec: 143.7, endSec: 145.7, ja: "彼も内心やってくれ", furigana: "彼も内心やってくれ" },
      { startSec: 145.7, endSec: 148.8, ja: "こういう風にして仲良くなって", furigana: "こういう風にして仲良くなって" },
      { startSec: 148.8, endSec: 149.4, ja: "赤座", furigana: "赤座" },
      { startSec: 149.4, endSec: 152.7, ja: "私の", furigana: "私の" },
      { startSec: 152.7, endSec: 155.8, ja: "分かった", furigana: "分かった" },
      { startSec: 155.8, endSec: 156.7, ja: "必ず", furigana: "必ず" },
      { startSec: 156.7, endSec: 160.5, ja: "そうか", furigana: "そうか" },
      { startSec: 160.5, endSec: 162.3, ja: "ことだ", furigana: "ことだ" },
      { startSec: 162.3, endSec: 164.3, ja: "さよなら", furigana: "さよなら" },
      { startSec: 164.3, endSec: 165.4, ja: "黒死亡殿", furigana: "黒死亡殿" },
      { startSec: 165.4, endSec: 169.1, ja: "赤座殿", furigana: "赤座殿" },
      { startSec: 169.1, endSec: 172.1, ja: "私とハンテング同じ場", furigana: "私とハンテング同じ場" },
      { startSec: 172.1, endSec: 176.9, ja: "勝ったらこの後俺と", furigana: "勝ったらこの後俺と" },
      { startSec: 176.9, endSec: 179.7, ja: "誰も彼も連れないな", furigana: "誰も彼も連れないな" },
      { startSec: 179.7, endSec: 181.1, ja: "信者の方がお見え", furigana: "信者の方がお見え" },
      { startSec: 181.1, endSec: 182.1, ja: "言ってもらっておくれ", furigana: "言ってもらっておくれ" },
    ],
    questions: [],
  },
  // narezki-41 (82.6 MB) — N3
  {
    id: "n3-narezki-long-story",
    level: "N3",
    titleRu: "Длинная история на японском",
    descriptionRu: "Продолжительная история для углубленного аудирования на уровне N3.",
    video: { type: "remote", src: "https://archive.org/download/japanese-trainer-narezki/narezki-41.mp4" },
    subtitles: [
      { startSec: 0, endSec: 4.3, ja: "音楽", furigana: "音楽" },
      { startSec: 4.3, endSec: 11, ja: "音楽", furigana: "音楽" },
      { startSec: 11, endSec: 15.2, ja: "音楽", furigana: "音楽" },
      { startSec: 15.2, endSec: 29.2, ja: "音楽", furigana: "音楽" },
      { startSec: 29.2, endSec: 30.4, ja: "何名様ですか?", furigana: "何名様ですか?" },
      { startSec: 31.5, endSec: 32.3, ja: "2人です", furigana: "2人です" },
      { startSec: 32.3, endSec: 34.2, ja: "こちらどうぞ", furigana: "こちらどうぞ" },
      { startSec: 34.9, endSec: 50.9, ja: "これはチキンですか?", furigana: "これはチキンですか?" },
      { startSec: 51.5, endSec: 53, ja: "いえ、チキンじゃありません", furigana: "いえ、チキンじゃありません" },
      { startSec: 53, endSec: 54.4, ja: "豚肉です", furigana: "豚肉です" },
      { startSec: 54.4, endSec: 56.2, ja: "豚肉、ポーク?", furigana: "豚肉、ポーク?" },
      { startSec: 56.7, endSec: 57.8, ja: "はい、ポークです", furigana: "はい、ポークです" },
      { startSec: 57.8, endSec: 59.8, ja: "じゃあこれは?", furigana: "じゃあこれは?" },
      { startSec: 59.8, endSec: 62.8, ja: "それは鶏肉です。チキンです。", furigana: "それは鶏肉です。チキンです。" },
      { startSec: 62.8, endSec: 64.8, ja: "これをください。", furigana: "これをください。" },
      { startSec: 64.8, endSec: 66.8, ja: "はい。", furigana: "はい。" },
      { startSec: 66.8, endSec: 68.8, ja: "クエさん、ビールは?", furigana: "クエさん、ビールは?" },
      { startSec: 68.8, endSec: 70.8, ja: "ビール?", furigana: "ビール?" },
      { startSec: 70.8, endSec: 82.3, ja: "OK。これは寿司ですか?はい、寿司です。じゃあこれは?天ぷらです。美味し司ですか?はい、寿司ですじゃあこれは?天ぷらです美味しいですか?美味しいです", furigana: "OK。これは寿司ですか?はい、寿司です。じゃあこれは?天ぷらです。美味し司ですか?はい、寿司ですじゃあこれは?天ぷらです美味しいですか?美味しいです" },
      { startSec: 82.3, endSec: 85.5, ja: "これとこれをください", furigana: "これとこれをください" },
      { startSec: 85.5, endSec: 89.3, ja: "はい、そばセットがお一つ、寿司セットがお一つですね", furigana: "はい、そばセットがお一つ、寿司セットがお一つですね" },
      { startSec: 89.3, endSec: 92.5, ja: "はい、それからビールを二つお願いします", furigana: "はい、それからビールを二つお願いします" },
      { startSec: 92.5, endSec: 94.8, ja: "はい、ビールがお二つですね", furigana: "はい、ビールがお二つですね" },
      { startSec: 94.8, endSec: 96.5, ja: "はい、少々お待ちくださいませ", furigana: "はい、少々お待ちくださいませ" },
      { startSec: 96.5, endSec: 96.8, ja: "はい", furigana: "はい" },
      { startSec: 96.8, endSec: 101.5, ja: "おー", furigana: "おー" },
      { startSec: 101.5, endSec: 103.8, ja: "乾杯", furigana: "乾杯" },
      { startSec: 103.8, endSec: 104.4, ja: "え?", furigana: "え?" },
      { startSec: 105.3, endSec: 105.9, ja: "乾杯", furigana: "乾杯" },
      { startSec: 105.9, endSec: 106.6, ja: "あ", furigana: "あ" },
      { startSec: 106.6, endSec: 108.5, ja: "乾杯", furigana: "乾杯" },
      { startSec: 108.5, endSec: 117.4, ja: "いただきます", furigana: "いただきます" },
      { startSec: 117.4, endSec: 118.6, ja: "いただきます", furigana: "いただきます" },
      { startSec: 126.8, endSec: 134.2, ja: "あ、グウェンさん", furigana: "あ、グウェンさん" },
      { startSec: 134.2, endSec: 137.1, ja: "あ", furigana: "あ" },
      { startSec: 137.1, endSec: 153.2, ja: "おいしいですか?おいしいですはるかさん、そばは?美味しいです。", furigana: "おいしいですか?おいしいですはるかさん、そばは?美味しいです。" },
      { startSec: 160.3, endSec: 161.5, ja: "これをください。", furigana: "これをください。" },
      { startSec: 168.1, endSec: 169.2, ja: "美味しいです。", furigana: "美味しいです。" },
      { startSec: 169.2, endSec: 169.2, ja: "美味しいです。", furigana: "美味しいです。" },
      { startSec: 175.8, endSec: 177, ja: "何名様ですか?", furigana: "何名様ですか?" },
      { startSec: 177.4, endSec: 178.7, ja: "一人です", furigana: "一人です" },
      { startSec: 178.7, endSec: 184.4, ja: "何名様ですか", furigana: "何名様ですか" },
      { startSec: 184.4, endSec: 191.2, ja: "これをください", furigana: "これをください" },
      { startSec: 191.2, endSec: 192.2, ja: "はい", furigana: "はい" },
      { startSec: 192.2, endSec: 197.8, ja: "はい", furigana: "はい" },
      { startSec: 197.8, endSec: 202.4, ja: "美味しいですか", furigana: "美味しいですか" },
      { startSec: 202.4, endSec: 203.7, ja: "美味しいです", furigana: "美味しいです" },
      { startSec: 203.7, endSec: 207.5, ja: "おいしいですか", furigana: "おいしいですか" },
      { startSec: 207.5, endSec: 214.5, ja: "音楽", furigana: "音楽" },
      { startSec: 214.5, endSec: 243.8, ja: "1人 2人 3人 4人 5人1つ 2つ 3つ 4つ 5つ", furigana: "1人 2人 3人 4人 5人1つ 2つ 3つ 4つ 5つ" },
      { startSec: 243.8, endSec: 259, ja: "牛肉 豚肉 鶏肉 魚", furigana: "牛肉 豚肉 鶏肉 魚" },
      { startSec: 273.8, endSec: 303.7, ja: "ご視聴ありがとうございました", furigana: "ご視聴ありがとうございました" },
      { startSec: 303.8, endSec: 333.7, ja: "ご視聴ありがとうございました", furigana: "ご視聴ありがとうございました" },
    ],
    questions: [],
  },
  // narezki-42 (87.7 MB) — N2
  {
    id: "n2-narezki-advanced-talk",
    level: "N2",
    titleRu: "Продвинутая беседа",
    descriptionRu: "Беседа на продвинутом уровне — сложная лексика и грамматические конструкции N2.",
    video: { type: "remote", src: "https://archive.org/download/japanese-trainer-narezki/narezki-42.mp4" },
    subtitles: [
      { startSec: 0, endSec: 16, ja: "作詞・作曲・編曲 初音ミク", furigana: "作詞・作曲・編曲 初音ミク" },
      { startSec: 16, endSec: 23.3, ja: "枯れてゆく 今この瞬間も", furigana: "枯れてゆく 今この瞬間も" },
      { startSec: 23.3, endSec: 25.3, ja: "咲いている", furigana: "咲いている" },
      { startSec: 25.3, endSec: 31, ja: "全ては溶けてゆく", furigana: "全ては溶けてゆく" },
      { startSec: 31, endSec: 35.2, ja: "何ができるのだろうか", furigana: "何ができるのだろうか" },
      { startSec: 35.2, endSec: 38.4, ja: "誰を生きようかな", furigana: "誰を生きようかな" },
      { startSec: 38.4, endSec: 42.8, ja: "みんな儚い", furigana: "みんな儚い" },
      { startSec: 42.8, endSec: 47.7, ja: "みんな尊い", furigana: "みんな尊い" },
      { startSec: 47.7, endSec: 51.9, ja: "シワシワにしおれた花束", furigana: "シワシワにしおれた花束" },
      { startSec: 51.9, endSec: 55.8, ja: "小脇に輝いて", furigana: "小脇に輝いて" },
      { startSec: 55.8, endSec: 79.4, ja: "永遠に変わらぬ輝き探してた僕らを信じてみた僕らを感じてた 僕らを信じてみた 僕らを感じてた咲かせに行くよ 内なる花を", furigana: "永遠に変わらぬ輝き探してた僕らを信じてみた僕らを感じてた 僕らを信じてみた 僕らを感じてた咲かせに行くよ 内なる花を" },
      { startSec: 90.5, endSec: 101.4, ja: "さりげなく思いを込めてみる", furigana: "さりげなく思いを込めてみる" },
      { startSec: 101.4, endSec: 109.1, ja: "やむを得ず祈りを込めてゆく", furigana: "やむを得ず祈りを込めてゆく" },
      { startSec: 109.1, endSec: 113.3, ja: "いつまで迷うんだろうか", furigana: "いつまで迷うんだろうか" },
      { startSec: 113.3, endSec: 116.8, ja: "いつかはわかるよな", furigana: "いつかはわかるよな" },
      { startSec: 116.8, endSec: 124.9, ja: "誰もが一人 全ては一つ", furigana: "誰もが一人 全ては一つ" },
      { startSec: 124.9, endSec: 140.3, ja: "色々な姿や形に惑わされるけどいつの日か全てが可愛く思えるさ", furigana: "色々な姿や形に惑わされるけどいつの日か全てが可愛く思えるさ" },
      { startSec: 140.3, endSec: 144.4, ja: "私は何になろうか", furigana: "私は何になろうか" },
      { startSec: 144.4, endSec: 147.8, ja: "どんな色がいいかな", furigana: "どんな色がいいかな" },
      { startSec: 147.8, endSec: 152.1, ja: "探しに行くよ", furigana: "探しに行くよ" },
      { startSec: 152.1, endSec: 156.3, ja: "内なる花を", furigana: "内なる花を" },
      { startSec: 156.3, endSec: 176.8, ja: "シワシワにしおれた花束", furigana: "シワシワにしおれた花束" },
      { startSec: 176.8, endSec: 182.3, ja: "空きに輝いて 永遠に", furigana: "空きに輝いて 永遠に" },
      { startSec: 182.3, endSec: 187.1, ja: "変わらぬ輝き探してた", furigana: "変わらぬ輝き探してた" },
      { startSec: 187.1, endSec: 191.2, ja: "僕らを信じてみた", furigana: "僕らを信じてみた" },
      { startSec: 191.2, endSec: 203.1, ja: "僕らを感じてた咲かせに行くよ無知なる花を", furigana: "僕らを感じてた咲かせに行くよ無知なる花を" },
      { startSec: 203.1, endSec: 207.1, ja: "探しに行くよ", furigana: "探しに行くよ" },
      { startSec: 207.1, endSec: 212.9, ja: "無知なる花を", furigana: "無知なる花を" },
      { startSec: 212.9, endSec: 216.8, ja: "Flowers here", furigana: "Flowers here" },
      { startSec: 216.8, endSec: 220.7, ja: "Flowers here", furigana: "Flowers here" },
      { startSec: 220.7, endSec: 243.8, ja: "おやすみなさい", furigana: "おやすみなさい" },
      { startSec: 250.7, endSec: 280.7, ja: "ご視聴ありがとうございました", furigana: "ご視聴ありがとうございました" },
    ],
    questions: [],
  },
  // narezki-43 (334.7 MB) — N2
  {
    id: "n2-narezki-long-listening",
    level: "N2",
    titleRu: "Длинное аудирование",
    descriptionRu: "Длительная аудиопрактика для подготовки к восприятию японской речи на уровне N2.",
    video: { type: "remote", src: "https://archive.org/download/japanese-trainer-narezki/narezki-43.mp4" },
    subtitles: [
      { startSec: 0, endSec: 2.3, ja: "そういうときには長ズボンがいいよ。", furigana: "そういうときには長ズボンがいいよ。" },
      { startSec: 2.6, endSec: 6.3, ja: "長ズボンだって。僕に長ズボンはまだ早いよ。", furigana: "長ズボンだって。僕に長ズボンはまだ早いよ。" },
      { startSec: 6.8, endSec: 8, ja: "スポンジボブです。", furigana: "スポンジボブです。" },
      { startSec: 8.6, endSec: 10.6, ja: "スポンジボブは寒いです。", furigana: "スポンジボブは寒いです。" },
      { startSec: 11.2, endSec: 13.9, ja: "スポンジボブはとっても寒いです。", furigana: "スポンジボブはとっても寒いです。" },
      { startSec: 14.5, endSec: 15.6, ja: "セールスマンです。", furigana: "セールスマンです。" },
      { startSec: 16.3, endSec: 18.4, ja: "彼はズボンを売っています。", furigana: "彼はズボンを売っています。" },
      { startSec: 19.1, endSec: 21.6, ja: "彼は長ズボンを売っています。", furigana: "彼は長ズボンを売っています。" },
      { startSec: 22.3, endSec: 25.1, ja: "スポンジボブには長ズボンがありません。", furigana: "スポンジボブには長ズボンがありません。" },
      { startSec: 25.7, endSec: 28.6, ja: "スポンジボブは半ズボンを履いています。", furigana: "スポンジボブは半ズボンを履いています。" },
      { startSec: 28.6, endSec: 32.2, ja: "スポンジボブは長ズボンが好きです", furigana: "スポンジボブは長ズボンが好きです" },
      { startSec: 32.2, endSec: 35.9, ja: "スポンジボブは長ズボンを欲しがっています", furigana: "スポンジボブは長ズボンを欲しがっています" },
      { startSec: 35.9, endSec: 40.3, ja: "スポンジボブは長ズボンを欲しがっていますが", furigana: "スポンジボブは長ズボンを欲しがっていますが" },
      { startSec: 40.3, endSec: 42.5, ja: "緊張しています", furigana: "緊張しています" },
      { startSec: 42.5, endSec: 44.7, ja: "まだ早いかどうか", furigana: "まだ早いかどうか" },
      { startSec: 44.7, endSec: 48.2, ja: "まだ早いかどうかわかりません", furigana: "まだ早いかどうかわかりません" },
      { startSec: 48.2, endSec: 51.2, ja: "勇気を出して履いてみますか", furigana: "勇気を出して履いてみますか" },
      { startSec: 58.6, endSec: 66.7, ja: "次に、最も重要な語彙、表現、発音、文化のコンテクストを学びます。", furigana: "次に、最も重要な語彙、表現、発音、文化のコンテクストを学びます。" },
      { startSec: 66.7, endSec: 71, ja: "最後に、サブタイトルがないフルクリップを見てみます。", furigana: "最後に、サブタイトルがないフルクリップを見てみます。" },
      { startSec: 71, endSec: 75.6, ja: "このビデオの最後まで、あまりにも理解できません。", furigana: "このビデオの最後まで、あまりにも理解できません。" },
      { startSec: 88.6, endSec: 91.6, ja: "そうかな?膝がこんなに冷えてるのに?", furigana: "そうかな?膝がこんなに冷えてるのに?" },
      { startSec: 92, endSec: 94, ja: "ちょっと背伸びして君も仲間になろう", furigana: "ちょっと背伸びして君も仲間になろう" },
      { startSec: 94, endSec: 94.9, ja: "そう!そう!そう!", furigana: "そう!そう!そう!" },
      { startSec: 95.5, endSec: 97.3, ja: "勇気を出して吐いてごらん", furigana: "勇気を出して吐いてごらん" },
      { startSec: 97.3, endSec: 99.1, ja: "でも僕まだ", furigana: "でも僕まだ" },
      { startSec: 99.1, endSec: 102.9, ja: "吐いてみる", furigana: "吐いてみる" },
      { startSec: 112.4, endSec: 114.8, ja: "この店にナナスモンの人が来た", furigana: "この店にナナスモンの人が来た" },
      { startSec: 114.8, endSec: 118, ja: "あの人僕のパパ?", furigana: "あの人僕のパパ?" },
      { startSec: 118, endSec: 125.9, ja: "あなたは天使みたい", furigana: "あなたは天使みたい" },
      { startSec: 125.9, endSec: 135.3, ja: "膝が寒い", furigana: "膝が寒い" },
      { startSec: 135.3, endSec: 138.7, ja: "膝が寒い", furigana: "膝が寒い" },
      { startSec: 138.7, endSec: 140.3, ja: "が寒い", furigana: "が寒い" },
      { startSec: 140.3, endSec: 170, ja: "寒い means cold for example you could say 手が寒いmy hands are coldシベリア並に膝が冷えるのかい 並に means as much as or like for example", furigana: "寒い means cold for example you could say 手が寒いmy hands are coldシベリア並に膝が冷えるのかい 並に means as much as or like for example" },
      { startSec: 170, endSec: 175, ja: "シベリア並に寒い means as cold as Siberia", furigana: "シベリア並に寒い means as cold as Siberia" },
      { startSec: 175, endSec: 179.8, ja: "Another example is 彼はプロ並に上手だ", furigana: "Another example is 彼はプロ並に上手だ" },
      { startSec: 179.8, endSec: 182.1, ja: "He is as good as a professional", furigana: "He is as good as a professional" },
      { startSec: 182.1, endSec: 187.1, ja: "シベリア並に膝が冷えるのかい? そういう時には長ズボンがいいよ", furigana: "シベリア並に膝が冷えるのかい? そういう時には長ズボンがいいよ" },
      { startSec: 187.1, endSec: 191, ja: "長ズボンだって? 僕に長ズボンはまだ早いよ", furigana: "長ズボンだって? 僕に長ズボンはまだ早いよ" },
      { startSec: 191, endSec: 192.5, ja: "そうかな?", furigana: "そうかな?" },
      { startSec: 192.5, endSec: 196.7, ja: "長ズボンだって? 僕に長ズボンはまだ早いよ", furigana: "長ズボンだって? 僕に長ズボンはまだ早いよ" },
      { startSec: 196.7, endSec: 200.2, ja: "まだ早い means still early", furigana: "まだ早い means still early" },
      { startSec: 200.2, endSec: 203.2, ja: "This phrase is often used to say", furigana: "This phrase is often used to say" },
      { startSec: 203.2, endSec: 206.9, ja: "it's soon for something or someone is not ready yet.", furigana: "it's soon for something or someone is not ready yet." },
      { startSec: 207.4, endSec: 209.2, ja: "For example, you could say", furigana: "For example, you could say" },
      { startSec: 209.2, endSec: 211.3, ja: "彼にはまだ早い", furigana: "彼にはまだ早い" },
      { startSec: 211.3, endSec: 214, ja: "It's still too soon for him.", furigana: "It's still too soon for him." },
      { startSec: 214.5, endSec: 218.1, ja: "長ズボンだって?僕に長ズボンはまだ早いよ。", furigana: "長ズボンだって?僕に長ズボンはまだ早いよ。" },
      { startSec: 218.8, endSec: 221.4, ja: "そうかな?膝がこんなに冷えてるのに?", furigana: "そうかな?膝がこんなに冷えてるのに?" },
      { startSec: 221.7, endSec: 222.6, ja: "ちょっと背伸びして!", furigana: "ちょっと背伸びして!" },
      { startSec: 222.8, endSec: 224.5, ja: "膝がこんなに冷えてるのに?", furigana: "膝がこんなに冷えてるのに?" },
      { startSec: 224.5, endSec: 229.7, ja: "のに is a particle that means even though or despite", furigana: "のに is a particle that means even though or despite" },
      { startSec: 229.7, endSec: 230.9, ja: "for example", furigana: "for example" },
      { startSec: 230.9, endSec: 234.4, ja: "長ズボンを履いているのに虫に刺された", furigana: "長ズボンを履いているのに虫に刺された" },
      { startSec: 234.4, endSec: 244.6, ja: "ちょっと背伸びして君も仲間になろう", furigana: "ちょっと背伸びして君も仲間になろう" },
      { startSec: 244.6, endSec: 251.3, ja: "背伸びして means to push oneself to the limit or to go past one's abilities", furigana: "背伸びして means to push oneself to the limit or to go past one's abilities" },
      { startSec: 251.3, endSec: 255.6, ja: "We use it to describe doing more than one can handle or afford", furigana: "We use it to describe doing more than one can handle or afford" },
      { startSec: 255.6, endSec: 257.8, ja: "For example, you could say", furigana: "For example, you could say" },
      { startSec: 257.8, endSec: 261.3, ja: "彼は背伸びして高級車を買った", furigana: "彼は背伸びして高級車を買った" },
      { startSec: 261.3, endSec: 265.6, ja: "He went beyond his means and bought a luxury car", furigana: "He went beyond his means and bought a luxury car" },
      { startSec: 265.6, endSec: 268.3, ja: "ちょっと背伸びして君も仲間になるぞ", furigana: "ちょっと背伸びして君も仲間になるぞ" },
      { startSec: 268.3, endSec: 269.3, ja: "そうそうそう", furigana: "そうそうそう" },
      { startSec: 269.3, endSec: 271.5, ja: "勇気を出して履いてごらん", furigana: "勇気を出して履いてごらん" },
      { startSec: 271.5, endSec: 273.2, ja: "でも僕まだ", furigana: "でも僕まだ" },
      { startSec: 273.2, endSec: 275.5, ja: "勇気を出して履いてごらん", furigana: "勇気を出して履いてごらん" },
      { startSec: 275.5, endSec: 278.6, ja: "勇気を出して means to gather up courage", furigana: "勇気を出して means to gather up courage" },
      { startSec: 278.6, endSec: 281, ja: "For example, you might say", furigana: "For example, you might say" },
      { startSec: 281, endSec: 285.2, ja: "新しい仕事に挑戦するために勇気を出してください", furigana: "新しい仕事に挑戦するために勇気を出してください" },
      { startSec: 285.2, endSec: 287.9, ja: "勇気を出して履いてごらん", furigana: "勇気を出して履いてごらん" },
      { startSec: 287.9, endSec: 289.6, ja: "でも僕まだ", furigana: "でも僕まだ" },
      { startSec: 289.6, endSec: 293.4, ja: "履いてみる", furigana: "履いてみる" },
      { startSec: 304, endSec: 305, ja: "履いてみる", furigana: "履いてみる" },
      { startSec: 305, endSec: 309.7, ja: "てみる is a common verb ending that means try to do", furigana: "てみる is a common verb ending that means try to do" },
      { startSec: 309.7, endSec: 314, ja: "for example 食べてみる means try to eat", furigana: "for example 食べてみる means try to eat" },
      { startSec: 314, endSec: 318.6, ja: "remember てみる is attached to the te-form of a verb", furigana: "remember てみる is attached to the te-form of a verb" },
      { startSec: 318.6, endSec: 322.1, ja: "so はく to wear becomes", furigana: "so はく to wear becomes" },
      { startSec: 322.1, endSec: 324.6, ja: "はいてみる try to wear", furigana: "はいてみる try to wear" },
      { startSec: 324.6, endSec: 346.4, ja: "だといいけど", furigana: "だといいけど" },
      { startSec: 346.4, endSec: 347.7, ja: "だといいけど", furigana: "だといいけど" },
      { startSec: 347.7, endSec: 350.5, ja: "means it'll be nice if", furigana: "means it'll be nice if" },
      { startSec: 350.5, endSec: 352.1, ja: "it's a bit informal", furigana: "it's a bit informal" },
      { startSec: 352.1, endSec: 355.1, ja: "so you would use it more in casual conversation.", furigana: "so you would use it more in casual conversation." },
      { startSec: 355.7, endSec: 359.9, ja: "With nouns or na adjectives, we include da.", furigana: "With nouns or na adjectives, we include da." },
      { startSec: 360.6, endSec: 365.4, ja: "But with verbs or i adjectives, we drop the da.", furigana: "But with verbs or i adjectives, we drop the da." },
      { startSec: 365.8, endSec: 367.6, ja: "For example, you could say", furigana: "For example, you could say" },
      { startSec: 367.6, endSec: 369.4, ja: "彼が来るといいけど", furigana: "彼が来るといいけど" },
      { startSec: 369.4, endSec: 371.7, ja: "It'll be nice if he comes.", furigana: "It'll be nice if he comes." },
      { startSec: 371.7, endSec: 373.4, ja: "なといいけど", furigana: "なといいけど" },
      { startSec: 373.4, endSec: 376.9, ja: "バーガーのお味はいかがですか?", furigana: "バーガーのお味はいかがですか?" },
      { startSec: 378.3, endSec: 379.5, ja: "あなた天使みたい", furigana: "あなた天使みたい" },
      { startSec: 379.5, endSec: 381.7, ja: "バーガーのお味はいかがですか?", furigana: "バーガーのお味はいかがですか?" },
      { startSec: 382.1, endSec: 386.6, ja: "は、いかがですか? means how is or how about", furigana: "は、いかがですか? means how is or how about" },
      { startSec: 386.6, endSec: 388.6, ja: "for example, you could say", furigana: "for example, you could say" },
      { startSec: 388.6, endSec: 391.3, ja: "この長ズボンはいかがですか?", furigana: "この長ズボンはいかがですか?" },
      { startSec: 392, endSec: 394.3, ja: "What do you think about these long pants?", furigana: "What do you think about these long pants?" },
      { startSec: 394.8, endSec: 396.8, ja: "バーガーのお味はいかがですか?", furigana: "バーガーのお味はいかがですか?" },
      { startSec: 398.2, endSec: 399.6, ja: "あなた天使みたい!", furigana: "あなた天使みたい!" },
      { startSec: 400.6, endSec: 402.6, ja: "あなた天使みたい!", furigana: "あなた天使みたい!" },
      { startSec: 403.1, endSec: 406.4, ja: "みたい means like or similar to", furigana: "みたい means like or similar to" },
      { startSec: 406.4, endSec: 409.1, ja: "It's a casual way to make comparisons", furigana: "It's a casual way to make comparisons" },
      { startSec: 409.1, endSec: 413.3, ja: "例えば、彼は猫みたいに寝ている。", furigana: "例えば、彼は猫みたいに寝ている。" },
      { startSec: 413.7, endSec: 415.3, ja: "He is sleeping like a cat.", furigana: "He is sleeping like a cat." },
      { startSec: 415.3, endSec: 417.1, ja: "あなた、天使みたい!", furigana: "あなた、天使みたい!" },
      { startSec: 417.5, endSec: 420.9, ja: "いいえ、僕はただの長ズボンを履いた男です。", furigana: "いいえ、僕はただの長ズボンを履いた男です。" },
      { startSec: 420.9, endSec: 439.8, ja: "いいえ、僕はただの長ズボンを履いた男です", furigana: "いいえ、僕はただの長ズボンを履いた男です" },
      { startSec: 439.8, endSec: 443.3, ja: "ただ means just or merely", furigana: "ただ means just or merely" },
      { startSec: 443.3, endSec: 453, ja: "For instance, 彼はただの友達ですHe is just a friend.いいえ、僕はただの長ズボンを履いた男です。", furigana: "For instance, 彼はただの友達ですHe is just a friend.いいえ、僕はただの長ズボンを履いた男です。" },
      { startSec: 467, endSec: 468.9, ja: "僕の大事な長ズボンが!", furigana: "僕の大事な長ズボンが!" },
      { startSec: 469.4, endSec: 470.5, ja: "何を騒いでる?", furigana: "何を騒いでる?" },
      { startSec: 470.7, endSec: 472.1, ja: "まさかズボンの一身でも…", furigana: "まさかズボンの一身でも…" },
      { startSec: 472.1, endSec: 473.2, ja: "何を騒いでる?", furigana: "何を騒いでる?" },
      { startSec: 473.2, endSec: 477.6, ja: "騒いでる means making a fuss or causing a commotion", furigana: "騒いでる means making a fuss or causing a commotion" },
      { startSec: 477.6, endSec: 482.2, ja: "For example, you might say 彼はいつも騒いでる", furigana: "For example, you might say 彼はいつも騒いでる" },
      { startSec: 482.2, endSec: 485.4, ja: "which means he is always making a fuss", furigana: "which means he is always making a fuss" },
      { startSec: 485.4, endSec: 492.8, ja: "まさかズボンにシミでもつけたか?", furigana: "まさかズボンにシミでもつけたか?" },
      { startSec: 493, endSec: 496.7, ja: "まさか means no way or can't be", furigana: "まさか means no way or can't be" },
      { startSec: 496.7, endSec: 501.9, ja: "For example, まさか彼が半ズボンを履くとは思わなかった", furigana: "For example, まさか彼が半ズボンを履くとは思わなかった" },
      { startSec: 501.9, endSec: 505.7, ja: "I didn't think he would wear shorts. No way.", furigana: "I didn't think he would wear shorts. No way." },
      { startSec: 506.1, endSec: 508, ja: "まさかズボンのシミでもつけたか?", furigana: "まさかズボンのシミでもつけたか?" },
      { startSec: 508.2, endSec: 511.9, ja: "そんなことはありません。ただ僕にはフロア係は向かないみたい。", furigana: "そんなことはありません。ただ僕にはフロア係は向かないみたい。" },
      { startSec: 514, endSec: 517.2, ja: "ただ僕にはフロア係は向かないみたい。", furigana: "ただ僕にはフロア係は向かないみたい。" },
      { startSec: 517.7, endSec: 520, ja: "向かない means not suitable.", furigana: "向かない means not suitable." },
      { startSec: 520.5, endSec: 525, ja: "For example, you could say この仕事は私には向かない。", furigana: "For example, you could say この仕事は私には向かない。" },
      { startSec: 525.4, endSec: 528, ja: "Which means this job is not suitable for me.", furigana: "Which means this job is not suitable for me." },
      { startSec: 528.4, endSec: 530.7, ja: "ただ僕にはフロア係は向かないみたい。", furigana: "ただ僕にはフロア係は向かないみたい。" },
      { startSec: 531.9, endSec: 535.4, ja: "まあそうだろうなこの店は品がないから", furigana: "まあそうだろうなこの店は品がないから" },
      { startSec: 535.4, endSec: 540, ja: "この店は品がないから", furigana: "この店は品がないから" },
      { startSec: 540, endSec: 543.3, ja: "品がない means unrefined or vulgar", furigana: "品がない means unrefined or vulgar" },
      { startSec: 543.3, endSec: 546.5, ja: "品 means elegance or class", furigana: "品 means elegance or class" },
      { startSec: 546.5, endSec: 550.3, ja: "ない means is not or there is none", furigana: "ない means is not or there is none" },
      { startSec: 550.3, endSec: 554.5, ja: "for example you can say あの男性には品がない", furigana: "for example you can say あの男性には品がない" },
      { startSec: 554.5, endSec: 556.2, ja: "この店は品がないから", furigana: "この店は品がないから" },
      { startSec: 556.2, endSec: 561.3, ja: "認めたくないけど僕はもうガニガニにふさわしくない", furigana: "認めたくないけど僕はもうガニガニにふさわしくない" },
      { startSec: 561.3, endSec: 566, ja: "認めたくない means I don't want to admit it", furigana: "認めたくない means I don't want to admit it" },
      { startSec: 566, endSec: 570.3, ja: "For example, you could say 彼の才能を認めたくない", furigana: "For example, you could say 彼の才能を認めたくない" },
      { startSec: 570.3, endSec: 573.6, ja: "which means I don't want to admit his talent", furigana: "which means I don't want to admit his talent" },
      { startSec: 573.6, endSec: 577.4, ja: "認めたくないけど僕はもうガニガニにふさわしくない", furigana: "認めたくないけど僕はもうガニガニにふさわしくない" },
      { startSec: 577.4, endSec: 579.5, ja: "次へ進む時が来たのです", furigana: "次へ進む時が来たのです" },
      { startSec: 586.2, endSec: 590.3, ja: "どこへ行くんでしょう", furigana: "どこへ行くんでしょう" },
      { startSec: 590.3, endSec: 593.2, ja: "おそらく行き先は大人の世界", furigana: "おそらく行き先は大人の世界" },
      { startSec: 593.2, endSec: 598.3, ja: "どう?", furigana: "どう?" },
      { startSec: 600, endSec: 604.7, ja: "おそらくは大人の世界。おそらく means probably or perhaps.", furigana: "おそらくは大人の世界。おそらく means probably or perhaps." },
      { startSec: 605.2, endSec: 609.8, ja: "For example, you could say おそらく彼は長ズボンを履いてみる。", furigana: "For example, you could say おそらく彼は長ズボンを履いてみる。" },
      { startSec: 610.2, endSec: 612.6, ja: "He will probably try the pants on.", furigana: "He will probably try the pants on." },
      { startSec: 612.9, endSec: 615.7, ja: "おそらく行き先は大人の世界。", furigana: "おそらく行き先は大人の世界。" },
      { startSec: 620.3, endSec: 621.8, ja: "どう?いいね。", furigana: "どう?いいね。" },
      { startSec: 623.4, endSec: 625.7, ja: "おめでとう。試験は合格です。", furigana: "おめでとう。試験は合格です。" },
      { startSec: 625.8, endSec: 626.9, ja: "やったー!", furigana: "やったー!" },
      { startSec: 626.9, endSec: 631.3, ja: "そうだ、長ズボンを履いて免許の試験を受けたことはないや", furigana: "そうだ、長ズボンを履いて免許の試験を受けたことはないや" },
      { startSec: 631.3, endSec: 632.4, ja: "やってみよう", furigana: "やってみよう" },
      { startSec: 632.4, endSec: 637.6, ja: "そうだ、長ズボンを履いて免許の試験を受けたことはないや", furigana: "そうだ、長ズボンを履いて免許の試験を受けたことはないや" },
      { startSec: 637.6, endSec: 640.8, ja: "ことはない means have not done", furigana: "ことはない means have not done" },
      { startSec: 640.8, endSec: 645, ja: "We use it to show that something has never been done before", furigana: "We use it to show that something has never been done before" },
      { startSec: 645, endSec: 651.1, ja: "So, 半ズボンを履いたことはない means I have never worn shorts before", furigana: "So, 半ズボンを履いたことはない means I have never worn shorts before" },
      { startSec: 651.1, endSec: 652.7, ja: "Here is another example", furigana: "Here is another example" },
      { startSec: 652.7, endSec: 655.4, ja: "私は寿司を食べたことはない", furigana: "私は寿司を食べたことはない" },
      { startSec: 655.4, endSec: 658.1, ja: "I have never eaten sushi before", furigana: "I have never eaten sushi before" },
      { startSec: 658.1, endSec: 677.8, ja: "さすが大人の男だぜ", furigana: "さすが大人の男だぜ" },
      { startSec: 677.8, endSec: 685, ja: "さすが is a word that expresses admiration or show that an expectation has been met", furigana: "さすが is a word that expresses admiration or show that an expectation has been met" },
      { startSec: 685, endSec: 687.3, ja: "We often use it to praise someone.", furigana: "We often use it to praise someone." },
      { startSec: 687.8, endSec: 689.5, ja: "For example, you could say", furigana: "For example, you could say" },
      { startSec: 689.5, endSec: 692.9, ja: "さすが!彼はいつも時間通りだ。", furigana: "さすが!彼はいつも時間通りだ。" },
      { startSec: 693.3, endSec: 695.7, ja: "As expected, he is always on time.", furigana: "As expected, he is always on time." },
      { startSec: 715, endSec: 722.2, ja: "いいぞコツがわかってきた", furigana: "いいぞコツがわかってきた" },
      { startSec: 722.2, endSec: 728.8, ja: "いいぞコツがわかってきた", furigana: "いいぞコツがわかってきた" },
      { startSec: 728.8, endSec: 730.3, ja: "コツがわかってきた", furigana: "コツがわかってきた" },
      { startSec: 730.3, endSec: 733, ja: "means I'm getting the hang of it", furigana: "means I'm getting the hang of it" },
      { startSec: 733, endSec: 737, ja: "the word コツ means trick or neck", furigana: "the word コツ means trick or neck" },
      { startSec: 737, endSec: 741, ja: "and わかってきた means started to understand", furigana: "and わかってきた means started to understand" },
      { startSec: 741, endSec: 743.3, ja: "for example you can say", furigana: "for example you can say" },
      { startSec: 743.3, endSec: 757.1, ja: "ピアノのコツがわかってきたI'm getting the hang of playing the pianoWhen my students have trouble learningnew words i recommend them for new it has thousands of real life videos with quizzes", furigana: "ピアノのコツがわかってきたI'm getting the hang of playing the pianoWhen my students have trouble learningnew words i recommend them for new it has thousands of real life videos with quizzes" },
      { startSec: 757.1, endSec: 763.7, ja: "that teach you the words in a real life context so it helps you remember and master vocab more", furigana: "that teach you the words in a real life context so it helps you remember and master vocab more" },
      { startSec: 763.7, endSec: 767.5, ja: "naturally go check it out", furigana: "naturally go check it out" },
      { startSec: 767.5, endSec: 776.2, ja: "君を不合格にして刑務所に送るつもりだったが、その長ズボンに免じて", furigana: "君を不合格にして刑務所に送るつもりだったが、その長ズボンに免じて" },
      { startSec: 776.2, endSec: 780.8, ja: "君を不合格にして刑務所に送るつもりだったが、つもりだった", furigana: "君を不合格にして刑務所に送るつもりだったが、つもりだった" },
      { startSec: 780.8, endSec: 789, ja: "We use it to express a past intention or plan that did not happen.", furigana: "We use it to express a past intention or plan that did not happen." },
      { startSec: 789.5, endSec: 792.3, ja: "For example, 映画を見るつもりだった", furigana: "For example, 映画を見るつもりだった" },
      { startSec: 792.3, endSec: 797.3, ja: "君を不合格にして刑務所に送るつもりだったが、その長ズボンに免じて", furigana: "君を不合格にして刑務所に送るつもりだったが、その長ズボンに免じて" },
      { startSec: 797.3, endSec: 802.9, ja: "その長ズボンに面して", furigana: "その長ズボンに面して" },
      { startSec: 802.9, endSec: 806.9, ja: "それに今頭に血が昇ってるんで合格だ", furigana: "それに今頭に血が昇ってるんで合格だ" },
      { startSec: 806.9, endSec: 808.6, ja: "頭に血が昇る", furigana: "頭に血が昇る" },
      { startSec: 808.6, endSec: 811.7, ja: "means blood rushes to one's head", furigana: "means blood rushes to one's head" },
      { startSec: 811.7, endSec: 815.1, ja: "this can be used literally or figuratively", furigana: "this can be used literally or figuratively" },
      { startSec: 815.1, endSec: 816.8, ja: "when used figuratively", furigana: "when used figuratively" },
      { startSec: 816.8, endSec: 821, ja: "it describes a state of extreme anger or agitation", furigana: "it describes a state of extreme anger or agitation" },
      { startSec: 821, endSec: 823.2, ja: "for example you could say", furigana: "for example you could say" },
      { startSec: 823.2, endSec: 826.1, ja: "彼の言葉に頭に血が昇った", furigana: "彼の言葉に頭に血が昇った" },
      { startSec: 826.1, endSec: 828.9, ja: "His words made me furious", furigana: "His words made me furious" },
      { startSec: 828.9, endSec: 830.8, ja: "その長ズボンに免じて", furigana: "その長ズボンに免じて" },
      { startSec: 830.8, endSec: 833.6, ja: "それに今頭に血が昇ってるんで合格だ", furigana: "それに今頭に血が昇ってるんで合格だ" },
      { startSec: 833.6, endSec: 836, ja: "やったー僕ついに合格したんだ", furigana: "やったー僕ついに合格したんだ" },
      { startSec: 836, endSec: 841.2, ja: "やったー僕ついに合格したんだ", furigana: "やったー僕ついに合格したんだ" },
      { startSec: 841.2, endSec: 844.7, ja: "ついに means finally or at last", furigana: "ついに means finally or at last" },
      { startSec: 844.7, endSec: 845.8, ja: "For instance", furigana: "For instance" },
      { startSec: 845.8, endSec: 849.9, ja: "彼女はついに彼と結婚することに同意した", furigana: "彼女はついに彼と結婚することに同意した" },
      { startSec: 849.9, endSec: 852.6, ja: "She finally agreed to marry him", furigana: "She finally agreed to marry him" },
      { startSec: 852.6, endSec: 855.3, ja: "やったー僕ついに合格したんだ", furigana: "やったー僕ついに合格したんだ" },
      { startSec: 855.3, endSec: 860.2, ja: "ドアに鍵をかけて窓に柵をつけなきゃ 世界の終わりが来る", furigana: "ドアに鍵をかけて窓に柵をつけなきゃ 世界の終わりが来る" },
      { startSec: 860.2, endSec: 870.9, ja: "ドアに鍵をかけて窓に柵をつけなきゃ 世界の終わりが来る", furigana: "ドアに鍵をかけて窓に柵をつけなきゃ 世界の終わりが来る" },
      { startSec: 870.9, endSec: 873.2, ja: "なきゃ means have to do", furigana: "なきゃ means have to do" },
      { startSec: 873.2, endSec: 876.4, ja: "It is a more casual version of なければ", furigana: "It is a more casual version of なければ" },
      { startSec: 876.4, endSec: 878.9, ja: "For instance, you might say", furigana: "For instance, you might say" },
      { startSec: 878.9, endSec: 882.3, ja: "半ズボンを買わなきゃ I have to buy shorts", furigana: "半ズボンを買わなきゃ I have to buy shorts" },
      { startSec: 882.3, endSec: 886.3, ja: "日本語をスポンジポップで学ぶことができますか?", furigana: "日本語をスポンジポップで学ぶことができますか?" },
      { startSec: 886.3, endSec: 890.3, ja: "ネットワークの映画や映画の中にもサブタイトルがありますか?", furigana: "ネットワークの映画や映画の中にもサブタイトルがありますか?" },
      { startSec: 890.3, endSec: 892.3, ja: "私が言ってくれます!", furigana: "私が言ってくれます!" },
      { startSec: 892.3, endSec: 898, ja: "Fluent New Chromeのエクステンションでお送りします。Fルーニューとゲットアクセス。", furigana: "Fluent New Chromeのエクステンションでお送りします。Fルーニューとゲットアクセス。" },
      { startSec: 913, endSec: 918.1, ja: "この映画はくだらなすぎて、くだらなすぎて means too ridiculous.", furigana: "この映画はくだらなすぎて、くだらなすぎて means too ridiculous." },
      { startSec: 918.8, endSec: 923.5, ja: "For example, you could say このゲームはくだらなすぎてやめたい。", furigana: "For example, you could say このゲームはくだらなすぎてやめたい。" },
      { startSec: 923.5, endSec: 927.1, ja: "This game is too ridiculous. I want to quit.", furigana: "This game is too ridiculous. I want to quit." },
      { startSec: 927.7, endSec: 934, ja: "この映画はくだらなすぎて長ズボンを履いているような洗練された紳士は入れないんです。規則なので。", furigana: "この映画はくだらなすぎて長ズボンを履いているような洗練された紳士は入れないんです。規則なので。" },
      { startSec: 934.4, endSec: 937.7, ja: "洗練された means refined or sophisticated.", furigana: "洗練された means refined or sophisticated." },
      { startSec: 938.6, endSec: 942.9, ja: "For example, you could say これは洗練されたデザインです。", furigana: "For example, you could say これは洗練されたデザインです。" },
      { startSec: 943.4, endSec: 945.7, ja: "This is a sophisticated design.", furigana: "This is a sophisticated design." },
      { startSec: 946.1, endSec: 950.8, ja: "長ズボンを履いているような洗練された紳士は入れないんです。規則なので。", furigana: "長ズボンを履いているような洗練された紳士は入れないんです。規則なので。" },
      { startSec: 950.8, endSec: 962.6, ja: "ひざだけ以外お断りだって以外 means except for or other than", furigana: "ひざだけ以外お断りだって以外 means except for or other than" },
      { startSec: 962.6, endSec: 966.7, ja: "for example コーヒー以外の飲み物はありますか", furigana: "for example コーヒー以外の飲み物はありますか" },
      { startSec: 966.7, endSec: 969.8, ja: "do you have any drinks other than coffee", furigana: "do you have any drinks other than coffee" },
      { startSec: 969.8, endSec: 973.2, ja: "in the sentence ひざだけ以外お断りだって", furigana: "in the sentence ひざだけ以外お断りだって" },
      { startSec: 973.2, endSec: 977.2, ja: "it means we refuse anything other than kneelings", furigana: "it means we refuse anything other than kneelings" },
      { startSec: 977.2, endSec: 979.5, ja: "ひざ丈以外お断りだって?", furigana: "ひざ丈以外お断りだって?" },
      { startSec: 980.2, endSec: 983, ja: "もうこんなズボン大嫌いだ", furigana: "もうこんなズボン大嫌いだ" },
      { startSec: 983, endSec: 995.7, ja: "これでもか", furigana: "これでもか" },
      { startSec: 995.7, endSec: 1006.1, ja: "大人の男ってこんな目に合うもんなの", furigana: "大人の男ってこんな目に合うもんなの" },
      { startSec: 1006.1, endSec: 1010, ja: "大人の男ってこんな目に合うもんなの?", furigana: "大人の男ってこんな目に合うもんなの?" },
      { startSec: 1010.5, endSec: 1015.8, ja: "目に合う means meet a terrible fate or have a bad experience.", furigana: "目に合う means meet a terrible fate or have a bad experience." },
      { startSec: 1016.4, endSec: 1020.8, ja: "For example, you could say こんな目に合うなんて思わなかった。", furigana: "For example, you could say こんな目に合うなんて思わなかった。" },
      { startSec: 1021.6, endSec: 1026.2, ja: "大人の男ってこんな目に合うもんなの? この面倒なズボンのせいだ。", furigana: "大人の男ってこんな目に合うもんなの? この面倒なズボンのせいだ。" },
      { startSec: 1030.6, endSec: 1033, ja: "この面倒なズボンのせいだ。", furigana: "この面倒なズボンのせいだ。" },
      { startSec: 1033, endSec: 1037.7, ja: "のせい means because of or due to", furigana: "のせい means because of or due to" },
      { startSec: 1037.7, endSec: 1042.3, ja: "for example 雨のせいで試合が中止になった", furigana: "for example 雨のせいで試合が中止になった" },
      { startSec: 1042.3, endSec: 1056.6, ja: "the game was cancelled because of the rainnote that no say is used in a negative contextwhen we want to say thanks to and assign gratitude for something we are happy about,we use no okage de.", furigana: "the game was cancelled because of the rainnote that no say is used in a negative contextwhen we want to say thanks to and assign gratitude for something we are happy about,we use no okage de." },
      { startSec: 1057, endSec: 1057.7, ja: "For example,", furigana: "For example," },
      { startSec: 1058.4, endSec: 1060.8, ja: "あなたのおかげで試験に合格した。", furigana: "あなたのおかげで試験に合格した。" },
      { startSec: 1061.4, endSec: 1063.4, ja: "Thanks to you, I passed the exam.", furigana: "Thanks to you, I passed the exam." },
      { startSec: 1063.4, endSec: 1065.7, ja: "この面倒なズボンのせいだ。", furigana: "この面倒なズボンのせいだ。" },
      { startSec: 1069.1, endSec: 1070.8, ja: "一体どうしたんだ。", furigana: "一体どうしたんだ。" },
      { startSec: 1071.4, endSec: 1072.5, ja: "全く情けない。", furigana: "全く情けない。" },
      { startSec: 1072.5, endSec: 1074, ja: "一体どうしたんだ。", furigana: "一体どうしたんだ。" },
      { startSec: 1074, endSec: 1078.7, ja: "一体 means what on earth or what the heck", furigana: "一体 means what on earth or what the heck" },
      { startSec: 1078.7, endSec: 1084.7, ja: "for instance you might say こんな時に一体誰が来たのだろう", furigana: "for instance you might say こんな時に一体誰が来たのだろう" },
      { startSec: 1084.7, endSec: 1087.7, ja: "who on earth could it be coming at this hour", furigana: "who on earth could it be coming at this hour" },
      { startSec: 1087.7, endSec: 1091.5, ja: "一体どうしたんだ 全く情けない", furigana: "一体どうしたんだ 全く情けない" },
      { startSec: 1091.5, endSec: 1094.9, ja: "全く情けない", furigana: "全く情けない" },
      { startSec: 1094.9, endSec: 1098.8, ja: "情けない means pathetic or pitiful", furigana: "情けない means pathetic or pitiful" },
      { startSec: 1098.8, endSec: 1106.4, ja: "This is a common word that's used to express disappointment or frustration towards oneself or others.", furigana: "This is a common word that's used to express disappointment or frustration towards oneself or others." },
      { startSec: 1106.8, endSec: 1108.7, ja: "For example, you might say", furigana: "For example, you might say" },
      { startSec: 1108.7, endSec: 1110.5, ja: "自分が情けない", furigana: "自分が情けない" },
      { startSec: 1110.5, endSec: 1112.5, ja: "I'm so pathetic", furigana: "I'm so pathetic" },
      { startSec: 1112.5, endSec: 1114.3, ja: "まったく情けない", furigana: "まったく情けない" },
      { startSec: 1114.3, endSec: 1118.5, ja: "長ズボンの大人の男が泣くなんてみっともないがんにょ", furigana: "長ズボンの大人の男が泣くなんてみっともないがんにょ" },
      { startSec: 1118.5, endSec: 1126.4, ja: "長ズボンの大人の男が泣くなんてみっともないがんにょ", furigana: "長ズボンの大人の男が泣くなんてみっともないがんにょ" },
      { startSec: 1126.4, endSec: 1130.3, ja: "みっともない means shameful or disgraceful.", furigana: "みっともない means shameful or disgraceful." },
      { startSec: 1130.7, endSec: 1134.7, ja: "For example, you could say その行動はみっともない", furigana: "For example, you could say その行動はみっともない" },
      { startSec: 1134.7, endSec: 1138.2, ja: "which means that behavior is disgraceful.", furigana: "which means that behavior is disgraceful." },
      { startSec: 1138.7, endSec: 1142.7, ja: "長相撲の大人の男が泣くなんてみっともないがによ。", furigana: "長相撲の大人の男が泣くなんてみっともないがによ。" },
      { startSec: 1142.7, endSec: 1144.4, ja: "えへへへへへへへ。", furigana: "えへへへへへへへ。" },
      { startSec: 1144.4, endSec: 1147.2, ja: "カーニさん、どうして映画見ないの?", furigana: "カーニさん、どうして映画見ないの?" },
      { startSec: 1147.3, endSec: 1148.8, ja: "映画なんて見てられるか。", furigana: "映画なんて見てられるか。" },
      { startSec: 1149, endSec: 1151.2, ja: "お前がここでギャンギャン泣いてるんだから。", furigana: "お前がここでギャンギャン泣いてるんだから。" },
      { startSec: 1151.6, endSec: 1152.7, ja: "カーニさん、僕…", furigana: "カーニさん、僕…" },
      { startSec: 1152.7, endSec: 1155.5, ja: "お前がここでギャンギャン泣いてるんだから。", furigana: "お前がここでギャンギャン泣いてるんだから。" },
      { startSec: 1155.5, endSec: 1157.4, ja: "ギャンギャン泣いている", furigana: "ギャンギャン泣いている" },
      { startSec: 1157.4, endSec: 1161.9, ja: "means is crying loudly or is crying a lot", furigana: "means is crying loudly or is crying a lot" },
      { startSec: 1161.9, endSec: 1165.1, ja: "ギャンギャン is an onomatopoeic word", furigana: "ギャンギャン is an onomatopoeic word" },
      { startSec: 1165.1, endSec: 1167.3, ja: "for example you could say", furigana: "for example you could say" },
      { startSec: 1167.3, endSec: 1169.9, ja: "彼女はギャンギャン泣いていた", furigana: "彼女はギャンギャン泣いていた" },
      { startSec: 1169.9, endSec: 1172.5, ja: "which means she was crying loudly", furigana: "which means she was crying loudly" },
      { startSec: 1172.5, endSec: 1175.4, ja: "お前がここでギャンギャン泣いてるんだから", furigana: "お前がここでギャンギャン泣いてるんだから" },
      { startSec: 1175.4, endSec: 1178.3, ja: "カーニーさん僕にはまだ長ズボンは早いみたい", furigana: "カーニーさん僕にはまだ長ズボンは早いみたい" },
      { startSec: 1178.3, endSec: 1180, ja: "いつもの半ズボンにも", furigana: "いつもの半ズボンにも" },
      { startSec: 1180, endSec: 1183.9, ja: "カーニーさん僕にはまだ長ズボンは早いみたい", furigana: "カーニーさん僕にはまだ長ズボンは早いみたい" },
      { startSec: 1183.9, endSec: 1193, ja: "いつもの半ズボンに戻りたい", furigana: "いつもの半ズボンに戻りたい" },
      { startSec: 1193, endSec: 1196.6, ja: "いつもの means usual or habitual", furigana: "いつもの means usual or habitual" },
      { startSec: 1196.6, endSec: 1199.7, ja: "For example, if you order the same coffee", furigana: "For example, if you order the same coffee" },
      { startSec: 1200, endSec: 1205.1, ja: "Every time you visit the cafe, you might say, いつものコーヒーをください。", furigana: "Every time you visit the cafe, you might say, いつものコーヒーをください。" },
      { startSec: 1205.6, endSec: 1207.6, ja: "I'll take my usual coffee, please.", furigana: "I'll take my usual coffee, please." },
      { startSec: 1208.3, endSec: 1212.7, ja: "いつもの半ズボンに戻りたい。でもこのズボンがどうやったって脱げないんです。", furigana: "いつもの半ズボンに戻りたい。でもこのズボンがどうやったって脱げないんです。" },
      { startSec: 1214.1, endSec: 1217.7, ja: "でもこのズボンがどうやったって脱げないんです。", furigana: "でもこのズボンがどうやったって脱げないんです。" },
      { startSec: 1218.5, endSec: 1221.6, ja: "どうやったって means no matter what I do.", furigana: "どうやったって means no matter what I do." },
      { startSec: 1222.1, endSec: 1227.9, ja: "For example, you could say, どうやったって彼は私の意見を聞かない。", furigana: "For example, you could say, どうやったって彼は私の意見を聞かない。" },
      { startSec: 1227.9, endSec: 1231.7, ja: "No matter what I do, he won't listen to my opinion", furigana: "No matter what I do, he won't listen to my opinion" },
      { startSec: 1231.7, endSec: 1234.7, ja: "でもこのズボンがどうやったって脱げないんです", furigana: "でもこのズボンがどうやったって脱げないんです" },
      { startSec: 1234.7, endSec: 1236.6, ja: "全く世話が焼けるかに", furigana: "全く世話が焼けるかに" },
      { startSec: 1236.6, endSec: 1241.2, ja: "切りすぎちゃってすんまい", furigana: "切りすぎちゃってすんまい" },
      { startSec: 1241.2, endSec: 1243.2, ja: "全く世話が焼けるかに", furigana: "全く世話が焼けるかに" },
      { startSec: 1243.2, endSec: 1248.1, ja: "世話が焼ける means to be a handful or to cause trouble", furigana: "世話が焼ける means to be a handful or to cause trouble" },
      { startSec: 1248.1, endSec: 1256.8, ja: "This is often used to describe someone or something that is helpless and requires a lot of attention or care", furigana: "This is often used to describe someone or something that is helpless and requires a lot of attention or care" },
      { startSec: 1256.8, endSec: 1261.6, ja: "例えば、彼は本当に世話が焼ける。", furigana: "例えば、彼は本当に世話が焼ける。" },
      { startSec: 1262, endSec: 1263.8, ja: "彼は本当に世話が焼ける。", furigana: "彼は本当に世話が焼ける。" },
      { startSec: 1264.4, endSec: 1266.2, ja: "これは、通常の話で、", furigana: "これは、通常の話で、" },
      { startSec: 1266.2, endSec: 1269.9, ja: "日本語の言語ではなく、", furigana: "日本語の言語ではなく、" },
      { startSec: 1270, endSec: 1271, ja: "古い文字で使われる言語です。", furigana: "古い文字で使われる言語です。" },
      { startSec: 1271.6, endSec: 1276.8, ja: "日本語は、難しい言語を使うことができない、", furigana: "日本語は、難しい言語を使うことができない、" },
      { startSec: 1276.8, endSec: 1278, ja: "正しい技術がない、と言うことが分かっています。", furigana: "正しい技術がない、と言うことが分かっています。" },
      { startSec: 1278.3, endSec: 1280.4, ja: "だから、私は、", furigana: "だから、私は、" },
      { startSec: 1280.4, endSec: 1283.4, ja: "日本語の動画を見ることができるように、", furigana: "日本語の動画を見ることができるように、" },
      { startSec: 1283.4, endSec: 1289, ja: "Where all videos have interactive subtitles that instantly show you definitions,", furigana: "Where all videos have interactive subtitles that instantly show you definitions," },
      { startSec: 1289.7, endSec: 1294.2, ja: "including idiomatic expressions that you wouldn't find in a regular dictionary.", furigana: "including idiomatic expressions that you wouldn't find in a regular dictionary." },
      { startSec: 1303.3, endSec: 1305.4, ja: "切りすぎちゃってすまんな", furigana: "切りすぎちゃってすまんな" },
      { startSec: 1305.4, endSec: 1308.7, ja: "すぎちゃって means to do too much.", furigana: "すぎちゃって means to do too much." },
      { startSec: 1308.7, endSec: 1314.5, ja: "This is a casual way of expressing regret for doing an action excessively.", furigana: "This is a casual way of expressing regret for doing an action excessively." },
      { startSec: 1314.9, endSec: 1316.6, ja: "For example, you could say", furigana: "For example, you could say" },
      { startSec: 1316.6, endSec: 1319.4, ja: "食べ過ぎちゃってお腹が痛い", furigana: "食べ過ぎちゃってお腹が痛い" },
      { startSec: 1319.4, endSec: 1322.2, ja: "I ate too much my stomach hurts", furigana: "I ate too much my stomach hurts" },
      { startSec: 1322.2, endSec: 1338.2, ja: "じゃあ、あなたはどポンジですからだがが、そりゃよかったじゃあ明日からフライ係に戻ってもらおうかそれでまた大人になるじゃあ明日からフライ係に戻ってもらおうか", furigana: "じゃあ、あなたはどポンジですからだがが、そりゃよかったじゃあ明日からフライ係に戻ってもらおうかそれでまた大人になるじゃあ明日からフライ係に戻ってもらおうか" },
      { startSec: 1338.2, endSec: 1339.7, ja: "てもらおう", furigana: "てもらおう" },
      { startSec: 1339.7, endSec: 1341.4, ja: "is a verb ending meaning", furigana: "is a verb ending meaning" },
      { startSec: 1341.4, endSec: 1344.2, ja: "will have someone do something for me", furigana: "will have someone do something for me" },
      { startSec: 1344.2, endSec: 1345.3, ja: "for example", furigana: "for example" },
      { startSec: 1345.3, endSec: 1348.6, ja: "この仕事、彼に手伝ってもらおう", furigana: "この仕事、彼に手伝ってもらおう" },
      { startSec: 1348.6, endSec: 1351.5, ja: "I'll have him help me with this work", furigana: "I'll have him help me with this work" },
      { startSec: 1351.5, endSec: 1354.5, ja: "じゃあ明日からフライ係に戻ってもらおうか", furigana: "じゃあ明日からフライ係に戻ってもらおうか" },
      { startSec: 1354.5, endSec: 1357.1, ja: "それでまた大人になったような気分になったら", furigana: "それでまた大人になったような気分になったら" },
      { startSec: 1357.1, endSec: 1360, ja: "その時は外でバーベキューをしていいぞ", furigana: "その時は外でバーベキューをしていいぞ" },
      { startSec: 1360, endSec: 1364.3, ja: "それって最高!", furigana: "それって最高!" },
      { startSec: 1364.8, endSec: 1368, ja: "最高 means awesome or the best", furigana: "最高 means awesome or the best" },
      { startSec: 1368, endSec: 1371.6, ja: "You might say この長ズボンは最高だ", furigana: "You might say この長ズボンは最高だ" },
      { startSec: 1371.6, endSec: 1374.1, ja: "These long pants are the best", furigana: "These long pants are the best" },
      { startSec: 1374.1, endSec: 1378.2, ja: "それって最高! 店に行く時は運転していきますね", furigana: "それって最高! 店に行く時は運転していきますね" },
      { startSec: 1378.2, endSec: 1379.2, ja: "ちょっと待った!", furigana: "ちょっと待った!" },
      { startSec: 1380.2, endSec: 1382.7, ja: "運転しちゃいかん! 半ズボンに戻ったんだから", furigana: "運転しちゃいかん! 半ズボンに戻ったんだから" },
      { startSec: 1382.7, endSec: 1384.3, ja: "運転しちゃいかん!", furigana: "運転しちゃいかん!" },
      { startSec: 1384.5, endSec: 1387.7, ja: "しちゃいかん means you may not do", furigana: "しちゃいかん means you may not do" },
      { startSec: 1387.7, endSec: 1392.3, ja: "This is an even more casual version of しちゃいけない", furigana: "This is an even more casual version of しちゃいけない" },
      { startSec: 1392.3, endSec: 1397.5, ja: "For example, you could say 飲酒後は運転しちゃいかん", furigana: "For example, you could say 飲酒後は運転しちゃいかん" },
      { startSec: 1397.5, endSec: 1400.3, ja: "You must not drive after drinking", furigana: "You must not drive after drinking" },
      { startSec: 1414.5, endSec: 1420.3, ja: "何の騒ぎかは知らないけど、終わったみたいでよかった。", furigana: "何の騒ぎかは知らないけど、終わったみたいでよかった。" },
      { startSec: 1420.8, endSec: 1425.2, ja: "で、よかった translates to I'm glad that.", furigana: "で、よかった translates to I'm glad that." },
      { startSec: 1425.6, endSec: 1429.7, ja: "For example, 免許の試験が終わってよかった。", furigana: "For example, 免許の試験が終わってよかった。" },
      { startSec: 1430.3, endSec: 1433, ja: "I'm glad that the road test is over.", furigana: "I'm glad that the road test is over." },
      { startSec: 1439, endSec: 1440.1, ja: "膝が寒い。", furigana: "膝が寒い。" },
      { startSec: 1441.1, endSec: 1442.9, ja: "今、膝が寒いって言ったね。", furigana: "今、膝が寒いって言ったね。" },
      { startSec: 1442.9, endSec: 1445.2, ja: "シベリア並みに膝が冷えるのかい", furigana: "シベリア並みに膝が冷えるのかい" },
      { startSec: 1445.2, endSec: 1447.7, ja: "そういう時には長ズボンがいいよ", furigana: "そういう時には長ズボンがいいよ" },
      { startSec: 1447.7, endSec: 1449.2, ja: "長ズボンだって", furigana: "長ズボンだって" },
      { startSec: 1449.2, endSec: 1451.7, ja: "僕に長ズボンはまだ早いよ", furigana: "僕に長ズボンはまだ早いよ" },
      { startSec: 1451.7, endSec: 1453.1, ja: "そうかな", furigana: "そうかな" },
      { startSec: 1453.1, endSec: 1463.4, ja: "膝がこんなに冷えてるのにちょっと背伸びして君も仲間になろうそうそそうそうそう!勇気を出して履いてごらん!あぁ、でも僕まだはぁん…", furigana: "膝がこんなに冷えてるのにちょっと背伸びして君も仲間になろうそうそそうそうそう!勇気を出して履いてごらん!あぁ、でも僕まだはぁん…" },
      { startSec: 1465.3, endSec: 1466.2, ja: "履いてみるよ!", furigana: "履いてみるよ!" },
      { startSec: 1475.8, endSec: 1477.6, ja: "この店に七つ門の人が…", furigana: "この店に七つ門の人が…" },
      { startSec: 1479.8, endSec: 1481.6, ja: "あの人僕のパパ?", furigana: "あの人僕のパパ?" },
      { startSec: 1481.6, endSec: 1483.1, ja: "だといいけど…", furigana: "だといいけど…" },
      { startSec: 1483.1, endSec: 1486.3, ja: "バーガーのお味はいかがですか?", furigana: "バーガーのお味はいかがですか?" },
      { startSec: 1487.7, endSec: 1489.2, ja: "あなた天使みたい", furigana: "あなた天使みたい" },
      { startSec: 1489.2, endSec: 1492.8, ja: "いいえ、僕はただの長ズボンを履いた男です", furigana: "いいえ、僕はただの長ズボンを履いた男です" },
      { startSec: 1506.8, endSec: 1508.7, ja: "僕の大事な長ズボンが!", furigana: "僕の大事な長ズボンが!" },
      { startSec: 1509.2, endSec: 1512.4, ja: "何を騒いでる!まさかズボンにシミでもつけたか?", furigana: "何を騒いでる!まさかズボンにシミでもつけたか?" },
      { startSec: 1512.4, endSec: 1516.4, ja: "そんなことはありません。ただ僕にはフロア係は向かないみたい。", furigana: "そんなことはありません。ただ僕にはフロア係は向かないみたい。" },
      { startSec: 1517.4, endSec: 1520.9, ja: "まあ、そうだろうな。この店は品がないから。", furigana: "まあ、そうだろうな。この店は品がないから。" },
      { startSec: 1520.9, endSec: 1521.4, ja: "あ。", furigana: "あ。" },
      { startSec: 1522.6, endSec: 1525.9, ja: "認めたくないけど、僕はもうカニカニにふさわしくない。", furigana: "認めたくないけど、僕はもうカニカニにふさわしくない。" },
      { startSec: 1526.2, endSec: 1527.9, ja: "次へ進む時が来たのです。", furigana: "次へ進む時が来たのです。" },
      { startSec: 1533.9, endSec: 1535.1, ja: "ふぅー、ふぅー。", furigana: "ふぅー、ふぅー。" },
      { startSec: 1537.4, endSec: 1538.7, ja: "どこへ行くんでしょう?", furigana: "どこへ行くんでしょう?" },
      { startSec: 1538.7, endSec: 1541.7, ja: "おそらく行き先は、大人の世界。", furigana: "おそらく行き先は、大人の世界。" },
      { startSec: 1542.4, endSec: 1547.8, ja: "どう?いいね", furigana: "どう?いいね" },
      { startSec: 1547.8, endSec: 1551.8, ja: "おめでとう、試験は合格です", furigana: "おめでとう、試験は合格です" },
      { startSec: 1551.8, endSec: 1553.3, ja: "やったー!", furigana: "やったー!" },
      { startSec: 1553.6, endSec: 1557.4, ja: "そうだ、長ズボンを履いて免許の試験を受けたことはないや", furigana: "そうだ、長ズボンを履いて免許の試験を受けたことはないや" },
      { startSec: 1557.4, endSec: 1558.7, ja: "やってみよう", furigana: "やってみよう" },
      { startSec: 1558.7, endSec: 1562, ja: "さすが大人の男だぜ", furigana: "さすが大人の男だぜ" },
      { startSec: 1569.7, endSec: 1571.6, ja: "次は重熱注射をやろう", furigana: "次は重熱注射をやろう" },
      { startSec: 1571.6, endSec: 1573, ja: "ゆっくり進めて", furigana: "ゆっくり進めて" },
      { startSec: 1573, endSec: 1576.5, ja: "もう少し早く", furigana: "もう少し早く" },
      { startSec: 1576.5, endSec: 1596.7, ja: "いいぞコツがわかってきた君を不合格にして刑務所に送るつもりだったがその長ズボンに免じてそれに今頭に血が昇ってるんで合格だ", furigana: "いいぞコツがわかってきた君を不合格にして刑務所に送るつもりだったがその長ズボンに免じてそれに今頭に血が昇ってるんで合格だ" },
      { startSec: 1596.7, endSec: 1599, ja: "やったー僕ついに合格したんだ", furigana: "やったー僕ついに合格したんだ" },
      { startSec: 1599, endSec: 1602.5, ja: "ドアに鍵をかけて窓に柵をつけなきゃ", furigana: "ドアに鍵をかけて窓に柵をつけなきゃ" },
      { startSec: 1602.5, endSec: 1603.8, ja: "世界の終わりが来る", furigana: "世界の終わりが来る" },
      { startSec: 1603.8, endSec: 1609.4, ja: "ああすみません", furigana: "ああすみません" },
      { startSec: 1609.4, endSec: 1610.7, ja: "あなたは入れません", furigana: "あなたは入れません" },
      { startSec: 1610.7, endSec: 1612.7, ja: "この映画はくだらなすぎて", furigana: "この映画はくだらなすぎて" },
      { startSec: 1612.7, endSec: 1616.2, ja: "長ズボンを履いているような洗練された紳士は入れないんです", furigana: "長ズボンを履いているような洗練された紳士は入れないんです" },
      { startSec: 1616.2, endSec: 1617.4, ja: "規則なので", furigana: "規則なので" },
      { startSec: 1617.4, endSec: 1619.9, ja: "何これ", furigana: "何これ" },
      { startSec: 1619.9, endSec: 1622, ja: "膝丈以外お断りだって", furigana: "膝丈以外お断りだって" },
      { startSec: 1622, endSec: 1625.5, ja: "もうこんなズボン大嫌いだ", furigana: "もうこんなズボン大嫌いだ" },
      { startSec: 1625.5, endSec: 1638.2, ja: "これでもか", furigana: "これでもか" },
      { startSec: 1642.7, endSec: 1648.5, ja: "大人の男ってこんな目に合うもんなの", furigana: "大人の男ってこんな目に合うもんなの" },
      { startSec: 1648.5, endSec: 1650.9, ja: "この面倒なズボンのせいだ", furigana: "この面倒なズボンのせいだ" },
      { startSec: 1650.9, endSec: 1656.1, ja: "一体どうしたんだ", furigana: "一体どうしたんだ" },
      { startSec: 1656.1, endSec: 1657.7, ja: "全く情けない", furigana: "全く情けない" },
      { startSec: 1657.7, endSec: 1660.6, ja: "長ズボンの大人の男が泣くなんて", furigana: "長ズボンの大人の男が泣くなんて" },
      { startSec: 1660.6, endSec: 1662, ja: "みっともないがによ", furigana: "みっともないがによ" },
      { startSec: 1662, endSec: 1666.5, ja: "カーニさんどうして映画見ないの", furigana: "カーニさんどうして映画見ないの" },
      { startSec: 1666.5, endSec: 1668.1, ja: "映画なんて見てられるか", furigana: "映画なんて見てられるか" },
      { startSec: 1668.1, endSec: 1670.6, ja: "お前がここでギャンギャン泣いてるんだから", furigana: "お前がここでギャンギャン泣いてるんだから" },
      { startSec: 1670.6, endSec: 1678.6, ja: "カーニさん、僕にはまだ長ズボンは早いみたい。いつもの半ズボンに戻りたい。でもこのズボンがどうやったって脱げないんです。", furigana: "カーニさん、僕にはまだ長ズボンは早いみたい。いつもの半ズボンに戻りたい。でもこのズボンがどうやったって脱げないんです。" },
      { startSec: 1678.9, endSec: 1680.5, ja: "全く世話が焼けるがに。", furigana: "全く世話が焼けるがに。" },
      { startSec: 1683.9, endSec: 1685.5, ja: "切りすぎちゃってすまんな。", furigana: "切りすぎちゃってすまんな。" },
      { startSec: 1685.6, endSec: 1688.5, ja: "わわわわわ、大丈夫。僕スポンジですから。", furigana: "わわわわわ、大丈夫。僕スポンジですから。" },
      { startSec: 1689.7, endSec: 1694.3, ja: "だがが、そりゃよかった。じゃあ明日からフライ係に戻ってもらおうか。", furigana: "だがが、そりゃよかった。じゃあ明日からフライ係に戻ってもらおうか。" },
      { startSec: 1694.6, endSec: 1699.7, ja: "それでまた大人になったような気分になったら、その時は外でバーベキューをしていいぞ。", furigana: "それでまた大人になったような気分になったら、その時は外でバーベキューをしていいぞ。" },
      { startSec: 1699.7, endSec: 1703.6, ja: "それって最高!店に行くときは運転していきますね", furigana: "それって最高!店に行くときは運転していきますね" },
      { startSec: 1703.6, endSec: 1704.6, ja: "ちょっと待った!", furigana: "ちょっと待った!" },
      { startSec: 1705.6, endSec: 1708.5, ja: "運転しちゃいかん!ハンズマンに戻ったんだからな!", furigana: "運転しちゃいかん!ハンズマンに戻ったんだからな!" },
      { startSec: 1716.2, endSec: 1719.7, ja: "何の騒ぎかは知らないけど終わったみたいでよかった", furigana: "何の騒ぎかは知らないけど終わったみたいでよかった" },
    ],
    questions: [],
  },
];
