import type { Lesson } from "./content";

export const NAREZKI_NEW: Lesson[] = [
  // narezki-34 (4.7 MB) — N4
  {
    id: "n4-narezki-frieren-magic",
    level: "N4",
    titleRu: "Фрирен: магия запаха",
    descriptionRu: "Сцена из аниме «Провожающая в последний путь Фрирен» (~1 мин). Фрирен испытывает магию запаха. Разговорная речь, N4.",
    video: { type: "remote", src: "https://archive.org/download/japanese-trainer-narezki/narezki-34.mp4" },
    subtitles: [
      { startSec: 1, endSec: 3.9, ja: "早々のフリーレン 〇〇の魔法", furigana: "早々のフリーレン 〇〇の魔法" },
      { startSec: 3.9, endSec: 8.6, ja: "体からいい匂いが出る魔法", furigana: "体からいい匂いが出る魔法" },
      { startSec: 8.6, endSec: 13.9, ja: "いい匂いって言ってもどういう匂いなんだろう", furigana: "いい匂いって言ってもどういう匂いなんだろう" },
      { startSec: 13.9, endSec: 17.9, ja: "人それぞれいいと感じる匂いって違いますからね", furigana: "人それぞれいいと感じる匂いって違いますからね" },
      { startSec: 17.9, endSec: 23.9, ja: "香水のような感じや花の香りだったり爽やかな香りだったりでしょうか", furigana: "香水のような感じや花の香りだったり爽やかな香りだったりでしょうか" },
      { startSec: 23.9, endSec: 26.4, ja: "例によって試してみようか", furigana: "例によって試してみようか" },
      { startSec: 26.4, endSec: 27.8, ja: "ねえシュタルク", furigana: "ねえシュタルク" },
      { startSec: 27.8, endSec: 29.7, ja: "ん?なに?", furigana: "ん?なに?" },
      { startSec: 30, endSec: 36.6, ja: "フリーレン様お肉を焼いたような匂いが", furigana: "フリーレン様お肉を焼いたような匂いが" },
      { startSec: 36.6, endSec: 40.7, ja: "すごく香ばしいね食欲をそそるというか", furigana: "すごく香ばしいね食欲をそそるというか" },
      { startSec: 40.7, endSec: 46, ja: "この魔法を作った魔法使いにとっていい匂いということのようですね", furigana: "この魔法を作った魔法使いにとっていい匂いということのようですね" },
      { startSec: 46, endSec: 49.2, ja: "美味しそうな匂い", furigana: "美味しそうな匂い" },
      { startSec: 49.2, endSec: 50.1, ja: "な、なに?", furigana: "な、なに?" },
      { startSec: 51.1, endSec: 52.7, ja: "ていうか今日の晩飯どうする?", furigana: "ていうか今日の晩飯どうする?" },
      { startSec: 55.6, endSec: 56, ja: "肉", furigana: "肉" },
      { startSec: 56, endSec: 59, ja: "え?なに?なんか怖いんだけど", furigana: "え?なに?なんか怖いんだけど" },
      { startSec: 59, endSec: 89, ja: "ご視聴ありがとうございました", furigana: "ご視聴ありがとうございました" },
    ],
    questions: [],
  },
  // narezki-35 (7.8 MB) — N5
  {
    id: "n5-narezki-japanese-food",
    level: "N5",
    titleRu: "Японская еда: лексика",
    descriptionRu: "Названия японских блюд и ингредиентов: フルーツサンド, ナポリタン, うなじゅう, 卵かけご飯 и другие. N5.",
    video: { type: "remote", src: "https://archive.org/download/japanese-trainer-narezki/narezki-35.mp4" },
    subtitles: [
      { startSec: 0, endSec: 6, ja: "ユニークな日本の食べ物", furigana: "ユニークな日本の食べ物" },
      { startSec: 6, endSec: 9, ja: "フルーツサンド", furigana: "フルーツサンド" },
      { startSec: 9, endSec: 11, ja: "食パン", furigana: "食パン" },
      { startSec: 11, endSec: 14, ja: "ホイップクリーム", furigana: "ホイップクリーム" },
      { startSec: 14, endSec: 18, ja: "果物", furigana: "果物" },
      { startSec: 18, endSec: 24, ja: "ハッシュドビーフまたは林ライス", furigana: "ハッシュドビーフまたは林ライス" },
      { startSec: 24, endSec: 26, ja: "牛肉", furigana: "牛肉" },
      { startSec: 26, endSec: 29, ja: "玉ねぎ", furigana: "玉ねぎ" },
      { startSec: 29, endSec: 30.4, ja: "マッシュルーム", furigana: "マッシュルーム" },
      { startSec: 30.4, endSec: 33.4, ja: "デミグラスソース", furigana: "デミグラスソース" },
      { startSec: 33.4, endSec: 34.9, ja: "ご飯", furigana: "ご飯" },
      { startSec: 34.9, endSec: 41.1, ja: "ナポリタン", furigana: "ナポリタン" },
      { startSec: 41.1, endSec: 43.8, ja: "ケチャップスパゲッティ", furigana: "ケチャップスパゲッティ" },
      { startSec: 43.8, endSec: 46.1, ja: "ピーマン", furigana: "ピーマン" },
      { startSec: 46.1, endSec: 48, ja: "マッシュルーム", furigana: "マッシュルーム" },
      { startSec: 48, endSec: 51.1, ja: "ベーコン", furigana: "ベーコン" },
      { startSec: 51.1, endSec: 52.9, ja: "玉ねぎ", furigana: "玉ねぎ" },
      { startSec: 57, endSec: 58.5, ja: "シーフードドリア", furigana: "シーフードドリア" },
      { startSec: 58.5, endSec: 69.5, ja: "チーズ エビ イカ ホタテ ホワイトソース バターライス", furigana: "チーズ エビ イカ ホタテ ホワイトソース バターライス" },
      { startSec: 69.5, endSec: 89, ja: "カレーうどんうどん カレーとだし 万能ギ和風ハンバーグ ハンバーグ", furigana: "カレーうどんうどん カレーとだし 万能ギ和風ハンバーグ ハンバーグ" },
      { startSec: 89, endSec: 93.8, ja: "大根おろし ポン酢", furigana: "大根おろし ポン酢" },
      { startSec: 97.8, endSec: 101.6, ja: "メンチカツ パン粉", furigana: "メンチカツ パン粉" },
      { startSec: 101.6, endSec: 103.8, ja: "ひき肉", furigana: "ひき肉" },
      { startSec: 103.8, endSec: 109.8, ja: "うなじゅう", furigana: "うなじゅう" },
      { startSec: 109.8, endSec: 112.5, ja: "うなぎのかば焼き", furigana: "うなぎのかば焼き" },
      { startSec: 112.5, endSec: 114.2, ja: "白ご飯", furigana: "白ご飯" },
      { startSec: 114.2, endSec: 119.7, ja: "焼きそばパン", furigana: "焼きそばパン" },
      { startSec: 119.7, endSec: 122.5, ja: "こっぺパン", furigana: "こっぺパン" },
      { startSec: 122.5, endSec: 124, ja: "焼きそば", furigana: "焼きそば" },
      { startSec: 124, endSec: 126.5, ja: "紅生姜", furigana: "紅生姜" },
      { startSec: 126.5, endSec: 128.9, ja: "青のり", furigana: "青のり" },
      { startSec: 131.6, endSec: 134.3, ja: "卵かけご飯", furigana: "卵かけご飯" },
      { startSec: 134.3, endSec: 137.1, ja: "白ご飯", furigana: "白ご飯" },
      { startSec: 137.1, endSec: 139.5, ja: "生卵", furigana: "生卵" },
      { startSec: 139.5, endSec: 141.8, ja: "醤油", furigana: "醤油" },
      { startSec: 141.8, endSec: 147.1, ja: "どれを食べてみたいですか?", furigana: "どれを食べてみたいですか?" },
    ],
    questions: [],
  },
  // narezki-36 (8.7 MB) — N5
  {
    id: "n5-narezki-time",
    level: "N5",
    titleRu: "Время",
    descriptionRu: "Как определять время по часам на японском. Базовые числа, часы и минуты. Уровень N5.",
    video: { type: "remote", src: "https://archive.org/download/japanese-trainer-narezki/narezki-36.mp4" },
    subtitles: [
      { startSec: 0, endSec: 3.4, ja: "何時かな?", furigana: "何時かな?" },
      { startSec: 4.4, endSec: 6.8, ja: "時計の読み方を覚えよう", furigana: "時計の読み方を覚えよう" },
      { startSec: 6.8, endSec: 14.6, ja: "時計には短い針と長い針があるよ", furigana: "時計には短い針と長い針があるよ" },
      { startSec: 14.6, endSec: 21.2, ja: "短い針が何時、長い針が何分を指すよ", furigana: "短い針が何時、長い針が何分を指すよ" },
      { startSec: 23.2, endSec: 25.2, ja: "例えば、これは3時", furigana: "例えば、これは3時" },
      { startSec: 25.2, endSec: 29.2, ja: "これは6時", furigana: "これは6時" },
      { startSec: 29.2, endSec: 33.6, ja: "これはくじだよ", furigana: "これはくじだよ" },
      { startSec: 33.6, endSec: 39.9, ja: "長い針は小さい目盛り一つで1分だから", furigana: "長い針は小さい目盛り一つで1分だから" },
      { startSec: 39.9, endSec: 45, ja: "1 2 3 4 5分", furigana: "1 2 3 4 5分" },
      { startSec: 45, endSec: 49.9, ja: "10分 15分 20分", furigana: "10分 15分 20分" },
      { startSec: 49.9, endSec: 53, ja: "25分 30分", furigana: "25分 30分" },
      { startSec: 53, endSec: 56.1, ja: "35分 40分", furigana: "35分 40分" },
      { startSec: 56.1, endSec: 69.7, ja: "45分 50分55分と読むよそれから30分のことを3とも言うよ", furigana: "45分 50分55分と読むよそれから30分のことを3とも言うよ" },
      { startSec: 69.7, endSec: 74.3, ja: "それじゃあ問題いってみよう", furigana: "それじゃあ問題いってみよう" },
      { startSec: 74.3, endSec: 79.4, ja: "何時かな", furigana: "何時かな" },
      { startSec: 79.4, endSec: 83, ja: "2時", furigana: "2時" },
      { startSec: 88.8, endSec: 91.5, ja: "何時かな?", furigana: "何時かな?" },
      { startSec: 92.9, endSec: 95, ja: "5時", furigana: "5時" },
      { startSec: 95, endSec: 103.5, ja: "何時かな?", furigana: "何時かな?" },
      { startSec: 106.3, endSec: 107.8, ja: "7時", furigana: "7時" },
      { startSec: 107.8, endSec: 115.4, ja: "何時かな?", furigana: "何時かな?" },
      { startSec: 115.4, endSec: 117.4, ja: "何時かな?", furigana: "何時かな?" },
      { startSec: 117.4, endSec: 119.4, ja: "10時", furigana: "10時" },
      { startSec: 119.4, endSec: 139.4, ja: "何時かな?12時何時かな?", furigana: "何時かな?12時何時かな?" },
      { startSec: 142.5, endSec: 144.2, ja: "1時30分", furigana: "1時30分" },
      { startSec: 151.4, endSec: 152.4, ja: "何時かな?", furigana: "何時かな?" },
      { startSec: 152.6, endSec: 157.4, ja: "3時10分", furigana: "3時10分" },
      { startSec: 157.4, endSec: 163.5, ja: "何時かな", furigana: "何時かな" },
      { startSec: 163.5, endSec: 168.5, ja: "4時45分", furigana: "4時45分" },
      { startSec: 175.2, endSec: 176.4, ja: "何時かな", furigana: "何時かな" },
      { startSec: 176.4, endSec: 181.6, ja: "7時25分", furigana: "7時25分" },
      { startSec: 181.6, endSec: 202.2, ja: "ご視聴ありがとうございました何時かな?9時40分何時かな?", furigana: "ご視聴ありがとうございました何時かな?9時40分何時かな?" },
      { startSec: 204.8, endSec: 206.9, ja: "10時15分", furigana: "10時15分" },
      { startSec: 206.9, endSec: 215.2, ja: "何時かな?", furigana: "何時かな?" },
      { startSec: 216.4, endSec: 220.7, ja: "12時55分", furigana: "12時55分" },
      { startSec: 220.7, endSec: 227, ja: "時計の読み方わかったかな?", furigana: "時計の読み方わかったかな?" },
      { startSec: 228.8, endSec: 230.8, ja: "じゃあね、またね", furigana: "じゃあね、またね" },
      { startSec: 237.3, endSec: 240.6, ja: "最後まで見てくれてありがとう", furigana: "最後まで見てくれてありがとう" },
      { startSec: 240.6, endSec: 246.7, ja: "チャンネル登録といいねもお願いします", furigana: "チャンネル登録といいねもお願いします" },
    ],
    questions: [],
  },
  // narezki-37 (12.6 MB) — N2
  {
    id: "n2-narezki-beastars",
    level: "N2",
    titleRu: "Beastars: истинная сила",
    descriptionRu: "Сцена из аниме Beastars (~1 мин). Тема: ложь, хищники и истинная сила. Книжная лексика: まみれている, 装飾, 邪悪さ. Уровень N2.",
    video: { type: "remote", src: "https://archive.org/download/japanese-trainer-narezki/narezki-37.mp4" },
    subtitles: [
      { startSec: 0, endSec: 2.8, ja: "おいフリー", furigana: "おいフリー" },
      { startSec: 2.8, endSec: 5.9, ja: "うまそうなものを見る目をしたな", furigana: "うまそうなものを見る目をしたな" },
      { startSec: 5.9, endSec: 17.4, ja: "この世は嘘にまみれている", furigana: "この世は嘘にまみれている" },
      { startSec: 17.4, endSec: 21.4, ja: "装飾が上辺ばかりの生き方をしていれば", furigana: "装飾が上辺ばかりの生き方をしていれば" },
      { startSec: 21.4, endSec: 23.4, ja: "必ず取って食われるんだ", furigana: "必ず取って食われるんだ" },
      { startSec: 23.4, endSec: 28, ja: "今度こそ本当の強さを手に入れる", furigana: "今度こそ本当の強さを手に入れる" },
      { startSec: 28, endSec: 29.6, ja: "自分と", furigana: "自分と" },
      { startSec: 30, endSec: 32.6, ja: "肉食獣の邪悪さを信じて", furigana: "肉食獣の邪悪さを信じて" },
      { startSec: 32.6, endSec: 37.5, ja: "おいフリー", furigana: "おいフリー" },
      { startSec: 37.5, endSec: 40.7, ja: "美味そうなものを見る目をしたな", furigana: "美味そうなものを見る目をしたな" },
      { startSec: 40.7, endSec: 54.2, ja: "いいな", furigana: "いいな" },
      { startSec: 54.2, endSec: 57.6, ja: "俺たちが交わした約束を忘れるな", furigana: "俺たちが交わした約束を忘れるな" },
      { startSec: 60, endSec: 62, ja: "ありがとうございました", furigana: "ありがとうございました" },
    ],
    questions: [],
  },
  // narezki-38 (24.1 MB) — N3
  {
    id: "n3-narezki-mha-suneater",
    level: "N3",
    titleRu: "Моя Геройская Академия: Санитер",
    descriptionRu: "Сцена из MHA (~1 мин). Амадзики Тамаки (Санитер) демонстрирует свою индивидуальность «Переявление». Кансайский диалект, аниме-лексика, N3.",
    video: { type: "remote", src: "https://archive.org/download/japanese-trainer-narezki/narezki-38.mp4" },
    subtitles: [
      { startSec: 0, endSec: 1, ja: "おお!", furigana: "おお!" },
      { startSec: 1, endSec: 2, ja: "させへん!", furigana: "させへん!" },
      { startSec: 2, endSec: 3, ja: "わ、待ってよ!", furigana: "わ、待ってよ!" },
      { startSec: 3, endSec: 5, ja: "はくん、沈む!", furigana: "はくん、沈む!" },
      { startSec: 5, endSec: 7, ja: "沈ませ屋さんのファットだいえ!", furigana: "沈ませ屋さんのファットだいえ!" },
      { startSec: 7, endSec: 8, ja: "うっ、バカ!", furigana: "うっ、バカ!" },
      { startSec: 8, endSec: 11, ja: "って、なや!エッジとコースでかぶっとるでお前!", furigana: "って、なや!エッジとコースでかぶっとるでお前!" },
      { startSec: 12, endSec: 14, ja: "なんじゃこのタコ!", furigana: "なんじゃこのタコ!" },
      { startSec: 15, endSec: 17, ja: "ひどい言い方を…", furigana: "ひどい言い方を…" },
      { startSec: 17, endSec: 20, ja: "違うよ先輩!見た目の話、悪口じゃないっせ!", furigana: "違うよ先輩!見た目の話、悪口じゃないっせ!" },
      { startSec: 27, endSec: 29, ja: "タコやマリンかい、我…", furigana: "タコやマリンかい、我…" },
      { startSec: 30, endSec: 31.8, ja: "アサリは便利なんだ", furigana: "アサリは便利なんだ" },
      { startSec: 31.8, endSec: 33.5, ja: "工房に炊ける", furigana: "工房に炊ける" },
      { startSec: 33.5, endSec: 36.8, ja: "だから毎日食べるようにしているんだ", furigana: "だから毎日食べるようにしているんだ" },
      { startSec: 36.8, endSec: 39.5, ja: "UA高校3年ビッグスリー", furigana: "UA高校3年ビッグスリー" },
      { startSec: 39.5, endSec: 40.5, ja: "天敷玉樹", furigana: "天敷玉樹" },
      { startSec: 40.5, endSec: 41.9, ja: "個性再現", furigana: "個性再現" },
      { startSec: 41.9, endSec: 45.6, ja: "食らったものの特徴をその体に再現できる", furigana: "食らったものの特徴をその体に再現できる" },
      { startSec: 45.6, endSec: 47.6, ja: "ちなみに右腕はたこ焼き", furigana: "ちなみに右腕はたこ焼き" },
      { startSec: 47.6, endSec: 49.5, ja: "左腕がアサリのしぐれに", furigana: "左腕がアサリのしぐれに" },
      { startSec: 49.5, endSec: 52.6, ja: "羽の足はフライドチキンを食べて再現してるぞ", furigana: "羽の足はフライドチキンを食べて再現してるぞ" },
      { startSec: 52.6, endSec: 54.6, ja: "羽はいらなかった", furigana: "羽はいらなかった" },
      { startSec: 54.6, endSec: 56.5, ja: "すげえ", furigana: "すげえ" },
      { startSec: 56.5, endSec: 58.3, ja: "てかまたいいとこね", furigana: "てかまたいいとこね" },
      { startSec: 58.3, endSec: 61.5, ja: "うまくできていただろうか", furigana: "うまくできていただろうか" },
      { startSec: 61.5, endSec: 62.2, ja: "すげーっす!", furigana: "すげーっす!" },
      { startSec: 62.5, endSec: 64.8, ja: "迅速で個性の使い方も慣れてて!", furigana: "迅速で個性の使い方も慣れてて!" },
      { startSec: 65.1, endSec: 67.2, ja: "技量ならとうにプロ以上やで", furigana: "技量ならとうにプロ以上やで" },
      { startSec: 67.2, endSec: 68.6, ja: "うちのサンイーターは", furigana: "うちのサンイーターは" },
      { startSec: 68.6, endSec: 70.4, ja: "メンタルは育たんけど", furigana: "メンタルは育たんけど" },
      { startSec: 70.4, endSec: 71.7, ja: "なあ!", furigana: "なあ!" },
      { startSec: 72.4, endSec: 73.5, ja: "エイドサンイーター!", furigana: "エイドサンイーター!" },
      { startSec: 73.9, endSec: 74.9, ja: "かっこいい!", furigana: "かっこいい!" },
    ],
    questions: [],
  },
  // narezki-39 (30.3 MB) — N4
  {
    id: "n4-narezki-phone-business",
    level: "N4",
    titleRu: "Телефонный этикет на работе",
    descriptionRu: "Как отвечать на телефон в японской компании. Внешние и внутренние звонки, деловые фразы: でございます, お世話になっております, お疲れ様です. N4.",
    video: { type: "remote", src: "https://archive.org/download/japanese-trainer-narezki/narezki-39.mp4" },
    subtitles: [
      { startSec: 0, endSec: 2, ja: "音楽", furigana: "音楽" },
      { startSec: 2, endSec: 14.5, ja: "はい、みどりシステムでございます。", furigana: "はい、みどりシステムでございます。" },
      { startSec: 15.4, endSec: 17.2, ja: "ABC障子の伊藤です。", furigana: "ABC障子の伊藤です。" },
      { startSec: 19.5, endSec: 22.8, ja: "みなさんこんにちは。ジャパスタのマナです。", furigana: "みなさんこんにちは。ジャパスタのマナです。" },
      { startSec: 23.6, endSec: 26.8, ja: "それでは、今日も楽しく日本語を勉強しましょう。", furigana: "それでは、今日も楽しく日本語を勉強しましょう。" },
      { startSec: 26.8, endSec: 34.2, ja: "今日は会社で電話に出る方法についてお話をしたいと思います", furigana: "今日は会社で電話に出る方法についてお話をしたいと思います" },
      { startSec: 34.2, endSec: 39.2, ja: "皆さん会社で電話が鳴っているけれど", furigana: "皆さん会社で電話が鳴っているけれど" },
      { startSec: 39.2, endSec: 42.5, ja: "どうやって出たらいいかわからないなぁ", furigana: "どうやって出たらいいかわからないなぁ" },
      { startSec: 42.5, endSec: 47.1, ja: "電話で話すのは緊張するなぁということはありませんか?", furigana: "電話で話すのは緊張するなぁということはありませんか?" },
      { startSec: 48.6, endSec: 52.9, ja: "今日はそんな皆さんの悩みを解決したいと思います", furigana: "今日はそんな皆さんの悩みを解決したいと思います" },
      { startSec: 52.9, endSec: 58.5, ja: "この動画を見ることで2つのことができるようになります", furigana: "この動画を見ることで2つのことができるようになります" },
      { startSec: 58.5, endSec: 64.4, ja: "まず1つ目が会社にかかってくる電話の種類がわかります", furigana: "まず1つ目が会社にかかってくる電話の種類がわかります" },
      { startSec: 64.4, endSec: 67.8, ja: "実は2種類の電話がありますよ", furigana: "実は2種類の電話がありますよ" },
      { startSec: 67.8, endSec: 75.8, ja: "そしてもう1つは会社で電話に出るときに何を言えばいいかわかるようになります", furigana: "そしてもう1つは会社で電話に出るときに何を言えばいいかわかるようになります" },
      { startSec: 77, endSec: 80.1, ja: "それでは今日も楽しく日本語を勉強しましょう", furigana: "それでは今日も楽しく日本語を勉強しましょう" },
      { startSec: 80.1, endSec: 86.2, ja: "ではまず会社にかかってくる電話の種類についてです", furigana: "ではまず会社にかかってくる電話の種類についてです" },
      { startSec: 86.2, endSec: 91, ja: "会社にかかってくる電話は2つの種類があります", furigana: "会社にかかってくる電話は2つの種類があります" },
      { startSec: 91, endSec: 93.9, ja: "皆さん何だと思いますか?", furigana: "皆さん何だと思いますか?" },
      { startSec: 95.5, endSec: 100.4, ja: "1つ目は会社の外の人からかかってくる電話です", furigana: "1つ目は会社の外の人からかかってくる電話です" },
      { startSec: 100.4, endSec: 103.1, ja: "会社の外の人なので", furigana: "会社の外の人なので" },
      { startSec: 103.1, endSec: 107, ja: "取引先やお客様などですね", furigana: "取引先やお客様などですね" },
      { startSec: 107, endSec: 113.5, ja: "そしてもう一つは会社の中の人からかかってくる電話です", furigana: "そしてもう一つは会社の中の人からかかってくる電話です" },
      { startSec: 113.5, endSec: 119.3, ja: "同じ会社の違う部署の人などからかかってくる電話のことです", furigana: "同じ会社の違う部署の人などからかかってくる電話のことです" },
      { startSec: 119.3, endSec: 125, ja: "この会社の外の人からかかってくる電話のことを", furigana: "この会社の外の人からかかってくる電話のことを" },
      { startSec: 125, endSec: 125.9, ja: "外線", furigana: "外線" },
      { startSec: 125.9, endSec: 132.4, ja: "会社の中の人からかかってくる電話のことを", furigana: "会社の中の人からかかってくる電話のことを" },
      { startSec: 132.4, endSec: 133.3, ja: "内線", furigana: "内線" },
      { startSec: 133.3, endSec: 136, ja: "と言います", furigana: "と言います" },
      { startSec: 136, endSec: 141.2, ja: "実は会社の外の人からかかってきた時と", furigana: "実は会社の外の人からかかってきた時と" },
      { startSec: 141.2, endSec: 145, ja: "会社の中の人からかかってきた時で", furigana: "会社の中の人からかかってきた時で" },
      { startSec: 145, endSec: 155.1, ja: "話す内容が少しだけ違いますなので今日はこの2つの種類の電話がかかってきた時に、", furigana: "話す内容が少しだけ違いますなので今日はこの2つの種類の電話がかかってきた時に、" },
      { startSec: 155.3, endSec: 159.2, ja: "それぞれどんなことを言えばいいかお話ししたいと思います。", furigana: "それぞれどんなことを言えばいいかお話ししたいと思います。" },
      { startSec: 160.9, endSec: 166, ja: "では実際に話をする内容の前に、", furigana: "では実際に話をする内容の前に、" },
      { startSec: 166.1, endSec: 170.7, ja: "まず電話の流れについてお話をしたいと思います。", furigana: "まず電話の流れについてお話をしたいと思います。" },
      { startSec: 170.7, endSec: 176.7, ja: "電話の流れは大きく分けると3つのステップがあります", furigana: "電話の流れは大きく分けると3つのステップがあります" },
      { startSec: 176.7, endSec: 181.2, ja: "これは会社の外の人からかかってきた時も", furigana: "これは会社の外の人からかかってきた時も" },
      { startSec: 181.2, endSec: 185, ja: "会社の中の人からかかってきた時も同じです", furigana: "会社の中の人からかかってきた時も同じです" },
      { startSec: 185, endSec: 187.7, ja: "では3つのステップです", furigana: "では3つのステップです" },
      { startSec: 187.7, endSec: 190.6, ja: "1つ目が自分について", furigana: "1つ目が自分について" },
      { startSec: 190.6, endSec: 193.4, ja: "2つ目が挨拶", furigana: "2つ目が挨拶" },
      { startSec: 194.4, endSec: 197.7, ja: "そして3つ目が要件の確認です", furigana: "そして3つ目が要件の確認です" },
      { startSec: 197.7, endSec: 204.9, ja: "要件の確認というのは相手がなぜ電話をしてきたのかを確認することです", furigana: "要件の確認というのは相手がなぜ電話をしてきたのかを確認することです" },
      { startSec: 204.9, endSec: 206.8, ja: "皆さんいいですか?", furigana: "皆さんいいですか?" },
      { startSec: 207.4, endSec: 211.4, ja: "自分について、挨拶、要件の確認", furigana: "自分について、挨拶、要件の確認" },
      { startSec: 211.4, endSec: 217.3, ja: "この3つのステップはとても大事ですからここは覚えておいてください", furigana: "この3つのステップはとても大事ですからここは覚えておいてください" },
      { startSec: 217.3, endSec: 222.2, ja: "それではまず1つ目の自分についてからです", furigana: "それではまず1つ目の自分についてからです" },
      { startSec: 222.2, endSec: 228.6, ja: "では自分について話すときに何と言えばいいか見てみましょう", furigana: "では自分について話すときに何と言えばいいか見てみましょう" },
      { startSec: 228.6, endSec: 233.8, ja: "これは会社の外の人からかかってくるときと", furigana: "これは会社の外の人からかかってくるときと" },
      { startSec: 233.8, endSec: 239.3, ja: "会社の中の人からかかってくるときで話すことが違います", furigana: "会社の中の人からかかってくるときで話すことが違います" },
      { startSec: 239.3, endSec: 243.6, ja: "まず会社の外の人からかかってきたときです", furigana: "まず会社の外の人からかかってきたときです" },
      { startSec: 244.7, endSec: 247.5, ja: "このときまず言うことは", furigana: "このときまず言うことは" },
      { startSec: 247.5, endSec: 253.7, ja: "はいプラス自分の会社の名前プラスでございます", furigana: "はいプラス自分の会社の名前プラスでございます" },
      { startSec: 253.7, endSec: 261.4, ja: "なので例えば私がジャパスタ会社というところで働いているとすると", furigana: "なので例えば私がジャパスタ会社というところで働いているとすると" },
      { startSec: 261.4, endSec: 265, ja: "電話が鳴ったら電話を取って", furigana: "電話が鳴ったら電話を取って" },
      { startSec: 265, endSec: 267.7, ja: "はいジャパスタ会社でございます", furigana: "はいジャパスタ会社でございます" },
      { startSec: 267.7, endSec: 271, ja: "はいジャパスタ会社でございます", furigana: "はいジャパスタ会社でございます" },
      { startSec: 271.8, endSec: 274.2, ja: "こういうのが一番自然です", furigana: "こういうのが一番自然です" },
      { startSec: 274.2, endSec: 279.5, ja: "では次に会社の中の人からかかってきた時です", furigana: "では次に会社の中の人からかかってきた時です" },
      { startSec: 279.5, endSec: 283.1, ja: "この時は2つ言い方があります", furigana: "この時は2つ言い方があります" },
      { startSec: 283.1, endSec: 292.2, ja: "1つ目ははいプラス自分の担当名担当の名前プラスです", furigana: "1つ目ははいプラス自分の担当名担当の名前プラスです" },
      { startSec: 294, endSec: 305.1, ja: "例えば私がシステム開発担当というところで働いているとすると最初に電話を取ってはい、システム開発担当というところで働いているとすると最初に電話を取ってはいシステム開発担当です", furigana: "例えば私がシステム開発担当というところで働いているとすると最初に電話を取ってはい、システム開発担当というところで働いているとすると最初に電話を取ってはいシステム開発担当です" },
      { startSec: 305.1, endSec: 308.7, ja: "はいシステム開発担当です", furigana: "はいシステム開発担当です" },
      { startSec: 308.7, endSec: 313, ja: "こういうふうに担当の名前を言うという言い方があります", furigana: "こういうふうに担当の名前を言うという言い方があります" },
      { startSec: 313, endSec: 316.6, ja: "そしてもう一つの言い方は", furigana: "そしてもう一つの言い方は" },
      { startSec: 316.6, endSec: 323.1, ja: "はいプラス自分の担当名プラス名前プラスです", furigana: "はいプラス自分の担当名プラス名前プラスです" },
      { startSec: 323.1, endSec: 325.9, ja: "ではこれも見てみましょう", furigana: "ではこれも見てみましょう" },
      { startSec: 325.9, endSec: 332.8, ja: "例えば私がシステム開発担当で働くキムさんだったとすると", furigana: "例えば私がシステム開発担当で働くキムさんだったとすると" },
      { startSec: 332.8, endSec: 334.5, ja: "電話を取って", furigana: "電話を取って" },
      { startSec: 334.5, endSec: 337.5, ja: "はいシステム開発担当のキムです", furigana: "はいシステム開発担当のキムです" },
      { startSec: 337.5, endSec: 341.1, ja: "はいシステム開発担当のキムです", furigana: "はいシステム開発担当のキムです" },
      { startSec: 341.1, endSec: 342.9, ja: "みたいな感じですね", furigana: "みたいな感じですね" },
      { startSec: 344.9, endSec: 349.1, ja: "皆さん一つ目の自分についての言い方は分かりましたか", furigana: "皆さん一つ目の自分についての言い方は分かりましたか" },
      { startSec: 349.1, endSec: 352.8, ja: "それでは2つ目の挨拶", furigana: "それでは2つ目の挨拶" },
      { startSec: 352.8, endSec: 358.1, ja: "と3つ目の要件の確認をまとめて見てみましょう", furigana: "と3つ目の要件の確認をまとめて見てみましょう" },
      { startSec: 358.1, endSec: 362.4, ja: "ではまず2つ目の挨拶からです", furigana: "ではまず2つ目の挨拶からです" },
      { startSec: 362.4, endSec: 365.1, ja: "挨拶は簡単です", furigana: "挨拶は簡単です" },
      { startSec: 365.1, endSec: 369.6, ja: "会社の外の人からかかってくる電話の時は", furigana: "会社の外の人からかかってくる電話の時は" },
      { startSec: 369.6, endSec: 372.1, ja: "いつもお世話になっております", furigana: "いつもお世話になっております" },
      { startSec: 372.1, endSec: 374.7, ja: "いつもお世話になっております", furigana: "いつもお世話になっております" },
      { startSec: 374.7, endSec: 376.3, ja: "これです", furigana: "これです" },
      { startSec: 377.5, endSec: 381.1, ja: "では会社の中の人からかかってくる電話です", furigana: "では会社の中の人からかかってくる電話です" },
      { startSec: 381.1, endSec: 384.6, ja: "これはお疲れ様です", furigana: "これはお疲れ様です" },
      { startSec: 384.6, endSec: 386.7, ja: "お疲れ様です", furigana: "お疲れ様です" },
      { startSec: 386.7, endSec: 389.7, ja: "挨拶はこれだけです", furigana: "挨拶はこれだけです" },
      { startSec: 389.7, endSec: 391.8, ja: "皆さん簡単でしたね", furigana: "皆さん簡単でしたね" },
      { startSec: 391.8, endSec: 394.5, ja: "それでは次に進みましょう", furigana: "それでは次に進みましょう" },
      { startSec: 394.5, endSec: 400.1, ja: "それでは最後の要件の確認についてです", furigana: "それでは最後の要件の確認についてです" },
      { startSec: 400.1, endSec: 402.9, ja: "ここで大事なことは", furigana: "ここで大事なことは" },
      { startSec: 403.2, endSec: 408.2, ja: "まずは相手が要件を話すのを待つということです", furigana: "まずは相手が要件を話すのを待つということです" },
      { startSec: 408.2, endSec: 411.9, ja: "挨拶をした後にすぐ", furigana: "挨拶をした後にすぐ" },
      { startSec: 411.9, endSec: 416.1, ja: "要件は何ですか?なぜ電話しましたか?", furigana: "要件は何ですか?なぜ電話しましたか?" },
      { startSec: 416.9, endSec: 419.8, ja: "というように聞くと少し失礼です", furigana: "というように聞くと少し失礼です" },
      { startSec: 419.8, endSec: 425.5, ja: "なのでまずは相手が話すのを少し待ってみましょう", furigana: "なのでまずは相手が話すのを少し待ってみましょう" },
      { startSec: 425.5, endSec: 429.7, ja: "だいたい電話でお互いに挨拶", furigana: "だいたい電話でお互いに挨拶" },
      { startSec: 429.7, endSec: 431.1, ja: "お疲れ様です", furigana: "お疲れ様です" },
      { startSec: 431.1, endSec: 433.2, ja: "いつもお世話になっております", furigana: "いつもお世話になっております" },
      { startSec: 433.2, endSec: 436.3, ja: "といった挨拶が終わって少し待つと", furigana: "といった挨拶が終わって少し待つと" },
      { startSec: 436.3, endSec: 438.6, ja: "電話をしてきた相手から", furigana: "電話をしてきた相手から" },
      { startSec: 438.6, endSec: 442.1, ja: "木村さんはいらっしゃいますか?のように", furigana: "木村さんはいらっしゃいますか?のように" },
      { startSec: 442.1, endSec: 443.9, ja: "要件を言ってくれます", furigana: "要件を言ってくれます" },
      { startSec: 443.9, endSec: 459.8, ja: "なので皆さん要件は何ですか?と聞かずに少し待つというのを覚えておいてください。ではここまで電話の流れについて3つのステップでお話をしてきました。", furigana: "なので皆さん要件は何ですか?と聞かずに少し待つというのを覚えておいてください。ではここまで電話の流れについて3つのステップでお話をしてきました。" },
      { startSec: 461.1, endSec: 465.7, ja: "では今までお話をしたこの3つの流れを使うと", furigana: "では今までお話をしたこの3つの流れを使うと" },
      { startSec: 465.7, endSec: 467.8, ja: "どんな会話になるのか", furigana: "どんな会話になるのか" },
      { startSec: 467.8, endSec: 472.8, ja: "実際に日本の会社ではどんな電話のやり取りがされるのか", furigana: "実際に日本の会社ではどんな電話のやり取りがされるのか" },
      { startSec: 472.8, endSec: 475.2, ja: "というのを見てみたいと思います", furigana: "というのを見てみたいと思います" },
      { startSec: 475.2, endSec: 480.1, ja: "今日は会社の外の人からかかってくる電話と", furigana: "今日は会社の外の人からかかってくる電話と" },
      { startSec: 480.1, endSec: 483.5, ja: "会社の中の人からかかってくる電話の", furigana: "会社の中の人からかかってくる電話の" },
      { startSec: 483.5, endSec: 486.7, ja: "2つの場面でお話をしたいと思います", furigana: "2つの場面でお話をしたいと思います" },
      { startSec: 486.7, endSec: 492.6, ja: "ではまず会社の外の人からかかってくる電話です", furigana: "ではまず会社の外の人からかかってくる電話です" },
      { startSec: 492.6, endSec: 497, ja: "みどりシステムで働くキムさんと", furigana: "みどりシステムで働くキムさんと" },
      { startSec: 497.2, endSec: 501.5, ja: "取引先のABC障子の伊藤さんです", furigana: "取引先のABC障子の伊藤さんです" },
      { startSec: 501.5, endSec: 506.7, ja: "キムさんが仕事をしていると電話がかかってきました", furigana: "キムさんが仕事をしていると電話がかかってきました" },
      { startSec: 506.7, endSec: 511, ja: "では皆さんもキムさんになったつもりで", furigana: "では皆さんもキムさんになったつもりで" },
      { startSec: 511, endSec: 513.9, ja: "声に出して一緒に練習してみてくださいね", furigana: "声に出して一緒に練習してみてくださいね" },
      { startSec: 521.2, endSec: 523.3, ja: "はい、みどりシステムでございます", furigana: "はい、みどりシステムでございます" },
      { startSec: 523.3, endSec: 526.3, ja: "ABC障子の伊藤です", furigana: "ABC障子の伊藤です" },
      { startSec: 526.3, endSec: 528.7, ja: "いつもお世話になっております", furigana: "いつもお世話になっております" },
      { startSec: 528.7, endSec: 531, ja: "お世話になっております", furigana: "お世話になっております" },
      { startSec: 531, endSec: 534.4, ja: "木村さんはいらっしゃいますか?", furigana: "木村さんはいらっしゃいますか?" },
      { startSec: 535.6, endSec: 537, ja: "はい、少々お待ちください", furigana: "はい、少々お待ちください" },
      { startSec: 537, endSec: 544, ja: "皆さんどうですか?うまく言えましたか?", furigana: "皆さんどうですか?うまく言えましたか?" },
      { startSec: 545.4, endSec: 549.8, ja: "では次は会社の中の人からかかってくる電話です", furigana: "では次は会社の中の人からかかってくる電話です" },
      { startSec: 549.8, endSec: 556, ja: "緑システムの開発担当で働くキムさんと", furigana: "緑システムの開発担当で働くキムさんと" },
      { startSec: 556, endSec: 563, ja: "同じく緑システムの営業担当で働く佐藤さんです", furigana: "同じく緑システムの営業担当で働く佐藤さんです" },
      { startSec: 563, endSec: 567.8, ja: "キムさんが仕事をしていると電話がかかってきました", furigana: "キムさんが仕事をしていると電話がかかってきました" },
      { startSec: 569.1, endSec: 574.5, ja: "皆さんもキムさんになったつもりで声に出して練習してみてくださいね", furigana: "皆さんもキムさんになったつもりで声に出して練習してみてくださいね" },
      { startSec: 579.8, endSec: 583.5, ja: "はい、開発担当のキムです", furigana: "はい、開発担当のキムです" },
      { startSec: 583.5, endSec: 586.2, ja: "営業担当の佐藤です", furigana: "営業担当の佐藤です" },
      { startSec: 586.2, endSec: 587.6, ja: "お疲れ様です", furigana: "お疲れ様です" },
      { startSec: 587.6, endSec: 589.3, ja: "お疲れ様です", furigana: "お疲れ様です" },
      { startSec: 589.3, endSec: 592.9, ja: "明日の打ち合わせ資料を送ってほしいんだけど", furigana: "明日の打ち合わせ資料を送ってほしいんだけど" },
      { startSec: 592.9, endSec: 596.5, ja: "はい、この後すぐ送りますね", furigana: "はい、この後すぐ送りますね" },
      { startSec: 600, endSec: 604.4, ja: "皆さんどうですか?うまく言えましたか?", furigana: "皆さんどうですか?うまく言えましたか?" },
      { startSec: 605.9, endSec: 609.1, ja: "今日の動画で何回か練習をして", furigana: "今日の動画で何回か練習をして" },
      { startSec: 609.1, endSec: 612.8, ja: "会社の外の人からかかってくる電話と", furigana: "会社の外の人からかかってくる電話と" },
      { startSec: 612.8, endSec: 616.1, ja: "会社の中の人からかかってくる電話に", furigana: "会社の中の人からかかってくる電話に" },
      { startSec: 616.1, endSec: 620.2, ja: "ぜひ自信を持って対応できるようになってくださいね", furigana: "ぜひ自信を持って対応できるようになってくださいね" },
      { startSec: 620.2, endSec: 625, ja: "最後まで動画を見ていただきありがとうございました", furigana: "最後まで動画を見ていただきありがとうございました" },
      { startSec: 625, endSec: 629.3, ja: "役に立ったらぜひいいねをお願いします", furigana: "役に立ったらぜひいいねをお願いします" },
      { startSec: 629.3, endSec: 632.8, ja: "ぜひコメントも書いてくださいね", furigana: "ぜひコメントも書いてくださいね" },
      { startSec: 632.8, endSec: 638.6, ja: "これからも皆さんの日本語の勉強に役に立つ動画を作っていくので", furigana: "これからも皆さんの日本語の勉強に役に立つ動画を作っていくので" },
      { startSec: 638.6, endSec: 641.8, ja: "ぜひチャンネル登録もよろしくお願いします", furigana: "ぜひチャンネル登録もよろしくお願いします" },
      { startSec: 641.8, endSec: 645.8, ja: "それではまた次の動画でお会いしましょう", furigana: "それではまた次の動画でお会いしましょう" },
      { startSec: 645.8, endSec: 647.1, ja: "バイバイ", furigana: "バイバイ" },
    ],
    questions: [],
  },
  // narezki-40 (34.7 MB) — N2
  {
    id: "n2-narezki-kny-uppermoons",
    level: "N2",
    titleRu: "Клинок: собрание Высших Лун",
    descriptionRu: "Сцена из «Клинок, рассекающий демонов» (~3 мин). Собрание Высших Лун у Музана. Архаичная и формальная речь, N2.",
    video: { type: "remote", src: "https://archive.org/download/japanese-trainer-narezki/narezki-40.mp4" },
    subtitles: [
      { startSec: 0, endSec: 15.8, ja: "第1話 イクウカン", furigana: "第1話 イクウカン" },
      { startSec: 15.8, endSec: 15.9, ja: "イクウカン", furigana: "イクウカン" },
      { startSec: 15.9, endSec: 18.6, ja: "ここに呼ばれたということは", furigana: "ここに呼ばれたということは" },
      { startSec: 18.6, endSec: 22, ja: "上限が鬼狩りにやられた", furigana: "上限が鬼狩りにやられた" },
      { startSec: 22, endSec: 28.7, ja: "これはこれは赤だぞ", furigana: "これはこれは赤だぞ" },
      { startSec: 28.7, endSec: 30.8, ja: "いいや早お元気そう", furigana: "いいや早お元気そう" },
      { startSec: 30.8, endSec: 33.4, ja: "恐ろしい", furigana: "恐ろしい" },
      { startSec: 33.4, endSec: 35.1, ja: "13年ぶり", furigana: "13年ぶり" },
      { startSec: 35.1, endSec: 37.6, ja: "ムザン様はいらっしゃらないのか", furigana: "ムザン様はいらっしゃらないのか" },
      { startSec: 37.6, endSec: 38.1, ja: "いません", furigana: "いません" },
      { startSec: 38.1, endSec: 40.1, ja: "どこだ", furigana: "どこだ" },
      { startSec: 40.1, endSec: 41.7, ja: "赤座殿", furigana: "赤座殿" },
      { startSec: 41.7, endSec: 43.4, ja: "ないのかい", furigana: "ないのかい" },
      { startSec: 43.4, endSec: 45.3, ja: "大切な仲", furigana: "大切な仲" },
      { startSec: 45.3, endSec: 47.9, ja: "やあやあ", furigana: "やあやあ" },
      { startSec: 47.9, endSec: 48.7, ja: "どかせ", furigana: "どかせ" },
      { startSec: 48.7, endSec: 49.6, ja: "ん?", furigana: "ん?" },
      { startSec: 50, endSec: 51, ja: "どかせ", furigana: "どかせ" },
      { startSec: 51, endSec: 54.7, ja: "いい拳だ", furigana: "いい拳だ" },
      { startSec: 54.7, endSec: 59.3, ja: "ずっとそこにいらっしゃいますよ", furigana: "ずっとそこにいらっしゃいますよ" },
      { startSec: 59.3, endSec: 60.1, ja: "ここにいる", furigana: "ここにいる" },
      { startSec: 60.1, endSec: 62.7, ja: "様がお見え", furigana: "様がお見え" },
      { startSec: 62.7, endSec: 66.8, ja: "かけた", furigana: "かけた" },
      { startSec: 66.8, endSec: 68.9, ja: "すいませんぬ", furigana: "すいませんぬ" },
      { startSec: 68.9, endSec: 70.7, ja: "送り出しましょうか", furigana: "送り出しましょうか" },
      { startSec: 70.7, endSec: 73.9, ja: "貴様の目玉なしでまといだった", furigana: "貴様の目玉なしでまといだった" },
      { startSec: 73.9, endSec: 76.5, ja: "だから牛太郎が戦っていればか", furigana: "だから牛太郎が戦っていればか" },
      { startSec: 76.5, endSec: 78.8, ja: "もうどうでもいい", furigana: "もうどうでもいい" },
      { startSec: 78.8, endSec: 79.6, ja: "ならぬ", furigana: "ならぬ" },
      { startSec: 79.6, endSec: 81.4, ja: "いい", furigana: "いい" },
      { startSec: 81.4, endSec: 88.1, ja: "俺があなた様の期待に応えなかった時があったでしょうか", furigana: "俺があなた様の期待に応えなかった時があったでしょうか" },
      { startSec: 88.1, endSec: 89.5, ja: "っていない", furigana: "っていない" },
      { startSec: 89.5, endSec: 101.9, ja: "どうした理由がわからなくなってきて気に入らない悪意だからな私はつかむ", furigana: "どうした理由がわからなくなってきて気に入らない悪意だからな私はつかむ" },
      { startSec: 101.9, endSec: 103.7, ja: "変化だ", furigana: "変化だ" },
      { startSec: 103.7, endSec: 106.6, ja: "今日の変化の場合劣化だ", furigana: "今日の変化の場合劣化だ" },
      { startSec: 106.6, endSec: 109.3, ja: "私が好きなものは不変こと", furigana: "私が好きなものは不変こと" },
      { startSec: 109.3, endSec: 112.2, ja: "頭に", furigana: "頭に" },
      { startSec: 112.2, endSec: 115.1, ja: "13年ぶりに上限を", furigana: "13年ぶりに上限を" },
      { startSec: 115.1, endSec: 117.4, ja: "まだ確定していない情報", furigana: "まだ確定していない情報" },
      { startSec: 117.4, endSec: 121.2, ja: "とともにそこへ向かえ", furigana: "とともにそこへ向かえ" },
      { startSec: 121.2, endSec: 123, ja: "この法とは何のことだ", furigana: "この法とは何のことだ" },
      { startSec: 123, endSec: 127.1, ja: "この通りと言っている", furigana: "この通りと言っている" },
      { startSec: 127.1, endSec: 129.6, ja: "赤さ", furigana: "赤さ" },
      { startSec: 129.6, endSec: 130.2, ja: "次", furigana: "次" },
      { startSec: 130.2, endSec: 133.5, ja: "しない", furigana: "しない" },
      { startSec: 133.5, endSec: 135, ja: "乱れ", furigana: "乱れ" },
      { startSec: 135, endSec: 137.4, ja: "憂いているのだ", furigana: "憂いているのだ" },
      { startSec: 137.4, endSec: 138.1, ja: "なるほどね", furigana: "なるほどね" },
      { startSec: 138.1, endSec: 142.5, ja: "この決戦を申し込む子は我らに勝てないが", furigana: "この決戦を申し込む子は我らに勝てないが" },
      { startSec: 142.5, endSec: 143.7, ja: "したのだから", furigana: "したのだから" },
      { startSec: 143.7, endSec: 145.7, ja: "彼も内心やってくれ", furigana: "彼も内心やってくれ" },
      { startSec: 145.7, endSec: 148.8, ja: "こういう風にして仲良くなって", furigana: "こういう風にして仲良くなって" },
      { startSec: 148.8, endSec: 149.4, ja: "赤座", furigana: "赤座" },
      { startSec: 149.4, endSec: 152.7, ja: "私の", furigana: "私の" },
      { startSec: 152.7, endSec: 155.8, ja: "分かった", furigana: "分かった" },
      { startSec: 155.8, endSec: 156.7, ja: "必ず", furigana: "必ず" },
      { startSec: 156.7, endSec: 160.5, ja: "そうか", furigana: "そうか" },
      { startSec: 160.5, endSec: 162.3, ja: "ことだ", furigana: "ことだ" },
      { startSec: 162.3, endSec: 164.3, ja: "さよなら", furigana: "さよなら" },
      { startSec: 164.3, endSec: 165.4, ja: "黒死亡殿", furigana: "黒死亡殿" },
      { startSec: 165.4, endSec: 169.1, ja: "赤座殿", furigana: "赤座殿" },
      { startSec: 169.1, endSec: 172.1, ja: "私とハンテング同じ場", furigana: "私とハンテング同じ場" },
      { startSec: 172.1, endSec: 176.9, ja: "勝ったらこの後俺と", furigana: "勝ったらこの後俺と" },
      { startSec: 176.9, endSec: 179.7, ja: "誰も彼も連れないな", furigana: "誰も彼も連れないな" },
      { startSec: 179.7, endSec: 181.1, ja: "信者の方がお見え", furigana: "信者の方がお見え" },
      { startSec: 181.1, endSec: 182.1, ja: "言ってもらっておくれ", furigana: "言ってもらっておくれ" },
    ],
    questions: [],
  },
  // narezki-41 (82.6 MB) — N5
  {
    id: "n5-narezki-restaurant",
    level: "N5",
    titleRu: "В ресторане: заказ еды",
    descriptionRu: "Сцена в ресторане (~5 мин). Базовые фразы: 何名様ですか?, これをください, 美味しいですか?, 乾杯!. Счётчики людей и порций. N5.",
    video: { type: "remote", src: "https://archive.org/download/japanese-trainer-narezki/narezki-41.mp4" },
    subtitles: [
      { startSec: 0, endSec: 4.3, ja: "音楽", furigana: "音楽" },
      { startSec: 4.3, endSec: 11, ja: "音楽", furigana: "音楽" },
      { startSec: 11, endSec: 15.2, ja: "音楽", furigana: "音楽" },
      { startSec: 15.2, endSec: 29.2, ja: "音楽", furigana: "音楽" },
      { startSec: 29.2, endSec: 30.4, ja: "何名様ですか?", furigana: "何名様ですか?" },
      { startSec: 31.5, endSec: 32.3, ja: "2人です", furigana: "2人です" },
      { startSec: 32.3, endSec: 34.2, ja: "こちらどうぞ", furigana: "こちらどうぞ" },
      { startSec: 34.9, endSec: 50.9, ja: "これはチキンですか?", furigana: "これはチキンですか?" },
      { startSec: 51.5, endSec: 53, ja: "いえ、チキンじゃありません", furigana: "いえ、チキンじゃありません" },
      { startSec: 53, endSec: 54.4, ja: "豚肉です", furigana: "豚肉です" },
      { startSec: 54.4, endSec: 56.2, ja: "豚肉、ポーク?", furigana: "豚肉、ポーク?" },
      { startSec: 56.7, endSec: 57.8, ja: "はい、ポークです", furigana: "はい、ポークです" },
      { startSec: 57.8, endSec: 59.8, ja: "じゃあこれは?", furigana: "じゃあこれは?" },
      { startSec: 59.8, endSec: 62.8, ja: "それは鶏肉です。チキンです。", furigana: "それは鶏肉です。チキンです。" },
      { startSec: 62.8, endSec: 64.8, ja: "これをください。", furigana: "これをください。" },
      { startSec: 64.8, endSec: 66.8, ja: "はい。", furigana: "はい。" },
      { startSec: 66.8, endSec: 68.8, ja: "クエさん、ビールは?", furigana: "クエさん、ビールは?" },
      { startSec: 68.8, endSec: 70.8, ja: "ビール?", furigana: "ビール?" },
      { startSec: 70.8, endSec: 82.3, ja: "OK。これは寿司ですか?はい、寿司です。じゃあこれは?天ぷらです。美味し司ですか?はい、寿司ですじゃあこれは?天ぷらです美味しいですか?美味しいです", furigana: "OK。これは寿司ですか?はい、寿司です。じゃあこれは?天ぷらです。美味し司ですか?はい、寿司ですじゃあこれは?天ぷらです美味しいですか?美味しいです" },
      { startSec: 82.3, endSec: 85.5, ja: "これとこれをください", furigana: "これとこれをください" },
      { startSec: 85.5, endSec: 89.3, ja: "はい、そばセットがお一つ、寿司セットがお一つですね", furigana: "はい、そばセットがお一つ、寿司セットがお一つですね" },
      { startSec: 89.3, endSec: 92.5, ja: "はい、それからビールを二つお願いします", furigana: "はい、それからビールを二つお願いします" },
      { startSec: 92.5, endSec: 94.8, ja: "はい、ビールがお二つですね", furigana: "はい、ビールがお二つですね" },
      { startSec: 94.8, endSec: 96.5, ja: "はい、少々お待ちくださいませ", furigana: "はい、少々お待ちくださいませ" },
      { startSec: 96.5, endSec: 96.8, ja: "はい", furigana: "はい" },
      { startSec: 96.8, endSec: 101.5, ja: "おー", furigana: "おー" },
      { startSec: 101.5, endSec: 103.8, ja: "乾杯", furigana: "乾杯" },
      { startSec: 103.8, endSec: 104.4, ja: "え?", furigana: "え?" },
      { startSec: 105.3, endSec: 105.9, ja: "乾杯", furigana: "乾杯" },
      { startSec: 105.9, endSec: 106.6, ja: "あ", furigana: "あ" },
      { startSec: 106.6, endSec: 108.5, ja: "乾杯", furigana: "乾杯" },
      { startSec: 108.5, endSec: 117.4, ja: "いただきます", furigana: "いただきます" },
      { startSec: 117.4, endSec: 118.6, ja: "いただきます", furigana: "いただきます" },
      { startSec: 126.8, endSec: 134.2, ja: "あ、グウェンさん", furigana: "あ、グウェンさん" },
      { startSec: 134.2, endSec: 137.1, ja: "あ", furigana: "あ" },
      { startSec: 137.1, endSec: 153.2, ja: "おいしいですか?おいしいですはるかさん、そばは?美味しいです。", furigana: "おいしいですか?おいしいですはるかさん、そばは?美味しいです。" },
      { startSec: 160.3, endSec: 161.5, ja: "これをください。", furigana: "これをください。" },
      { startSec: 168.1, endSec: 169.2, ja: "美味しいです。", furigana: "美味しいです。" },
      { startSec: 169.2, endSec: 169.2, ja: "美味しいです。", furigana: "美味しいです。" },
      { startSec: 175.8, endSec: 177, ja: "何名様ですか?", furigana: "何名様ですか?" },
      { startSec: 177.4, endSec: 178.7, ja: "一人です", furigana: "一人です" },
      { startSec: 178.7, endSec: 184.4, ja: "何名様ですか", furigana: "何名様ですか" },
      { startSec: 184.4, endSec: 191.2, ja: "これをください", furigana: "これをください" },
      { startSec: 191.2, endSec: 192.2, ja: "はい", furigana: "はい" },
      { startSec: 192.2, endSec: 197.8, ja: "はい", furigana: "はい" },
      { startSec: 197.8, endSec: 202.4, ja: "美味しいですか", furigana: "美味しいですか" },
      { startSec: 202.4, endSec: 203.7, ja: "美味しいです", furigana: "美味しいです" },
      { startSec: 203.7, endSec: 207.5, ja: "おいしいですか", furigana: "おいしいですか" },
      { startSec: 207.5, endSec: 214.5, ja: "音楽", furigana: "音楽" },
      { startSec: 214.5, endSec: 243.8, ja: "1人 2人 3人 4人 5人1つ 2つ 3つ 4つ 5つ", furigana: "1人 2人 3人 4人 5人1つ 2つ 3つ 4つ 5つ" },
      { startSec: 243.8, endSec: 259, ja: "牛肉 豚肉 鶏肉 魚", furigana: "牛肉 豚肉 鶏肉 魚" },
      { startSec: 273.8, endSec: 303.7, ja: "ご視聴ありがとうございました", furigana: "ご視聴ありがとうございました" },
      { startSec: 303.8, endSec: 333.7, ja: "ご視聴ありがとうございました", furigana: "ご視聴ありがとうございました" },
    ],
    questions: [],
  },
  // narezki-42 (87.7 MB) — N2 Vocaloid song
  {
    id: "n2-narezki-advanced-talk",
    level: "N2",
    titleRu: "Песня",
    descriptionRu:
      "Песня (~4 мин). Тема: быстротечность, внутренняя красота, поиск себя. Поэтический язык, книжные формы ～てゆく, ～ぬ, やむを得ず. Уровень N2.",
    video: { type: "remote", src: "https://archive.org/download/japanese-trainer-narezki/narezki-42.mp4" },
    subtitles: [
      { startSec: 0, endSec: 16, ja: "作詞・作曲・編曲 初音ミク", furigana: "さくし・さっきょく・へんきょく はつね ミク" },
      { startSec: 16, endSec: 23.3, ja: "枯れてゆく 今この瞬間も", furigana: "かれてゆく いま この しゅんかん も" },
      { startSec: 23.3, endSec: 25.3, ja: "咲いている", furigana: "さいている" },
      { startSec: 25.3, endSec: 31, ja: "全ては溶けてゆく", furigana: "すべて は とけてゆく" },
      { startSec: 31, endSec: 35.2, ja: "何ができるのだろうか", furigana: "なに が できる の だろう か" },
      { startSec: 35.2, endSec: 38.4, ja: "誰を生きようかな", furigana: "だれ を いきよう かな" },
      { startSec: 38.4, endSec: 42.8, ja: "みんな儚い", furigana: "みんな はかない" },
      { startSec: 42.8, endSec: 47.7, ja: "みんな尊い", furigana: "みんな とうとい" },
      { startSec: 47.7, endSec: 51.9, ja: "シワシワにしおれた花束", furigana: "シワシワ に しおれた はなたば" },
      { startSec: 51.9, endSec: 55.8, ja: "小脇に輝いて", furigana: "こわき に かがやいて" },
      { startSec: 55.8, endSec: 65, ja: "永遠に変わらぬ輝き探してた", furigana: "えいえん に かわらぬ かがやき さがしてた" },
      { startSec: 65, endSec: 72, ja: "僕らを信じてみた 僕らを感じてた", furigana: "ぼくら を しんじてみた ぼくら を かんじてた" },
      { startSec: 72, endSec: 79.4, ja: "咲かせに行くよ 内なる花を", furigana: "さかせ に いくよ うちなる はな を" },
      { startSec: 90.5, endSec: 101.4, ja: "さりげなく思いを込めてみる", furigana: "さりげなく おもい を こめてみる" },
      { startSec: 101.4, endSec: 109.1, ja: "やむを得ず祈りを込めてゆく", furigana: "やむをえず いのり を こめてゆく" },
      { startSec: 109.1, endSec: 113.3, ja: "いつまで迷うんだろうか", furigana: "いつまで まようん だろう か" },
      { startSec: 113.3, endSec: 116.8, ja: "いつかはわかるよな", furigana: "いつか は わかるよな" },
      { startSec: 116.8, endSec: 124.9, ja: "誰もが一人 全ては一つ", furigana: "だれも が ひとり すべて は ひとつ" },
      { startSec: 124.9, endSec: 132, ja: "色々な姿や形に惑わされるけど", furigana: "いろいろ な すがた や かたち に まどわされる けど" },
      { startSec: 132, endSec: 140.3, ja: "いつの日か全てが可愛く思えるさ", furigana: "いつのひか すべて が かわいく おもえる さ" },
      { startSec: 140.3, endSec: 144.4, ja: "私は何になろうか", furigana: "わたし は なに に なろう か" },
      { startSec: 144.4, endSec: 147.8, ja: "どんな色がいいかな", furigana: "どんな いろ が いい かな" },
      { startSec: 147.8, endSec: 156.3, ja: "探しに行くよ 内なる花を", furigana: "さがし に いくよ うちなる はな を" },
    ],
    questions: [
      { id: "n2-song-q01", kind: "kanji_translate", atSec: 18, promptRu: "Переведите「瞬間」.", kanji: "瞬間", acceptedRu: ["мгновение", "момент", "миг"] },
      { id: "n2-song-q02", kind: "listening_mcq", atSec: 28, promptRu: "Что происходит со «всем» (全て) в песне?", optionsRu: ["Всё расцветает", "Всё тает/растворяется", "Всё останавливается", "Всё рождается заново"], correctIndex: 1, explanationRu: "全ては溶けてゆく — «Всё тает / растворяется». てゆく = постепенный процесс." },
      { id: "n2-song-q03", kind: "kanji_translate", atSec: 40, promptRu: "Переведите「儚い」.", kanji: "儚い", acceptedRu: ["мимолётный", "эфемерный", "быстротечный", "хрупкий"] },
      { id: "n2-song-q04", kind: "listening_mcq", atSec: 45, promptRu: "Что значит「尊い」?", optionsRu: ["Печальный", "Драгоценный / возвышенный", "Далёкий", "Забытый"], correctIndex: 1, explanationRu: "尊い (とうとい) — «драгоценный», «возвышенный», «священный». В паре с 儚い создаёт контраст: всё мимолётно, но всё прекрасно." },
      { id: "n2-song-q05", kind: "word_order", atSec: 60, promptRu: "Соберите: «Вечно неизменное сияние»", words: ["輝き", "永遠に", "変わらぬ"], correctOrder: [1, 2, 0], explanationRu: "永遠に変わらぬ輝き — «вечно неизменное сияние». 変わらぬ = 変わらない (книжная форма)." },
      { id: "n2-song-q06", kind: "listening_mcq", atSec: 76, promptRu: "Что герой хочет «раскрыть»?", optionsRu: ["Внешнюю красоту", "Внутренний цветок", "Старый дневник", "Забытую мелодию"], correctIndex: 1, explanationRu: "咲かせに行くよ 内なる花を — «Пойду раскрывать внутренний цветок». 内なる = 内の (книжн.)." },
      { id: "n2-song-q07", kind: "kanji_translate", atSec: 105, promptRu: "Переведите「やむを得ず」.", kanji: "やむを得ず", acceptedRu: ["вынужденно", "неизбежно", "поневоле"] },
      { id: "n2-song-q08", kind: "listening_mcq", atSec: 130, promptRu: "Что значит「惑わされる」?", optionsRu: ["Быть обманутым / сбитым с толку", "Быть обрадованным", "Быть напуганным", "Быть забытым"], correctIndex: 0, explanationRu: "惑わされる — пассив от 惑わす (вводить в заблуждение). 姿や形に惑わされる — «быть сбитым с толку внешностью и формой»." },
    ],
    grammarNotes: [
      {
        titleJa: "〜てゆく",
        titleRu: "Постепенный процесс ～てゆく (книжн.)",
        level: "N2",
        structure: "Vて + ゆく",
        explanationRu: "Книжная/поэтическая форма ～ていく. Показывает постепенное изменение, удаление или развитие. В песнях и литературе ゆく звучит более возвышенно, чем いく.",
        examples: [
          { ja: "枯れてゆく花。", furigana: "かれてゆく はな。", ru: "Увядающий цветок." },
          { ja: "時代は変わってゆく。", furigana: "じだい は かわってゆく。", ru: "Эпоха постепенно меняется." },
          { ja: "思い出は薄れてゆく。", furigana: "おもいで は うすれてゆく。", ru: "Воспоминания постепенно тускнеют." },
        ],
        tip: "てゆく = ていく (книжно). JLPT: различайте ていく (пр. изменение) и てくる (пр. приближение/начало).",
      },
      {
        titleJa: "〜ぬ（＝ない）",
        titleRu: "Книжное отрицание ～ぬ",
        level: "N2",
        structure: "Vない形 → Vぬ (заменяем ない на ぬ)",
        explanationRu: "Архаичная/книжная форма отрицания. 変わらぬ = 変わらない. В песнях, поэзии и официальной речи.",
        examples: [
          { ja: "変わらぬ友情。", furigana: "かわらぬ ゆうじょう。", ru: "Неизменная дружба." },
          { ja: "知らぬ間に。", furigana: "しらぬ ま に。", ru: "Незаметно (букв. 'в неведомый момент')." },
          { ja: "思わぬ結果。", furigana: "おもわぬ けっか。", ru: "Неожиданный результат." },
        ],
        tip: "ぬ = ない (книжн.). На JLPT: 思わぬ = 思わない, 変わらぬ = 変わらない. Часто в устойчивых выражениях.",
      },
      {
        titleJa: "やむを得ず",
        titleRu: "Вынужденно / поневоле やむを得ず",
        level: "N2",
        structure: "やむを得ず + Verb",
        explanationRu: "Означает «вынужденно», «неизбежно», «поневоле». От やむを得ない — «неизбежный». Формальный стиль.",
        examples: [
          { ja: "やむを得ず欠席した。", furigana: "やむをえず けっせきした。", ru: "Вынужденно отсутствовал." },
          { ja: "やむを得ない事情があった。", furigana: "やむをえない じじょう が あった。", ru: "Были неизбежные обстоятельства." },
          { ja: "やむを得ず計画を変更した。", furigana: "やむをえず けいかく を へんこうした。", ru: "Поневоле изменил план." },
        ],
      },
      {
        titleJa: "内なる〜",
        titleRu: "Внутренний ～ 内なる (книжн.)",
        level: "N2",
        structure: "内なる + Noun",
        explanationRu: "Книжная форма 内の — «внутренний». Используется в поэзии, песнях и философских текстах. 内なる花 — «внутренний цветок» (скрытый потенциал).",
        examples: [
          { ja: "内なる声に従え。", furigana: "うちなる こえ に したがえ。", ru: "Следуй внутреннему голосу." },
          { ja: "内なる力を信じる。", furigana: "うちなる ちから を しんじる。", ru: "Верить во внутреннюю силу." },
          { ja: "内なる平和を求める。", furigana: "うちなる へいわ を もとめる。", ru: "Искать внутренний покой." },
        ],
        tip: "Xなる = XのY (книжно). 内なる = 内の, 我がなる国 = 我が国 и т.д.",
      },
    ],
  },
  // narezki-29 (13.9 MB) — N2
  {
    id: "n2-narezki-long-listening",
    level: "N2",
    titleRu: "Аниме-сцена: решимость и судьба",
    descriptionRu: "Аниме-сцена (~2 мин). Диалог о решимости, судьбе и ответственности. Сложная лексика N2: 覚悟, 運命, ～ざるを得ない, ～にほかならない.",
    video: { type: "remote", src: "https://archive.org/download/japanese-trainer-narezki/narezki-29.mp4" },
    subtitles: [
      { startSec: 0, endSec: 4, ja: "お前に覚悟はあるのか", furigana: "おまえ に かくご は ある の か" },
      { startSec: 4, endSec: 8, ja: "覚悟なら…とっくにできている", furigana: "かくご なら…とっくに できている" },
      { startSec: 8, endSec: 13, ja: "この戦いは避けられぬ運命だ", furigana: "この たたかい は さけられぬ うんめい だ" },
      { startSec: 13, endSec: 18, ja: "お前がここに来たのは偶然ではない", furigana: "おまえ が ここ に きた の は ぐうぜん で は ない" },
      { startSec: 18, endSec: 23, ja: "全てを背負う義務がある", furigana: "すべて を せおう ぎむ が ある" },
      { startSec: 23, endSec: 28, ja: "たとえ一人でも戦わざるを得ない", furigana: "たとえ ひとり でも たたかわざるをえない" },
      { startSec: 28, endSec: 34, ja: "それが強さにほかならない", furigana: "それ が つよさ に ほかならない" },
      { startSec: 34, endSec: 40, ja: "俺は逃げない", furigana: "おれ は にげない" },
      { startSec: 40, endSec: 48, ja: "お前のその目…本気だな", furigana: "おまえ の その め…ほんき だ な" },
      { startSec: 48, endSec: 55, ja: "ならば容赦はしない", furigana: "ならば ようしゃ は しない" },
      { startSec: 55, endSec: 62, ja: "来い。決着をつけよう", furigana: "こい。けっちゃく を つけよう" },
    ],
    questions: [
      { id: "n2-resolve-q01", kind: "kanji_translate", atSec: 3, promptRu: "Переведите「覚悟」.", kanji: "覚悟", acceptedRu: ["решимость", "готовность", "подготовленность"] },
      { id: "n2-resolve-q02", kind: "listening_mcq", atSec: 15, promptRu: "Почему герой пришёл сюда?", optionsRu: ["По случайности", "Это судьба, не случайность", "Его позвали друзья", "Он заблудился"], correctIndex: 1, explanationRu: "お前がここに来たのは偶然ではない — 'Ты пришёл сюда не случайно'. Это указание на судьбу (運命)." },
      { id: "n2-resolve-q03", kind: "kanji_translate", atSec: 25, promptRu: "Переведите「義務」.", kanji: "義務", acceptedRu: ["обязанность", "долг", "обязательство"] },
      { id: "n2-resolve-q04", kind: "word_order", atSec: 28, promptRu: "Соберите: 'Даже в одиночку приходится сражаться'", words: ["戦わざるを得ない", "たとえ", "一人でも"], correctOrder: [1, 2, 0], explanationRu: "たとえ一人でも戦わざるを得ない. ～ざるを得ない = 'вынужден, не могу не' (N2)." },
      { id: "n2-resolve-q05", kind: "listening_mcq", atSec: 33, promptRu: "Что значит「～にほかならない」?", optionsRu: ["Не что иное, как…", "Возможно, что…", "Ни в коем случае не…", "Похоже на…"], correctIndex: 0, explanationRu: "～にほかならない = 'не что иное, как…', 'именно'. それが強さにほかならない = 'Это и есть настоящая сила'." },
      { id: "n2-resolve-q06", kind: "kanji_translate", atSec: 50, promptRu: "Переведите「容赦」.", kanji: "容赦", acceptedRu: ["пощада", "снисхождение", "прощение"] },
      { id: "n2-resolve-q07", kind: "listening_mcq", atSec: 58, promptRu: "Что значит「決着をつける」?", optionsRu: ["Принять решение", "Расстаться с кем-то", "Поставить точку / завершить дело", "Начать сначала"], correctIndex: 2, explanationRu: "決着をつける = 'расставить все точки', 'довести до конца'. Классическая фраза в аниме-поединках." },
    ],
    grammarNotes: [
      {
        titleJa: "～ざるを得ない",
        titleRu: "Вынужден / не могу не ～ざるを得ない",
        level: "N2",
        structure: "Vない形 → Vざる + を得ない (する→せざるを得ない)",
        explanationRu: "Означает 'не иметь другого выбора кроме как...', 'быть вынужденным'. Формальный стиль. ない→ざる (книжное отрицание) + を得ない (невозможно).",
        examples: [
          { ja: "締め切りがあるので、徹夜せざるを得ない。", furigana: "しめきり が ある ので、てつや せざるをえない。", ru: "Есть дедлайн, поэтому приходится не спать всю ночь." },
          { ja: "証拠がある以上、認めざるを得ない。", furigana: "しょうこ が ある いじょう、みとめざるをえない。", ru: "Раз есть доказательства, вынужден признать." },
          { ja: "事情を考えると、参加せざるを得ない。", furigana: "じじょう を かんがえる と、さんか せざるをえない。", ru: "Учитывая обстоятельства, приходится участвовать." },
        ],
        tip: "する→せざるを得ない (исключение!). Остальные: 行く→行かざるを得ない, 食べる→食べざるを得ない.",
      },
      {
        titleJa: "～にほかならない",
        titleRu: "Не что иное, как ～にほかならない",
        level: "N2",
        structure: "Noun + にほかならない / Sentence + からにほかならない",
        explanationRu: "Означает 'именно это', 'не что иное, как'. Подчёркивает единственную причину или суть чего-то. Книжный/формальный стиль.",
        examples: [
          { ja: "彼の成功は努力の結果にほかならない。", furigana: "かれ の せいこう は どりょく の けっか に ほかならない。", ru: "Его успех — не что иное, как результат усилий." },
          { ja: "これは彼女の才能にほかならない。", furigana: "これ は かのじょ の さいのう に ほかならない。", ru: "Это не что иное, как её талант." },
          { ja: "遅刻したのは寝坊したからにほかならない。", furigana: "ちこく した の は ねぼう した から に ほかならない。", ru: "Опоздал я исключительно потому, что проспал." },
        ],
      },
      {
        titleJa: "覚悟（かくご）",
        titleRu: "Решимость / готовность 覚悟",
        level: "N2",
        structure: "覚悟する / 覚悟がある / 覚悟を決める",
        explanationRu: "'Решимость', 'внутренняя готовность к трудностям'. Часто в аниме и формальной речи. 覚悟を決める = 'принять решение' (с пониманием последствий).",
        examples: [
          { ja: "覚悟を決めて出発した。", furigana: "かくご を きめて しゅっぱつした。", ru: "Решился и отправился в путь." },
          { ja: "最悪の事態を覚悟している。", furigana: "さいあく の じたい を かくご している。", ru: "Я готов к худшему." },
          { ja: "覚悟はできているか？", furigana: "かくご は できている か？", ru: "Ты готов? (Ты осознаёшь последствия?)" },
        ],
      },
    ],
  },
];
