import type { GrammarNote, Lesson, LessonQuestion } from "./content";

const N4_NEW: Lesson[] = [
  // ═══════════════════════════════════════════════════════════════
  //  narezki-15 — N4 — Губка Боб на японском (~5 min)
  // ═══════════════════════════════════════════════════════════════
  {
    id: "n4-spongebob",
    level: "N4",
    titleRu: "Губка Боб на японском :D",
    descriptionRu:
      "Спанчбоб решает никогда не выходить из дома после травмы. Лексика: 治療, 完了, 大丈夫, 危険, 絶対. Грамматика: ～ちゃいけない, ～かもしれない, ～たり.",
    video: { type: "remote", src: "https://archive.org/download/japanese-trainer-narezki/narezki-15.mp4" },
    subtitles: [
      { startSec: 0, endSec: 3.06, ja: "そっちのね、お尻で着きするのよ!", furigana: "そっちのね、お尻で着きするのよ!" },
      { startSec: 3.54, endSec: 5.28, ja: "ぐっしゃーになるからね!", furigana: "ぐっしゃーになるからね!" },
      { startSec: 7.3, endSec: 8.3, ja: "こんな感じ?", furigana: "こんな感じ?" },
      { startSec: 8.7, endSec: 10.24, ja: "もう一度抜いちゃいよ!", furigana: "もう一度抜いちゃいよ!" },
      { startSec: 10.24, endSec: 11.7, ja: "あんたはどっか行ってたよ!", furigana: "あんたはどっか行ってたよ!" },
      { startSec: 11.94, endSec: 13.14, ja: "うん、あとでね…", furigana: "うん、あとでね…" },
      { startSec: 15.94, endSec: 17.94, ja: "うー、とってもいたそう!", furigana: "うー、とってもいたそう!" },
      { startSec: 17.94, endSec: 19.74, ja: "もう一回見てなかった!", furigana: "もう一回見てなかった!" },
      { startSec: 21.42, endSec: 23.14, ja: "よーし、こんなもんだろう!", furigana: "よーし、こんなもんだろう!" },
      { startSec: 23.14, endSec: 25.44, ja: "お尻の治療はこれで完了だよ!", furigana: "お尻の治療はこれで完了だよ!" },
      { startSec: 25.6, endSec: 26.94, ja: "僕のお尻大丈夫?", furigana: "僕のお尻大丈夫?" },
      { startSec: 27.18, endSec: 28.36, ja: "うー、平気だよ!", furigana: "うー、平気だよ!" },
      { startSec: 28.36, endSec: 29.64, ja: "でも大変だった!", furigana: "でも大変だった!" },
      { startSec: 29.9, endSec: 32.7, ja: "つなぎ合わせの24時間もかかったんだ!", furigana: "つなぎ合わせの24時間もかかったんだ!" },
      { startSec: 32.7, endSec: 35.34, ja: "シューツには保地キストのりを使った!", furigana: "シューツには保地キストのりを使った!" },
      { startSec: 35.34, endSec: 39.86, ja: "君は本当にラキラキラキラキラキーボーアイだね!", furigana: "君は本当にラキラキラキラキラキーボーアイだね!" },
      { startSec: 39.86, endSec: 41.44, ja: "でも中国してくよ!", furigana: "でも中国してくよ!" },
      { startSec: 41.44, endSec: 42.82, ja: "今は気をつけるんだ!", furigana: "今は気をつけるんだ!" },
      { startSec: 42.82, endSec: 44.58, ja: "もしもう一度けが押したら、", furigana: "もしもう一度けが押したら、" },
      { startSec: 44.58, endSec: 47.38, ja: "君のお尻はあんなことになっちゃうかもしれない!", furigana: "君のお尻はあんなことになっちゃうかもしれない!" },
      { startSec: 47.38, endSec: 48.78, ja: "別のお尻だ!", furigana: "別のお尻だ!" },
      { startSec: 48.78, endSec: 50.44, ja: "あーもう…", furigana: "あーもう…" },
      { startSec: 50.44, endSec: 52.34, ja: "お尻がかいよ!", furigana: "お尻がかいよ!" },
      { startSec: 52.34, endSec: 54.18, ja: "うー!", furigana: "うー!" },
      { startSec: 54.18, endSec: 55.18, ja: "うー!", furigana: "うー!" },
      { startSec: 55.18, endSec: 55.94, ja: "今、どうぞ!", furigana: "今、どうぞ!" },
      { startSec: 55.94, endSec: 56.94, ja: "最後!", furigana: "最後!" },
      { startSec: 56.94, endSec: 59.18, ja: "うーふっ!", furigana: "うーふっ!" },
      { startSec: 59.18, endSec: 61.18, ja: "うー!", furigana: "うー!" },
      { startSec: 61.18, endSec: 62.68, ja: "お尻は治った?", furigana: "お尻は治った?" },
      { startSec: 62.68, endSec: 64.68, ja: "うー!", furigana: "うー!" },
      { startSec: 64.68, endSec: 66.68, ja: "うー!", furigana: "うー!" },
      { startSec: 66.68, endSec: 68.68, ja: "うー!", furigana: "うー!" },
      { startSec: 68.68, endSec: 69.68, ja: "うー!", furigana: "うー!" },
      { startSec: 69.68, endSec: 70.18, ja: "うーん…", furigana: "うーん…" },
      { startSec: 70.18, endSec: 71.68, ja: "お尻があった!", furigana: "お尻があった!" },
      { startSec: 71.68, endSec: 72.68, ja: "み…", furigana: "み…" },
      { startSec: 72.68, endSec: 73.88, ja: "ネスポンジバベー!", furigana: "ネスポンジバベー!" },
      { startSec: 73.88, endSec: 75.48, ja: "またボードやりに行かない?", furigana: "またボードやりに行かない?" },
      { startSec: 75.48, endSec: 76.68, ja: "どうしたの?", furigana: "どうしたの?" },
      { startSec: 76.68, endSec: 78.48, ja: "いやー、君たち…", furigana: "いやー、君たち…" },
      { startSec: 78.48, endSec: 80.38, ja: "外は楽しいかい…", furigana: "外は楽しいかい…" },
      { startSec: 80.38, endSec: 83.18, ja: "部屋の真ん中で一体何をやってるのよ?", furigana: "部屋の真ん中で一体何をやってるのよ?" },
      { startSec: 83.18, endSec: 86.88, ja: "もうこりの人生は安全にその仕事にしたんだ!", furigana: "もうこりの人生は安全にその仕事にしたんだ!" },
      { startSec: 86.98, endSec: 89.58, ja: "おすすめだよ、君たちもどう?", furigana: "おすすめだよ、君たちもどう?" },
      { startSec: 89.58, endSec: 92.78, ja: "けがの影で外は危険だって真んなんだ!", furigana: "けがの影で外は危険だって真んなんだ!" },
      { startSec: 92.78, endSec: 94.38, ja: "危ないとこだった…", furigana: "危ないとこだった…" },
      { startSec: 94.38, endSec: 95.58, ja: "でももし…", furigana: "でももし…" },
      { startSec: 95.58, endSec: 98.58, ja: "この終わり絶対言えの外には一歩も出ないよ!", furigana: "この終わり絶対言えの外には一歩も出ないよ!" },
      { startSec: 98.58, endSec: 100.08, ja: "バカなこと言わないだよ!", furigana: "バカなこと言わないだよ!" },
      { startSec: 100.08, endSec: 101.58, ja: "僕はじゃないよ!", furigana: "僕はじゃないよ!" },
      { startSec: 101.58, endSec: 103.08, ja: "バカって何ね?", furigana: "バカって何ね?" },
      { startSec: 103.08, endSec: 104.88, ja: "うー!", furigana: "うー!" },
      { startSec: 108.68, endSec: 110.18, ja: "ごめん…", furigana: "ごめん…" },
      { startSec: 110.18, endSec: 111.98, ja: "パートリックの言う通りだよ!", furigana: "パートリックの言う通りだよ!" },
      { startSec: 111.98, endSec: 113.38, ja: "僕も見ただろ?", furigana: "僕も見ただろ?" },
      { startSec: 113.38, endSec: 115.38, ja: "次はお尻だけじゃなくて", furigana: "次はお尻だけじゃなくて" },
      { startSec: 115.48, endSec: 117.88, ja: "お尻の下やお尻こだって危険なんだ!", furigana: "お尻の下やお尻こだって危険なんだ!" },
      { startSec: 117.88, endSec: 119.58, ja: "お尻も危険だ!", furigana: "お尻も危険だ!" },
      { startSec: 119.58, endSec: 121.58, ja: "自然にさからちゃいけないんだ!", furigana: "自然にさからちゃいけないんだ!" },
      { startSec: 121.58, endSec: 123.38, ja: "僕はスポンジなんだよ!", furigana: "僕はスポンジなんだよ!" },
      { startSec: 123.38, endSec: 126.38, ja: "つまり歩いたりする方がおかしいんだよ!", furigana: "つまり歩いたりする方がおかしいんだよ!" },
      { startSec: 126.38, endSec: 128.38, ja: "家の中に一人ぼっちだよ!", furigana: "家の中に一人ぼっちだよ!" },
      { startSec: 128.38, endSec: 130.08, ja: "ね、寂しくないの?", furigana: "ね、寂しくないの?" },
      { startSec: 130.08, endSec: 132.68, ja: "一人じゃないよ、友達ならいるさ!", furigana: "一人じゃないよ、友達ならいるさ!" },
      { startSec: 132.68, endSec: 133.48, ja: "ほら!", furigana: "ほら!" },
      { startSec: 133.48, endSec: 135.48, ja: "近いん君でしょ?", furigana: "近いん君でしょ?" },
      { startSec: 135.48, endSec: 137.18, ja: "チップコンに…", furigana: "チップコンに…" },
      { startSec: 137.18, endSec: 139.38, ja: "逆尺で反駆ちこんも!", furigana: "逆尺で反駆ちこんも!" },
      { startSec: 139.38, endSec: 142.18, ja: "じゃあ、カニカーニの仕事はどうするの?", furigana: "じゃあ、カニカーニの仕事はどうするの?" },
      { startSec: 142.18, endSec: 144.68, ja: "問題ありません!", furigana: "問題ありません!" },
      { startSec: 144.78, endSec: 145.68, ja: "よいしょ!", furigana: "よいしょ!" },
      { startSec: 145.68, endSec: 147.68, ja: "よらくこんな感じ!", furigana: "よらくこんな感じ!" },
      { startSec: 147.68, endSec: 150.68, ja: "何がいっぱい考えして!", furigana: "何がいっぱい考えして!" },
      { startSec: 150.68, endSec: 152.18, ja: "じゃ、食事は?", furigana: "じゃ、食事は?" },
      { startSec: 152.18, endSec: 153.68, ja: "僕はスポンジだよ?", furigana: "僕はスポンジだよ?" },
      { startSec: 153.68, endSec: 154.68, ja: "空気で中分!", furigana: "空気で中分!" },
      { startSec: 164.68, endSec: 166.18, ja: "三字ボーって!", furigana: "三字ボーって!" },
      { startSec: 166.18, endSec: 168.68, ja: "いつまでも家の中にいられるわけないでしょ?", furigana: "いつまでも家の中にいられるわけないでしょ?" },
      { startSec: 168.68, endSec: 170.18, ja: "僕決めたんだ!", furigana: "僕決めたんだ!" },
      { startSec: 170.18, endSec: 171.68, ja: "もちろん絶対外に当てない!", furigana: "もちろん絶対外に当てない!" },
      { startSec: 171.68, endSec: 173.18, ja: "絶対に絶対に!", furigana: "絶対に絶対に!" },
      { startSec: 173.18, endSec: 175.38, ja: "絶対に絶対に!", furigana: "絶対に絶対に!" },
      { startSec: 175.38, endSec: 183.68, ja: "絶対絶対絶対絶対 …?", furigana: "絶対絶対絶対絶対 …?" },
      { startSec: 190.18, endSec: 193.18, ja: "チップコン2人程はまでお送りして…", furigana: "チップコン2人程はまでお送りして…" },
      { startSec: 200.18, endSec: 201.18, ja: "いい分かった?", furigana: "いい分かった?" },
      { startSec: 201.18, endSec: 203.18, ja: "よ 両会", furigana: "よ 両会" },
      { startSec: 205.18, endSec: 207.18, ja: "あなたの勝ちね", furigana: "あなたの勝ちね" },
      { startSec: 207.18, endSec: 209.18, ja: "諦めた 家にいればいいわ", furigana: "諦めた 家にいればいいわ" },
      { startSec: 209.18, endSec: 211.18, ja: "あなたの決意は手強りも固い", furigana: "あなたの決意は手強りも固い" },
      { startSec: 211.18, endSec: 213.18, ja: "さあ 今よ", furigana: "さあ 今よ" },
      { startSec: 215.18, endSec: 217.18, ja: "やー 取りるのか", furigana: "やー 取りるのか" },
      { startSec: 217.18, endSec: 219.18, ja: "出せて 順番だ", furigana: "出せて 順番だ" },
      { startSec: 224.18, endSec: 225.18, ja: "まあいっちゃうな", furigana: "まあいっちゃうな" },
      { startSec: 225.18, endSec: 227.18, ja: "本当涙かましい取り�くだね", furigana: "本当涙かましい取り�くだね" },
      { startSec: 227.18, endSec: 229.18, ja: "そのゴリラ 去年のハロウィンで", furigana: "そのゴリラ 去年のハロウィンで" },
      { startSec: 229.18, endSec: 231.18, ja: "バトリックが来てたキグロみたいよ", furigana: "バトリックが来てたキグロみたいよ" },
      { startSec: 231.18, endSec: 233.18, ja: "うーん いいそうだっけ?", furigana: "うーん いいそうだっけ?" },
      { startSec: 233.18, endSec: 235.18, ja: "大学たせるよ", furigana: "大学たせるよ" },
      { startSec: 235.18, endSec: 237.18, ja: "いやーしアンディー", furigana: "いやーしアンディー" },
      { startSec: 237.18, endSec: 238.18, ja: "こいつ誰?", furigana: "こいつ誰?" },
      { startSec: 239.18, endSec: 241.18, ja: "ゴリラのキグルミは?", furigana: "ゴリラのキグルミは?" },
      { startSec: 241.18, endSec: 243.18, ja: "ゴリラが来てるよ", furigana: "ゴリラが来てるよ" },
      { startSec: 244.18, endSec: 246.18, ja: "結構本物ぽかったでしょ?", furigana: "結構本物ぽかったでしょ?" },
      { startSec: 246.18, endSec: 248.18, ja: "わかったわ", furigana: "わかったわ" },
      { startSec: 248.18, endSec: 249.18, ja: "じゃああれは?", furigana: "じゃああれは?" },
      { startSec: 252.18, endSec: 254.18, ja: "あっ 本物のゴリラ!", furigana: "あっ 本物のゴリラ!" },
      { startSec: 254.18, endSec: 255.18, ja: "はっ", furigana: "はっ" },
      { startSec: 255.18, endSec: 257.18, ja: "やー", furigana: "やー" },
      { startSec: 257.18, endSec: 259.18, ja: "やー", furigana: "やー" },
      { startSec: 265.18, endSec: 267.18, ja: "やー", furigana: "やー" },
      { startSec: 267.18, endSec: 269.18, ja: "やー", furigana: "やー" },
      { startSec: 271.18, endSec: 273.18, ja: "やー", furigana: "やー" },
    ],
    questions: [
      { id: "sb01", kind: "listening_mcq", atSec: 26, promptRu: "Что завершилось, по словам персонажа?", optionsRu: ["Операция на руке", "Лечение попы", "Ремонт дома", "Приготовление еды"], correctIndex: 1, explanationRu: "お尻の治療はこれで完了だよ = Лечение попы на этом завершено!" },
      { id: "sb02", kind: "kanji_translate", atSec: 26, promptRu: "Переведите「治療」.", kanji: "治療", acceptedRu: ["лечение", "терапия"] },
      { id: "sb03", kind: "kanji_translate", atSec: 27, promptRu: "Переведите「完了」.", kanji: "完了", acceptedRu: ["завершение", "окончание", "готово", "завершено"] },
      { id: "sb04", kind: "listening_mcq", atSec: 29, promptRu: "Что означает「大丈夫」?", optionsRu: ["Опасно", "Всё в порядке", "Больно", "Трудно"], correctIndex: 1, explanationRu: "大丈夫 = всё в порядке, ОК." },
      { id: "sb05", kind: "listening_mcq", atSec: 31, promptRu: "Как персонаж описывает ситуацию?", optionsRu: ["Было легко", "Было весело", "Было трудно", "Было быстро"], correctIndex: 2, explanationRu: "でも大変だった = Но было трудно!" },
      { id: "sb06", kind: "kanji_translate", atSec: 31, promptRu: "Переведите「大変」.", kanji: "大変", acceptedRu: ["трудно", "тяжело", "серьёзно", "ужасно"] },
      { id: "sb07", kind: "word_order", atSec: 44, promptRu: "Соберите: «Сейчас будь осторожен!»", words: ["つけるんだ", "を", "気", "は", "今"], correctOrder: [4, 3, 2, 1, 0], explanationRu: "今は気をつけるんだ！" },
      { id: "sb08", kind: "listening_mcq", atSec: 49, promptRu: "Что может случиться, по предупреждению?", optionsRu: ["Попа может снова пострадать", "Дом сломается", "Друзья уйдут", "Еда закончится"], correctIndex: 0, explanationRu: "～なっちゃうかもしれない = может стать (плохо)." },
      { id: "sb09", kind: "listening_mcq", atSec: 84, promptRu: "Что спрашивает Сэнди?", optionsRu: ["Что ты ешь?", "Что ты делаешь посреди комнаты?", "Куда ты идёшь?", "Почему ты грустный?"], correctIndex: 1, explanationRu: "部屋の真ん中で一体何をやってるのよ？= Что ты вообще делаешь посреди комнаты?" },
      { id: "sb10", kind: "kanji_translate", atSec: 84, promptRu: "Переведите「部屋」.", kanji: "部屋", acceptedRu: ["комната"] },
      { id: "sb11", kind: "word_order", atSec: 96, promptRu: "Соберите: «Снаружи опасно!»", words: ["危険", "は", "外", "だ"], correctOrder: [2, 1, 0, 3], explanationRu: "外は危険だ！" },
      { id: "sb12", kind: "listening_mcq", atSec: 123, promptRu: "Что нельзя делать, по словам Спанчбоба?", optionsRu: ["Есть много", "Идти против природы", "Спать днём", "Бегать"], correctIndex: 1, explanationRu: "自然にさからっちゃいけないんだ = Нельзя идти против природы!" },
      { id: "sb13", kind: "kanji_translate", atSec: 123, promptRu: "Переведите「自然」.", kanji: "自然", acceptedRu: ["природа", "естественный"] },
      { id: "sb14", kind: "listening_mcq", atSec: 134, promptRu: "Спанчбоб говорит, что он не один, потому что:", optionsRu: ["У него есть работа", "У него есть друзья", "У него есть еда", "У него есть телевизор"], correctIndex: 1, explanationRu: "一人じゃないよ、友達ならいるさ = Я не один, друзья-то есть!" },
    ],
    grammarNotes: [
      {
        titleJa: "～ちゃいけない",
        titleRu: "Нельзя делать (разговорная форма)",
        level: "N4",
        structure: "〔て-форма глагола〕＋は → ちゃ ＋ いけない",
        explanationRu:
          "Разговорное сокращение от ～てはいけない. Выражает запрет: «нельзя делать». В аниме и повседневной речи ては сокращается до ちゃ (для て) или じゃ (для で).",
        examples: [
          { ja: "自然にさからっちゃいけない。", furigana: "しぜん に さからっちゃ いけない。", ru: "Нельзя идти против природы." },
          { ja: "ここで食べちゃいけない。", furigana: "ここ で たべちゃ いけない。", ru: "Здесь нельзя есть." },
          { ja: "遅れちゃいけないよ。", furigana: "おくれちゃ いけない よ。", ru: "Нельзя опаздывать." },
        ],
        tip: "ちゃ = ては (разговорное). Часто встречается в аниме.",
      },
      {
        titleJa: "～かもしれない",
        titleRu: "Возможно / может быть",
        level: "N4",
        structure: "〔普通形〕＋ かもしれない",
        explanationRu:
          "Выражает неуверенность или предположение: «может быть», «возможно». Присоединяется к обычной (словарной) форме глагола, прилагательного или существительного.",
        examples: [
          { ja: "あんなことになっちゃうかもしれない。", furigana: "あんな こと に なっちゃう かも しれない。", ru: "Может стать вот так (плохо)." },
          { ja: "明日は雨かもしれない。", furigana: "あした は あめ かも しれない。", ru: "Завтра, возможно, дождь." },
          { ja: "彼は来ないかもしれない。", furigana: "かれ は こない かも しれない。", ru: "Он, может, не придёт." },
        ],
        tip: "В вежливой речи: かもしれません.",
      },
      {
        titleJa: "～わけない",
        titleRu: "Не может быть / невозможно",
        level: "N4",
        structure: "〔辞書形 / ない形〕＋ わけない / わけがない",
        explanationRu:
          "Выражает невозможность: «не может быть, чтобы...». Часто используется для эмоционального отрицания.",
        examples: [
          { ja: "いつまでも家の中にいられるわけないでしょ？", furigana: "いつまでも いえ の なか に いられる わけ ない でしょ？", ru: "Не может быть, что ты вечно будешь дома, правда?" },
          { ja: "そんなことできるわけない。", furigana: "そんな こと できる わけ ない。", ru: "Такое невозможно сделать." },
          { ja: "知らないわけがない。", furigana: "しらない わけ が ない。", ru: "Не может быть, чтобы не знал." },
        ],
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  //  narezki-26 — N4 — Мультфильм: приключения в большом городе (~3 min)
  // ═══════════════════════════════════════════════════════════════
  {
    id: "n4-big-city",
    level: "N4",
    titleRu: "Приключения в большом городе",
    descriptionRu:
      "Друзья приезжают в большой город и хотят всё попробовать. Лексика: 大都会, 美味しい, 流行る, 許す. Грамматика: ～たい, ～てみたい, ～てもらえますか.",
    video: { type: "remote", src: "https://archive.org/download/japanese-trainer-narezki/narezki-26.mp4" },
    subtitles: [
      { startSec: 0, endSec: 4, ja: "私のエクエストミレファン", furigana: "私のエクエストミレファン" },
      { startSec: 10, endSec: 12, ja: "ここはキャンタラッドシティ", furigana: "ここはキャンタラッドシティ" },
      { startSec: 12, endSec: 15, ja: "今日はこの大都会で1日十好きなこと", furigana: "今日はこの大都会で1日十好きなこと" },
      { startSec: 15, endSec: 17, ja: "何だってしていいんだよね", furigana: "何だってしていいんだよね" },
      { startSec: 17, endSec: 19, ja: "わぁ、場所を見て回りたいわ", furigana: "わぁ、場所を見て回りたいわ" },
      { startSec: 19, endSec: 20, ja: "美味しいもの食べたい", furigana: "美味しいもの食べたい" },
      { startSec: 20, endSec: 22, ja: "私はおかけろしたい", furigana: "私はおかけろしたい" },
      { startSec: 22, endSec: 24, ja: "おかしいおペロペロのリアクだよ", furigana: "おかしいおペロペロのリアクだよ" },
      { startSec: 24, endSec: 28, ja: "最近街で流行ってるっていうパスケーキを食べてみたいんだ", furigana: "最近街で流行ってるっていうパスケーキを食べてみたいんだ" },
      { startSec: 28, endSec: 30, ja: "半分がプリムパフで半分かかっこくパスケーキ", furigana: "半分がプリムパフで半分かかっこくパスケーキ" },
      { startSec: 30, endSec: 34, ja: "この街なら何だってできるわね", furigana: "この街なら何だってできるわね" },
      { startSec: 34, endSec: 36, ja: "誰か助けて", furigana: "だれか たすけて" },
      { startSec: 36, endSec: 38, ja: "そいつに帽子を分析された", furigana: "そいつ に ぼうし を ぶんせき された" },
      { startSec: 38, endSec: 40, ja: "まだパスケーキがおわすけ", furigana: "まだパスケーキがおわすけ" },
      { startSec: 40, endSec: 42, ja: "手に乗ればよ", furigana: "手に乗ればよ" },
      { startSec: 58, endSec: 60, ja: "あちよ", furigana: "あちよ" },
      { startSec: 88, endSec: 90, ja: "いいけどあちだよ", furigana: "いいけどあちだよ" },
      { startSec: 100, endSec: 106, ja: "あのえっとすみませんがその帽子を返してもらえますか", furigana: "あの えっと すみません が その ぼうし を かえして もらえます か" },
      { startSec: 114, endSec: 117, ja: "彼女にプレゼントしたって喜ばないわよ", furigana: "彼女にプレゼントしたって喜ばないわよ" },
      { startSec: 118, endSec: 121, ja: "ごめんなさい、許して", furigana: "ごめんなさい、許して" },
      { startSec: 123, endSec: 126, ja: "考える時間はいっぱいある、反省して", furigana: "考える時間はいっぱいある、反省して" },
      { startSec: 126, endSec: 127, ja: "ケーム車の中でね", furigana: "ケーム車の中でね" },
      { startSec: 133, endSec: 135, ja: "半分のためでかかったんだ", furigana: "半分のためでかかったんだ" },
    ],
    questions: [
      { id: "bc01", kind: "listening_mcq", atSec: 18, promptRu: "Что герои могут делать весь день?", optionsRu: ["Работать", "Что угодно", "Только есть", "Только гулять"], correctIndex: 1, explanationRu: "何だってしていいんだよね = Можно делать что угодно, правда?" },
      { id: "bc02", kind: "listening_mcq", atSec: 21, promptRu: "Что хочет делать одна из героинь?", optionsRu: ["Спать", "Осмотреть места", "Купить одежду", "Поехать домой"], correctIndex: 1, explanationRu: "場所を見て回りたい = Хочу осмотреть места." },
      { id: "bc03", kind: "kanji_translate", atSec: 21, promptRu: "Переведите「美味しい」.", kanji: "美味しい", acceptedRu: ["вкусный", "вкусно"] },
      { id: "bc04", kind: "word_order", atSec: 29, promptRu: "Соберите: «Хочу попробовать поесть»", words: ["みたい", "て", "食べ"], correctOrder: [2, 1, 0], explanationRu: "食べてみたい = хочу попробовать поесть." },
      { id: "bc05", kind: "listening_mcq", atSec: 29, promptRu: "Что популярно в городе?", optionsRu: ["Рамен", "Пирожные (パスケーキ)", "Суши", "Такояки"], correctIndex: 1, explanationRu: "最近街で流行ってるっていうパスケーキ = Пирожные, которые сейчас популярны в городе." },
      { id: "bc06", kind: "kanji_translate", atSec: 35, promptRu: "Переведите「街」.", kanji: "街", acceptedRu: ["город", "улица", "квартал"] },
      { id: "bc07", kind: "listening_mcq", atSec: 37, promptRu: "Что кричит персонаж?", optionsRu: ["Привет!", "Помогите!", "Стойте!", "Бегите!"], correctIndex: 1, explanationRu: "誰か助けて！= Кто-нибудь, помогите!" },
      { id: "bc08", kind: "word_order", atSec: 107, promptRu: "Соберите: «Верните, пожалуйста, шляпу»", words: ["もらえますか", "て", "返し", "を", "帽子", "その"], correctOrder: [5, 4, 3, 2, 1, 0], explanationRu: "その帽子を返してもらえますか。" },
      { id: "bc09", kind: "kanji_translate", atSec: 107, promptRu: "Переведите「返す」.", kanji: "返す", acceptedRu: ["вернуть", "возвращать"] },
      { id: "bc10", kind: "listening_mcq", atSec: 122, promptRu: "Что говорит персонаж, извиняясь?", optionsRu: ["Спасибо", "Простите, пожалуйста", "До свидания", "Подождите"], correctIndex: 1, explanationRu: "ごめんなさい、許して = Простите, пожалуйста." },
      { id: "bc11", kind: "kanji_translate", atSec: 122, promptRu: "Переведите「許す」.", kanji: "許す", acceptedRu: ["прощать", "простить"] },
      { id: "bc12", kind: "listening_mcq", atSec: 127, promptRu: "Что предлагают персонажу?", optionsRu: ["Отдохнуть", "Подумать и раскаяться", "Поесть", "Поспать"], correctIndex: 1, explanationRu: "考える時間はいっぱいある、反省して = Времени подумать полно, раскайся." },
    ],
    grammarNotes: [
      {
        titleJa: "～たい",
        titleRu: "Хочу (сделать)",
        level: "N4",
        structure: "〔ます-основа〕＋ たい",
        explanationRu:
          "Выражает желание говорящего. Образуется от ます-основы глагола + たい. Спрягается как い-прилагательное: たかった (хотел), たくない (не хочу).",
        examples: [
          { ja: "場所を見て回りたい。", furigana: "ばしょ を みて まわりたい。", ru: "Хочу осмотреть места." },
          { ja: "美味しいもの食べたい。", furigana: "おいしい もの たべたい。", ru: "Хочу поесть вкусного." },
          { ja: "日本に行きたい。", furigana: "にほん に いきたい。", ru: "Хочу поехать в Японию." },
        ],
        tip: "～たい используется только для своих желаний. Для чужих: ～たがっている.",
      },
      {
        titleJa: "～てみたい",
        titleRu: "Хочу попробовать (сделать)",
        level: "N4",
        structure: "〔て-форма〕＋ みたい",
        explanationRu:
          "Комбинация て-формы + みる (попробовать) + たい (хочу). Означает «хочу попробовать сделать что-то впервые».",
        examples: [
          { ja: "パスケーキを食べてみたい。", furigana: "パスケーキ を たべて みたい。", ru: "Хочу попробовать пирожные." },
          { ja: "着物を着てみたい。", furigana: "きもの を きて みたい。", ru: "Хочу попробовать надеть кимоно." },
          { ja: "日本語で話してみたい。", furigana: "にほんご で はなして みたい。", ru: "Хочу попробовать поговорить по-японски." },
        ],
      },
      {
        titleJa: "～てもらえますか",
        titleRu: "Не могли бы вы (сделать)?",
        level: "N4",
        structure: "〔て-форма〕＋ もらえますか",
        explanationRu:
          "Вежливая просьба: «не могли бы вы сделать для меня?». Более мягкая, чем ～てください.",
        examples: [
          { ja: "帽子を返してもらえますか。", furigana: "ぼうし を かえして もらえます か。", ru: "Не могли бы вы вернуть шляпу?" },
          { ja: "ちょっと待ってもらえますか。", furigana: "ちょっと まって もらえます か。", ru: "Не могли бы вы подождать?" },
          { ja: "写真を撮ってもらえますか。", furigana: "しゃしん を とって もらえます か。", ru: "Не могли бы вы сфотографировать?" },
        ],
        tip: "Ещё вежливее: ～ていただけますか.",
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  //  narezki-31 — N4 — Эминенция в тени: похвала и ложь (~2 min)
  // ═══════════════════════════════════════════════════════════════
  {
    id: "n3-eminence-shadow",
    level: "N4",
    titleRu: "Аниме: похвала, ложь и поддержка",
    descriptionRu:
      "Лексика: 見事, 嬉しい, 嘘, 心配. Грамматика: ～なんて, ～ことによって, いつも通り.",
    video: { type: "remote", src: "https://archive.org/download/japanese-trainer-narezki/narezki-31.mp4" },
    subtitles: [
      { startSec: 0, endSec: 2, ja: "カゲ実", furigana: "カゲ実" },
      { startSec: 6, endSec: 8, ja: "ありがと月やってくれて", furigana: "ありがと月やってくれて" },
      { startSec: 8, endSec: 10, ja: "いいよ 当然のことであります", furigana: "いいよ 当然のことであります" },
      { startSec: 12, endSec: 14, ja: "ところで", furigana: "ところで" },
      { startSec: 14, endSec: 16, ja: "どうでした？私の演技は", furigana: "どう でした？ わたし の えんぎ は" },
      { startSec: 16, endSec: 18, ja: "それを", furigana: "それを" },
      { startSec: 18, endSec: 22, ja: "ガンマ様の演技は本当に見事でした", furigana: "ガンマさま の えんぎ は ほんとう に みごと でした" },
      { startSec: 22, endSec: 23, ja: "本当?", furigana: "本当?" },
      { startSec: 23, endSec: 26, ja: "うん そうですね 買い", furigana: "うん そうですね 買い" },
      { startSec: 30, endSec: 32, ja: "どうしたの?", furigana: "どうしたの?" },
      { startSec: 32, endSec: 34, ja: "カイもガンマ様の演技の素晴らしさに", furigana: "カイ も ガンマさま の えんぎ の すばらしさ に" },
      { startSec: 34, endSec: 36, ja: "完営を受けたと言っています", furigana: "完営を受けたと言っています" },
      { startSec: 36, endSec: 40, ja: "二人に褒められるなんて本当に嬉しいわ", furigana: "二人に褒められるなんて本当に嬉しいわ" },
      { startSec: 40, endSec: 42, ja: "二人たまお茶を入れましょう", furigana: "二人たまお茶を入れましょう" },
      { startSec: 42, endSec: 44, ja: "ありがとうございます", furigana: "ありがとうございます" },
      { startSec: 46, endSec: 48, ja: "カイ もうちょっとうまくやってくれ", furigana: "カイ もうちょっとうまくやってくれ" },
      { startSec: 48, endSec: 50, ja: "どうって", furigana: "どうって" },
      { startSec: 50, endSec: 52, ja: "私は嘘が好きでない", furigana: "私は嘘が好きでない" },
      { startSec: 52, endSec: 54, ja: "嘘とかそういう話じゃない", furigana: "嘘とかそういう話じゃない" },
      { startSec: 54, endSec: 56, ja: "ユーズが聞かないのもいい影にしろ", furigana: "ユーズが聞かないのもいい影にしろ" },
      { startSec: 56, endSec: 60, ja: "ガンマ様が落ち込むことによって起きる", furigana: "ガンマ様が落ち込むことによって起きる" },
      { startSec: 60, endSec: 62, ja: "これからの問題を考えてくれ", furigana: "これからの問題を考えてくれ" },
      { startSec: 62, endSec: 64, ja: "薄もない", furigana: "薄もない" },
      { startSec: 64, endSec: 66, ja: "お待たせーってどうしたの?", furigana: "お待たせーってどうしたの?" },
      { startSec: 66, endSec: 68, ja: "何もありません", furigana: "何もありません" },
      { startSec: 68, endSec: 70, ja: "そう", furigana: "そう" },
      { startSec: 70, endSec: 72, ja: "それにしてもアルファ様は心配症ね", furigana: "それにしてもアルファ様は心配症ね" },
      { startSec: 72, endSec: 74, ja: "あなたたち二人をつけるだなんて", furigana: "あなたたち二人をつけるだなんて" },
      { startSec: 74, endSec: 76, ja: "それでもお金り心配で", furigana: "それでもお金り心配で" },
      { startSec: 76, endSec: 80, ja: "ガンマ様の優秀を", furigana: "ガンマ様の優秀を" },
      { startSec: 80, endSec: 82, ja: "報告するものが必要ですから", furigana: "報告するものが必要ですから" },
      { startSec: 82, endSec: 84, ja: "そう", furigana: "そう" },
      { startSec: 84, endSec: 86, ja: "そういうことだったのね", furigana: "そういうことだったのね" },
      { startSec: 86, endSec: 88, ja: "そういうことだったのです", furigana: "そういうことだったのです" },
      { startSec: 88, endSec: 90, ja: "アルファ様にも見せたかったわ", furigana: "アルファ様にも見せたかったわ" },
      { startSec: 90, endSec: 92, ja: "あの大義", furigana: "あの大義" },
      { startSec: 92, endSec: 96, ja: "手見たいしゃる", furigana: "手見たいしゃる" },
      { startSec: 96, endSec: 100, ja: "お目が", furigana: "お目が" },
      { startSec: 102, endSec: 104, ja: "こういう時", furigana: "こういう時" },
      { startSec: 104, endSec: 106, ja: "私はどういっていいかわからないんだ", furigana: "私はどういっていいかわからないんだ" },
      { startSec: 106, endSec: 110, ja: "こういう時はいつも通りでいいのよ", furigana: "こういう時はいつも通りでいいのよ" },
      { startSec: 110, endSec: 112, ja: "ガンマ様", furigana: "ガンマ様" },
      { startSec: 114, endSec: 116, ja: "話出ていますよ", furigana: "話出ていますよ" },
      { startSec: 116, endSec: 118, ja: "おろ", furigana: "おろ" },
    ],
    questions: [
      { id: "es01", kind: "listening_mcq", atSec: 16, promptRu: "О чём спрашивает Гамма?", optionsRu: ["О еде", "О своём выступлении", "О погоде", "О друзьях"], correctIndex: 1, explanationRu: "どうでした？私の演技は — Как было? Моё выступление..." },
      { id: "es02", kind: "kanji_translate", atSec: 22, promptRu: "Переведите「見事」.", kanji: "見事", acceptedRu: ["великолепно", "прекрасно", "замечательно", "блестяще"] },
      { id: "es03", kind: "listening_mcq", atSec: 24, promptRu: "Как оценили выступление Гаммы?", optionsRu: ["Ужасно", "Нормально", "Действительно великолепно", "Скучно"], correctIndex: 2, explanationRu: "本当に見事でした — Было действительно великолепно." },
      { id: "es04", kind: "word_order", atSec: 41, promptRu: "Соберите: «Быть похваленной — правда радостно!»", words: ["嬉しいわ", "本当に", "褒められるなんて"], correctOrder: [2, 1, 0], explanationRu: "褒められるなんて本当に嬉しいわ。" },
      { id: "es05", kind: "listening_mcq", atSec: 43, promptRu: "Что предлагает Гамма?", optionsRu: ["Пойти гулять", "Заварить чай", "Поесть", "Поспать"], correctIndex: 1, explanationRu: "お茶を入れましょう — Давайте заварим чай." },
      { id: "es06", kind: "kanji_translate", atSec: 52, promptRu: "Переведите「嘘」.", kanji: "嘘", acceptedRu: ["ложь", "враньё", "обман"] },
      { id: "es07", kind: "listening_mcq", atSec: 54, promptRu: "Что говорит Кай о себе?", optionsRu: ["Любит шутки", "Не любит ложь", "Любит сладкое", "Не любит чай"], correctIndex: 1, explanationRu: "私は嘘が好きでない — Я не люблю ложь." },
      { id: "es08", kind: "listening_mcq", atSec: 68, promptRu: "Что ответили на вопрос «Что случилось?»", optionsRu: ["Всё плохо", "Ничего", "Не знаю", "Много всего"], correctIndex: 1, explanationRu: "何もありません — Ничего (нет)." },
      { id: "es09", kind: "kanji_translate", atSec: 72, promptRu: "Переведите「心配」.", kanji: "心配", acceptedRu: ["беспокойство", "волнение", "тревога"] },
      { id: "es10", kind: "word_order", atSec: 110, promptRu: "Соберите: «В такие моменты — как обычно.»", words: ["いいのよ", "で", "いつも通り", "は", "こういう時"], correctOrder: [4, 3, 2, 1, 0], explanationRu: "こういう時はいつも通りでいいのよ。" },
    ],
    grammarNotes: [
      {
        titleJa: "～なんて",
        titleRu: "Восклицание удивления «и вдруг / такое как»",
        level: "N4",
        structure: "〔普通形〕＋ なんて",
        explanationRu:
          "Выражает удивление, восхищение или недоверие. «Такое, как... / Чтобы...!». Часто в эмоциональных фразах.",
        examples: [
          { ja: "褒められるなんて嬉しい。", furigana: "ほめられる なんて うれしい。", ru: "Быть похваленной — как приятно!" },
          { ja: "二人をつけるだなんて。", furigana: "ふたり を つける だ なんて。", ru: "Приставить к двоим — надо же." },
          { ja: "合格するなんて信じられない。", furigana: "ごうかく する なんて しんじられない。", ru: "Не верится, что сдал!" },
        ],
      },
      {
        titleJa: "いつも通り",
        titleRu: "Как обычно / как всегда",
        level: "N4",
        structure: "いつも通り（に）",
        explanationRu:
          "Означает «как обычно, как всегда». 通り (とおり) — «так, как». Используется для описания привычного поведения.",
        examples: [
          { ja: "こういう時はいつも通りでいいのよ。", furigana: "こういう とき は いつもどおり で いい の よ。", ru: "В такие моменты — как обычно, и всё." },
          { ja: "いつも通りに仕事をする。", furigana: "いつもどおり に しごと を する。", ru: "Работать как обычно." },
          { ja: "いつも通りの朝だった。", furigana: "いつもどおり の あさ だった。", ru: "Было обычное утро." },
        ],
      },
      {
        titleJa: "～ことによって",
        titleRu: "Посредством / из-за того, что",
        level: "N4",
        structure: "〔辞書形 / noun の〕＋ ことによって",
        explanationRu:
          "Выражает причину или средство: «посредством…», «из-за того, что…», «благодаря тому, что…». Более формальный аналог ～ことで. Часто встречается в объяснениях последствий действий.",
        examples: [
          { ja: "ガンマ様が落ち込むことによって問題が起きる。", furigana: "ガンマさま が おちこむ こと に よって もんだい が おきる。", ru: "Из-за того, что Гамма-сама расстроится, возникнут проблемы." },
          { ja: "練習することによって上手になる。", furigana: "れんしゅう する こと に よって じょうず に なる。", ru: "Благодаря практике становишься лучше." },
          { ja: "本を読むことによって知識が増える。", furigana: "ほん を よむ こと に よって ちしき が ふえる。", ru: "Посредством чтения книг знания растут." },
        ],
        tip: "～ことによって — более книжный стиль. В разговоре чаще: ～ことで.",
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  //  narezki-32 — N4 — Тикава: узнавание и хаос (~1.5 min)
  // ═══════════════════════════════════════════════════════════════
  {
    id: "n4-chikawa-chaos",
    level: "N4",
    titleRu: "Тикава: узнавание и хаос",
    descriptionRu:
      "Лексика: 絶対, ほんまの, 話しかける. Грамматика: ～じゃん, ～だっけ, ～てみよっか.",
    video: { type: "remote", src: "https://archive.org/download/japanese-trainer-narezki/narezki-32.mp4" },
    subtitles: [
      { startSec: 0, endSec: 2, ja: "チーカワー", furigana: "チーカワー" },
      { startSec: 7, endSec: 9, ja: "これってあれじゃん!", furigana: "これってあれじゃん!" },
      { startSec: 9, endSec: 10, ja: "あの、なんだっけ?", furigana: "あの、なんだっけ?" },
      { startSec: 10, endSec: 11, ja: "あれだよあれ!", furigana: "あれだよあれ!" },
      { startSec: 11, endSec: 12, ja: "あの、は…", furigana: "あの、は…" },
      { startSec: 13, endSec: 14, ja: "これ!", furigana: "これ!" },
      { startSec: 15, endSec: 16, ja: "こんなさ!", furigana: "こんなさ!" },
      { startSec: 16, endSec: 17, ja: "絶対あれじゃん!", furigana: "絶対あれじゃん!" },
      { startSec: 18, endSec: 19, ja: "ねこのさ!", furigana: "ねこのさ!" },
      { startSec: 20, endSec: 21, ja: "これでしょ!", furigana: "これでしょ!" },
      { startSec: 27, endSec: 28, ja: "ね?", furigana: "ね?" },
      { startSec: 28, endSec: 29, ja: "絶対ね!", furigana: "絶対ね!" },
      { startSec: 31, endSec: 32, ja: "うんうんうんうん", furigana: "うんうんうんうん" },
      { startSec: 36, endSec: 37, ja: "ほんまのだぁ", furigana: "ほんまのだぁ" },
      { startSec: 38, endSec: 39, ja: "いるんだね", furigana: "いるんだね" },
      { startSec: 39, endSec: 40, ja: "こういうとこにも", furigana: "こういうとこにも" },
      { startSec: 41, endSec: 42, ja: "てか", furigana: "てか" },
      { startSec: 44, endSec: 45, ja: "話かけてみよっか", furigana: "話かけてみよっか" },
      { startSec: 47, endSec: 48, ja: "なんで?", furigana: "なんで?" },
      { startSec: 48, endSec: 50, ja: "スピンカス!", furigana: "スピンカス!" },
      { startSec: 50, endSec: 51, ja: "スピンカス!", furigana: "スピンカス!" },
      { startSec: 51, endSec: 52, ja: "スピンカス!", furigana: "スピンカス!" },
      { startSec: 54, endSec: 55, ja: "ほっ!", furigana: "ほっ!" },
      { startSec: 55, endSec: 56, ja: "うああああああ!", furigana: "うああああああ!" },
      { startSec: 56, endSec: 57, ja: "スピンカス!", furigana: "スピンカス!" },
      { startSec: 57, endSec: 58, ja: "スピンカス!", furigana: "スピンカス!" },
      { startSec: 60, endSec: 62, ja: "スピンカス!", furigana: "スピンカス!" },
      { startSec: 90, endSec: 92, ja: "スピンカス!", furigana: "スピンカス!" },
    ],
    questions: [
      { id: "cc01", kind: "listening_mcq", atSec: 9, promptRu: "Что кричит персонаж, увидев что-то знакомое?", optionsRu: ["Это страшно!", "Это же то самое!", "Это красиво!", "Это новое!"], correctIndex: 1, explanationRu: "これってあれじゃん！— Это же то самое!" },
      { id: "cc02", kind: "listening_mcq", atSec: 10, promptRu: "Что означает「なんだっけ？」?", optionsRu: ["Что это?", "Как это называлось?", "Зачем это?", "Кто это?"], correctIndex: 1, explanationRu: "なんだっけ — Как же это называлось? (пытается вспомнить)" },
      { id: "cc03", kind: "kanji_translate", atSec: 17, promptRu: "Переведите「絶対」.", kanji: "絶対", acceptedRu: ["точно", "абсолютно", "обязательно", "однозначно"] },
      { id: "cc04", kind: "listening_mcq", atSec: 21, promptRu: "Что означает「これでしょ！」?", optionsRu: ["Это не то", "Это же оно!", "Это плохо", "Это далеко"], correctIndex: 1, explanationRu: "これでしょ！— Это же оно! (подтверждение)" },
      { id: "cc05", kind: "listening_mcq", atSec: 37, promptRu: "Что означает「ほんまのだぁ」?", optionsRu: ["Это подделка", "Это настоящее!", "Это странное", "Это старое"], correctIndex: 1, explanationRu: "ほんまの = 本物の (настоящее), кансайский диалект." },
      { id: "cc06", kind: "listening_mcq", atSec: 40, promptRu: "Персонаж удивлён, что существо:", optionsRu: ["Ушло", "Есть и в таком месте", "Спит", "Ест"], correctIndex: 1, explanationRu: "こういうとこにも いるんだね — Оказывается, и в таких местах есть." },
      { id: "cc07", kind: "word_order", atSec: 45, promptRu: "Соберите: «Попробуем заговорить?»", words: ["みよっか", "て", "話しかけ"], correctOrder: [2, 1, 0], explanationRu: "話しかけてみよっか — Попробуем заговорить?" },
      { id: "cc08", kind: "listening_mcq", atSec: 48, promptRu: "Что спрашивает персонаж?", optionsRu: ["Когда?", "Где?", "Почему?", "Как?"], correctIndex: 2, explanationRu: "なんで？— Почему? / Зачем?" },
    ],
    grammarNotes: [
      {
        titleJa: "～じゃん",
        titleRu: "Ведь / же (разговорное подтверждение)",
        level: "N4",
        structure: "〔普通形〕＋ じゃん",
        explanationRu:
          "Разговорное сокращение от ～じゃないか. Используется для подтверждения очевидного факта: «это же...!». Очень часто в аниме и молодёжной речи.",
        examples: [
          { ja: "これってあれじゃん！", furigana: "これ って あれ じゃん！", ru: "Это же то самое!" },
          { ja: "絶対あれじゃん！", furigana: "ぜったい あれ じゃん！", ru: "Это точно оно!" },
          { ja: "すごいじゃん！", furigana: "すごい じゃん！", ru: "Круто же!" },
        ],
        tip: "じゃん — токийский разговорный стиль. В кансайском диалекте аналог: やん.",
      },
      {
        titleJa: "～てみる",
        titleRu: "Попробовать (сделать)",
        level: "N4",
        structure: "〔て-форма〕＋ みる",
        explanationRu:
          "Означает «попробовать сделать» — попытка нового действия. В разговоре: みよう → みよっか (давай попробуем?).",
        examples: [
          { ja: "話しかけてみよっか。", furigana: "はなしかけて みよっか。", ru: "Попробуем заговорить?" },
          { ja: "食べてみる。", furigana: "たべて みる。", ru: "Попробую поесть." },
          { ja: "やってみよう。", furigana: "やって みよう。", ru: "Давай попробуем!" },
        ],
      },
      {
        titleJa: "～んだね",
        titleRu: "Оказывается… / Вот как… (осознание)",
        level: "N4",
        structure: "〔普通形〕＋ んだね / のだね",
        explanationRu:
          "Выражает осознание, открытие нового факта: «оказывается…», «вот как…». ん — разговорное сокращение の (объяснительный の). ね добавляет оттенок подтверждения или эмоциональной реакции.",
        examples: [
          { ja: "いるんだね、こういうとこにも。", furigana: "いるんだね、こういう とこ に も。", ru: "Оказывается, и в таких местах есть." },
          { ja: "もう帰るんだね。", furigana: "もう かえるんだね。", ru: "Так ты уже уходишь, да…" },
          { ja: "日本語が上手なんだね。", furigana: "にほんご が じょうず なんだね。", ru: "Оказывается, ты хорошо говоришь по-японски." },
        ],
        tip: "んだ = のだ (объяснительный). С ね — мягкое подтверждение. С よ — утверждение: んだよ.",
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  //  narezki-33 — N4 — Комедийный диалог: лень и планы (~0.5 min)
  // ═══════════════════════════════════════════════════════════════
  {
    id: "n4-lazy-plans",
    level: "N4",
    titleRu: "Комедийный диалог: лень и планы на будущее",
    descriptionRu:
      "Короткий диалог: один персонаж бездельничает, другой требует искать подработку. Лексика: 将来, バイト, 暇, 忙しい. Грамматика: ～なさい, ～なんか, ～のに.",
    video: { type: "remote", src: "https://archive.org/download/japanese-trainer-narezki/narezki-33.mp4" },
    subtitles: [
      { startSec: 0, endSec: 2, ja: "どうするの?", furigana: "どうするの?" },
      { startSec: 2, endSec: 4, ja: "あなた将来は", furigana: "あなた将来は" },
      { startSec: 4, endSec: 6, ja: "うーん", furigana: "うーん" },
      { startSec: 6, endSec: 10, ja: "ごろごろしてる時に将来の話なんかしないでよ", furigana: "ごろごろしてる時に将来の話なんかしないでよ" },
      { startSec: 10, endSec: 14, ja: "ひまがあるならちょっとはバイトでも探しなさい", furigana: "ひまがあるならちょっとはバイトでも探しなさい" },
      { startSec: 14, endSec: 16, ja: "えぇ?", furigana: "えぇ?" },
      { startSec: 16, endSec: 20, ja: "ごろごろするのに忙しいからあとにするよ", furigana: "ごろごろするのに忙しいからあとにするよ" },
      { startSec: 20, endSec: 24, ja: "あーーー", furigana: "あーーー" },
      { startSec: 24, endSec: 26, ja: "つわないでー", furigana: "つわないでー" },
    ],
    questions: [
      { id: "lp01", kind: "listening_mcq", atSec: 5, promptRu: "О чём спрашивают персонажа?", optionsRu: ["О еде", "О будущем", "О друзьях", "О школе"], correctIndex: 1, explanationRu: "あなた将来は = А твоё будущее? (Что будешь делать?)" },
      { id: "lp02", kind: "kanji_translate", atSec: 5, promptRu: "Переведите「将来」.", kanji: "将来", acceptedRu: ["будущее"] },
      { id: "lp03", kind: "listening_mcq", atSec: 11, promptRu: "Что не хочет обсуждать персонаж, пока валяется?", optionsRu: ["Работу", "Разговоры о будущем", "Еду", "Учёбу"], correctIndex: 1, explanationRu: "ごろごろしてる時に将来の話なんかしないでよ = Не говори о будущем, когда я валяюсь!" },
      { id: "lp04", kind: "word_order", atSec: 15, promptRu: "Соберите: «Если есть свободное время, поищи подработку!»", words: ["探しなさい", "でも", "バイト", "は", "ちょっと", "なら", "暇がある"], correctOrder: [6, 5, 4, 3, 2, 1, 0], explanationRu: "暇があるならちょっとはバイトでも探しなさい。" },
      { id: "lp05", kind: "kanji_translate", atSec: 15, promptRu: "Переведите「暇」.", kanji: "暇", acceptedRu: ["свободное время", "досуг", "свободный"] },
      { id: "lp06", kind: "listening_mcq", atSec: 21, promptRu: "Почему персонаж откладывает поиск работы?", optionsRu: ["Болеет", "Занят бездельем", "Уже нашёл", "Не хочет работать"], correctIndex: 1, explanationRu: "ごろごろするのに忙しい = Занят тем, что валяюсь (ирония)." },
      { id: "lp07", kind: "kanji_translate", atSec: 21, promptRu: "Переведите「忙しい」.", kanji: "忙しい", acceptedRu: ["занятой", "занят", "загруженный"] },
    ],
    grammarNotes: [
      {
        titleJa: "～なさい",
        titleRu: "Делай! (мягкий приказ)",
        level: "N4",
        structure: "〔ます-основа〕＋ なさい",
        explanationRu:
          "Мягкая повелительная форма, часто используется родителями или учителями. Менее грубая, чем императив, но более настойчивая, чем ～てください.",
        examples: [
          { ja: "バイトでも探しなさい。", furigana: "バイト でも さがしなさい。", ru: "Поищи хотя бы подработку." },
          { ja: "早く寝なさい。", furigana: "はやく ねなさい。", ru: "Ложись спать быстрее." },
          { ja: "ちゃんと食べなさい。", furigana: "ちゃんと たべなさい。", ru: "Ешь нормально." },
        ],
        tip: "Часто слышно от мам в аниме: 勉強しなさい！(Учись!)",
      },
      {
        titleJa: "～なんか",
        titleRu: "Такое как... / пренебрежение",
        level: "N4",
        structure: "〔名詞〕＋ なんか",
        explanationRu:
          "Разговорная частица, выражающая пренебрежение или преуменьшение: «такое как...», «всякие там...». Более грубый вариант なんて.",
        examples: [
          { ja: "将来の話なんかしないでよ。", furigana: "しょうらい の はなし なんか しないで よ。", ru: "Не говори мне всякое там про будущее." },
          { ja: "勉強なんかしたくない。", furigana: "べんきょう なんか したくない。", ru: "Не хочу учиться (и подобное)." },
          { ja: "お金なんか関係ない。", furigana: "おかね なんか かんけい ない。", ru: "Деньги тут ни при чём." },
        ],
      },
      {
        titleJa: "～つもり",
        titleRu: "Намерен / собираюсь",
        level: "N4",
        structure: "〔辞書形〕＋ つもり（だ）/ 〔ない形〕＋ つもり（だ）",
        explanationRu:
          "Выражает намерение или план: «собираюсь сделать», «намерен». С ない-формой: «не собираюсь». Часто используется для разговоров о будущих планах.",
        examples: [
          { ja: "明日バイトを探すつもりだ。", furigana: "あした バイト を さがす つもり だ。", ru: "Завтра собираюсь искать подработку." },
          { ja: "ごろごろするつもりだよ。", furigana: "ごろごろ する つもり だ よ。", ru: "Собираюсь валяться." },
          { ja: "将来は日本に住むつもりです。", furigana: "しょうらい は にほん に すむ つもり です。", ru: "В будущем намерен жить в Японии." },
        ],
        tip: "～つもりだった = «собирался, но не сделал» (прошедшее нереализованное намерение).",
      },
    ],
  },

];

export { N4_NEW };
